REGUA_SPEC = {
    "ordem_de_leitura": "selo antes da frase",
    "versao": "régua final de 15/09/2026 (rodada sem dinheiro): proposta 'contra a sorte' do plano aprovado (sessao_14_09/dinheiro_parte1_resultado.json, chave plano.regua_final), com as quatro respostas do dono da noite de 14/09 e as decisões do coordenador; declarada em sessao_14_09/declaracoes_novas.json, chave regua_final",
    "perguntas": [
        "1. A comparação foi escrita antes de olhar?",
        "2. É firme? q de Benjamini-Hochberg < 0,05 na família declarada; num teste único declarado, q = p",
        "3. Foi conferida por outro caminho? Conferências testáveis: o 1º turno prevendo o 2º (p parcial < 0,05 E no lado declarado; não pelo q dos 28) e 2018-2021 (p < 0,05 E mesmo sinal); quando o teste é por ano (DIN-01, DIN-02), também 'cada ano sozinho' e 'deixando um ano de fora'",
        "4. A lista de onde ela saiu tem mais achados do que a sorte produz? (p do excesso < 0,05, contagem bruta)",
        "5. Só no físico: continua entre times que rodaram o elenco parecido? (p < 0,05 descontado SÓ o posto de atletas rastreados, fis_atletas ou fis_<setor>_atletas)",
    ],
    "saiu_da_regua_em_15_09": {
        "dinheiro": "o desconto pelo valor do elenco ('descontado o dinheiro', 'continua entre times/elencos de valor parecido') sai de todo selo, porta, marca, gate e frase de critério; o valor do elenco continua DESCRITO (etapa 1, régua H_dinheiro, DIN-*, cenários da etapa 14)",
        "ano_seguinte": "'o mesmo clube repete o número no ano seguinte' (rho_persist, esmaecido da etapa 9, rho < 0,15 da etapa 10) sai das conferências e do desempate; etapa_6.rho continua como DADO; as conclusões cujo assunto é a repetição (FIS-07, M1, M6, M7, ELE-06) ficam, com o selo",
        "tambem": ["os níveis liq e liq2 do excesso (liq2 vira rod)", "o controle da cobertura do valor na DIN-01", "a constante 'o desconto do dinheiro não se aplica'", "'dificilmente é sorte' e 'no limite' como rótulo de sorte"],
    },
    "selos": {
        "sem_sinal": "p >= 0,10; ou zona cinzenta (0,05 <= p < 0,10) sem p < 0,05 em outra comparação da mesma linha, com a palavra 'no limite'; a frase diz em palavras o que o estudo veria (16 x 48: 'só uma diferença grande apareceria'; 16 x 16: 'só uma muito grande'), com o tamanho em número só no rodapé (etapa_0.poder), e escreve 'não se viu'",
        "fraco": "zona cinzenta com p < 0,05 em outra comparação da mesma linha; OU, no físico, p_rod >= 0,05; OU declarada, não firme (q >= 0,05) e com a lista da família no nível da sorte; OU comparação escolhida depois de olhar sem lista ou com a lista dela no nível da sorte",
        "moderado": "comparação escolhida depois de olhar com a lista DELA acima da sorte (nunca forte); OU declarada e não firme com a lista da família acima da sorte; OU declarada e firme com alguma conferência testável que falhou (conferências que discordam: vale a mais fraca); OU declarada e firme SEM NENHUMA conferência testável (sem conferência testável = moderado, nunca forte); OU firme por pouco (0,025 <= q < 0,05) com UMA conferência testável só, mesmo que ela passe (regra geral, resposta a do dono); no físico, sempre com p_rod < 0,05",
        "forte": "declarada E firme (q < 0,05) E PELO MENOS UMA conferência testável E todas as testáveis passando E fora da cláusula firme por pouco com uma conferência só; no físico, também p_rod < 0,05; nunca por comparação escolhida depois de olhar. Repetição do atleta: regua.repeticao_do_atleta",
        "nao_da_para_afirmar": "só três casos: (a) pergunta de 'qual dos dois é maior' (duas medidas, dois períodos, dois grupos de atletas, duas bases, um nome contra o vizinho) com intervalo da diferença cruzando zero; (b) pergunta nunca medida porque o dado não existe; (c) duas contas sobre a mesma pergunta com lados opostos. Diferença entre grupos com p >= 0,10 é sem_sinal. Campo não gravado NÃO produz selo: tira a conclusão da tela (selo_documento_e_tela)",
    },
    "sem_conferencia_testavel": "nenhuma conferência testável = MODERADO, nunca FORTE (cláusula escrita com todas as letras; sem ela, ELE-01, ELE-02, ELE-03, FIS-04, J6, A2, M5 e M8 virariam fortes por não ter nada para conferir)",
    "firme_por_pouco": {"regra": "0,025 <= q < 0,05 (no q sem arredondar) com exatamente UMA conferência testável = MODERADO, mesmo que ela passe", "decisao": "resposta a do dono, 14/09 (noite), regra geral", "hoje_atinge": "J17"},
    "contas_da_mesma_pergunta": "no mesmo lado, uma passando do corte e a outra não: segue a conta declarada antes (J10, FIS-09); se nenhuma foi declarada antes, vale o selo mais fraco (ELE-06, J8, J9)",
    "zona_cinzenta": "0,05 <= p < 0,10: fraco se há p < 0,05 em outra comparação da mesma linha; senão sem_sinal com a palavra 'no limite' (o único lugar em que 'no limite' aparece)",
    "desempate": "quando conferências discordam, duas contas sobre a mesma medida discordam, ou dois céticos discordam, vale o selo mais fraco; o mesmo clube no ano seguinte não entra mais no desempate",
    "vocabulario_sorte": {
        "chaves": {"firme": "q < 0,05 (teste único: q = p)", "pode_ser_sorte": "p < 0,05 e q >= 0,05", "sem_diferenca": "p >= 0,05 ('sem diferença clara'; ρ: 'sem relação clara'; grupos: 'sem separação clara')"},
        "por_pouco": "só atrás de 'firme', quando 0,025 <= q < 0,05; não é quarta chave",
        "no_limite": "só no selo, para a zona cinzenta",
        "lista": "'a lista tem (não tem) mais achados do que a sorte produz' (p do excesso < 0,05)",
        "nome_proprio": "'acima da linha da sorte' (ranking_gaps) não disputa a palavra",
        "declaracao": "sessao_14_09/declaracoes_novas.json, chave vocabulario_sorte",
    },
    "ressalva_sem_desconto": {
        "decisao": "resposta b do dono, 14/09 (noite): a aba fica mais afirmativa",
        "texto": "elenco valioso tende a ter isso; o estudo não separa as duas coisas",
        "onde": "nas conclusões que sobem por esta régua (ELE-03, FIS-04, J17, J19, A2, M8) e nas outras em que o número anda com o valor do elenco (ORI-01, J15, A1)",
        "nunca": "virar teto de selo nem desconto (voltaria o dinheiro por outra porta)",
        "medida": "etapa_2.andam_com_o_valor (declaracoes_novas.andam_com_o_valor); ainda não gravada: onde não há medida, a frase sai sem número",
    },
    "regime_comum": {
        "o_que_e": "as conclusões de diferença entre grupos têm critérios com PAPEL e as linhas {selo, exige} saem de uma função só (sp6_maquina.ordem_comum), sem remendo conclusão por conclusão",
        "papeis": {"declarada": "1. comparação escrita antes de olhar (constante ou campo)", "p": "p bruto < 0,05 na comparação do título", "zona": "p < 0,10", "outra": "p < 0,05 noutra comparação da mesma linha",
                   "q": "2. firme", "q_folga": "firme com folga (q < 0,025)", "conf": "3. conferência testável (cada critério; todas têm de passar)", "ha_conf": "constante: há conferência testável",
                   "uma_conf": "constante: há uma conferência testável só", "lista": "4. lista acima da sorte", "rod": "5. físico: p_rod < 0,05"},
        "linhas": "zona: sem_sinal {p:F, zona:F}, sem_sinal {p:F, zona:T, outra:F}, fraco {p:F, zona:T, outra:T} · físico: fraco {p:T, rod:F} · escolhida depois: moderado {declarada:F, p:T, lista:T}, fraco {declarada:F, p:T, lista:F} (sem lista: fraco {declarada:F, p:T}) · declarada: forte {…, q:T, ha_conf:T, toda conf:T, q_folga:T}, forte {…, q:T, ha_conf:T, toda conf:T, uma_conf:F}, moderado {…, q:T}, moderado {…, q:F, lista:T}, fraco {…, q:F, lista:F} (sem lista: fraco {…, q:F}); '…' = declarada:T, p:T e, no físico, rod:T",
        "regimes_proprios": "repetição do atleta (FIS-07, M6, M7), contas da mesma pergunta (ELE-06, J8, J9), não dá para afirmar (DIN-06, J12, A3, M1, M3), sem sinal de uma ou várias medidas (ORI-02, DIN-04, DIN-05, ELE-04, ELE-05, FIS-05, FIS-09, J10, J11, J14, J18, A5, A6, M2), lista inteira (FIS-04), contagem com corte declarado (DIN-02): campo 'regime' de cada conclusão",
    },
    "conclusoes_partidas_ou_relidas": {
        "M4_M8": "resposta d do dono: M4 = zaga e lateral (fraco); o ataque vira a M8 (moderado); família e comparação declaradas antes, divisão do título depois de olhar (declaracoes_novas.conclusao_ataque_por_clube)",
        "A1": "decisão do coordenador: família dos 2 eixos da tipologia, escolhida depois de olhar (declaracoes_novas.familia_A1): fraco",
        "DIN04_DIN05": "decisão do coordenador: lidas por jogador (ponderado_por_jogador.particao), sem sinal, com a fatia em euros descrita (declaracoes_novas.din04_din05_por_jogador)",
        "porta_A": "resposta c do dono: só leitura, nome 'firme e reaparece por outro caminho'; a nota da etapa 13 não muda (ESPECIFICACAO 6.5)",
    },
    "regras_de_frase": [
        "associação não é causa: nada de 'faz subir', 'evita cair', 'contrate X para'",
        "'nunca' e 'sempre' só com zero exceção verificada no dado; uma exceção vira 'quase nunca' com o nome",
        "o que a conferência derrubou não volta (PSV-99 do top-5, 'ROTA não replica', 'TERRITÓRIO ficou mais forte', 'a tipologia caiu no teste cego')",
        "valor de mercado nunca é 'gasto', 'gastar', 'custa' nem 'orçamento'",
        "'descontado o dinheiro', 'entre elencos (ou times) de valor parecido' e 'não se viu o mesmo clube repetir o número' não entram como critério nem como motivo de selo (15/09); a relação com o valor do elenco só como ressalva sem desconto",
        "vocabulário único de sorte: firme / pode ser sorte / sem diferença clara; 'por pouco' só atrás de firme; 'no limite' só no selo; nunca 'dificilmente é sorte'",
        "sem_sinal escreve 'não se viu', nunca 'não separa' ou 'não existe'",
        "q de BH não se traduz como 'chance de acaso'; traduzir como 'contando os N testes, é firme' ou 'contando os N testes, já não dá para descartar a sorte'",
        "só p bilateral chega ao leitor",
        "2026 nunca conta como repetição nem entra em média",
        "associação nunca vira receita",
        "mecanismo não medido só como possibilidade ('pode')",
        "ordem nunca testada não entra ('o mais firme', 'o único que passa em tudo', 'o que mais separa', 'um dos três sinais fortes' quando dois são o mesmo sinal)",
        "frase que junta universos diferentes diz cada universo",
        "frase que depende dos nomes da etapa 14 sai do gerador novo ou não sai",
        "tamanho detectável e correlação em número só no rodapé; na frase, em palavras",
        "ausência só com 'não se viu' quando p >= 0,05",
        "período sempre com os anos ({periodo_antigo}, {periodo_recente}), nunca 'período antigo' sozinho",
        "molde sem número digitado: todo número vem de uma lacuna (as únicas exceções são as unidades 'de cada 100', 'em 100' e 'intervalo de 95%')",
    ],
    "rotulos_permitidos": SELO_ORD,
    "sem_sexto_rotulo": "contagem sem teste próprio vira descrição da conclusão de onde herda o selo (ex.: euros → DIN-01); 'descritivo', 'provisório' e 'não se aplica' não são selos",
    "regra_do_excesso": {
        "decisao": "dono, 14/09/2026: desempate MODERADO x FRACO = 'olhar a lista inteira'",
        "familia": "a família DECLARADA de dados/prototipo_indicadores.json da linha (tecnico_col, elenco, fisico_col_elenco, fisico_col_setor, tecnico_ind) ou a família declarada da análise (medidas da nota por setor, contadas por clube)",
        "comparacao": "a da conclusão (SM, SC; e CR, SR, CM para comparações escolhidas depois)",
        "contagem_observada": "número de linhas da família com p bruto < 0,05 na comparação",
        "nulo": "rótulos sobe/meio/cai permutados DENTRO de cada ano; o clube-temporada leva todas as colunas; recontagem em cada sorteio nos dois níveis (bruto e, nas famílias físicas e por clube, rod) com os mesmos rótulos; resíduo do rodízio calculado uma vez nos dados reais",
        "sorteios": 10000,
        "semente": "default_rng([SEMENTE, 3, i]) com i = 5 × índice da família + índice da comparação (declaracoes_novas.excesso_por_familia); por clube, default_rng([SEMENTE, 17, i]) com i = índice do setor (o [SEMENTE, 13, id] já é o gerador de cada atleta na etapa 13: não pode ser reusado)",
        "p_excesso": "(1 + sorteios com contagem >= observada) / (sorteios + 1)",
        "corte": "estrito: p_excesso < 0,05",
        "nivel": "contagem BRUTA decide; o nível rod é a 5ª pergunta só na FIS-04 (a conclusão é sobre a lista) e fica descrito nas outras",
        "gravar": "etapa_3.por_familia[f].excesso[comparacao][nivel] = {observado, nulo_mediana, nulo_p95, p_excesso, erro_monte_carlo, sorteios, semente, lista}; sobecai_corrigido_por_clube.<setor>.excesso.SC[nivel] = idem",
        "medido_15_09": "ver CONCLUSOES.md, rodapé da régua (dado novo prototipo_novo.json, sementes declaradas); valores de referência para conferir o gerador, não para a tela",
        "fronteira_elenco": "SM bruto 0,044 a 0,052 em 12 sementes em 14/09; a declarada [7,3,5] dá 0,0502 no dado novo: não se afirma excesso; conclusão do elenco não fica moderada por essa conta",
    },
    "faixa_de_pontos": {"campo": "vale_pela_faixa_de_pontos em cada conclusão", "regra": "só entra quando medido; sempre provisório até dados/pontos.json ser regerado no item 6 e fechado; nunca promove o selo", "de_onde_a_tela_le": "PONTOS.conclusoes (gerado por gerar_pontos.py)"},
    "comparacao_escolhida_depois_de_olhar": {
        "decisao": "dono, 14/09/2026 (decisão 1); sem o 'E sobreviver ao desconto do dinheiro' desde 15/09",
        "regra": "comparação, índice ou lista escolhida DEPOIS de ver os números (toda chave declarada_depois_de_olhar=true em declaracoes_novas; toda comparação CR, SR, CM; a família da A1; a divisão do título da M4/M8 não, porque família e comparação foram declaradas antes) não conta no BH; pode ser MODERADA só se a lista dela tiver mais achados que a sorte (p_excesso < 0,05, contagem bruta, na família declarada e na comparação escolhida); senão teto FRACO; nunca FORTE; sem lista de onde a comparação saia, teto FRACO",
        "selo_da_conclusao": "o da comparação do título; o título é o que a conclusão já tinha (a declarada antes ou a da pergunta do dono) e não se troca para a comparação que passa depois de ver os números; a outra comparação da mesma medida fica descrita ao lado",
        "excecao": "régua escolhida depois que só deixa a conta mais dura (posto por setor na FIS-07) não rebaixa, se a régua declarada antes der o mesmo selo",
        "efeito_por_conclusao": {
            "J5": "moderado de 2022 a 2025 (lista tecnico_col CR 13 contra 1, p 0,0024); 'em 2018-2021 não se repetiu'",
            "J5_zagueiros": "fraco (lista tecnico_ind CR 8 contra 5, p 0,19)",
            "J17": "a comparação do título é a SC declarada (moderado pela resposta a do dono: firme por pouco com uma conferência só); a CM (lista elenco CM 5 contra 0, p 0,0067) fica descrita ao lado",
            "DIN-03": "fraco (cai x meio sem lista)",
            "A1": "fraco (família dos 2 eixos escolhida depois, sem lista)",
            "A4": "fraco (comparação entre períodos sem lista)",
            "FIS-01": "fraco (índice sem lista; e não continua só com o rodízio, 0,077)",
            "J16": "fraco (linha escolhida depois, sem lista)",
            "ELE-06": "não sobe (sem lista); sem sinal pela regra das contas da mesma pergunta",
            "ELE-07": "fraco (2 medidas não formam lista)",
            "ORI-01": "fraco (sem lista)",
            "M6": "fraco (1 achado em 10 métricas)",
            "M7": "fraco (comparação físico x técnico montada depois, sem lista)",
            "M1": "não dá para afirmar (intervalo cruza zero; a regra não sobe)",
            "J7": "fraco pela declarada (SM); SR: lista tecnico_ind 10 contra 5, p 0,085 → teto fraco; CR zona cinzenta",
            "ELE-01": "moderado pela SC declarada; a parte CM também seria moderada (lista 0,0067) — sem efeito",
            "FIS-07": "exceção da régua mais dura — sem efeito",
        },
    },
    "repeticao_do_atleta": {
        "aplica_a": ["FIS-07", "M1", "M6", "M7"],
        "decisao": "dono, 14/09/2026 (decisão 3)",
        "medida": "Spearman do posto do mesmo atleta em t e t+1, nas 10 métricas declaradas da etapa 11, na régua declarada, ano <= 2025, chave do atleta nome + data de nascimento",
        "forte_se": "o teste de cada par de anos (Spearman de cada métrica, H0 rho = 0) dá p < 0,05 em todas as métricas e pares (p_max < 0,05), na régua do setor E na régua declarada antes (posto no ano)",
        "moderado_se": "p < 0,05 em algum par e não em todos",
        "tamanho": "mediana, ic95 e o corte de 0,5 descrevem o tamanho; não decidem",
        "diferenca_entre_grupos": "mudou x ficou e físico x técnico são 'qual é maior': nao_da_para_afirmar se o ic95 da diferença cruza zero; se não cruza, régua comum e regra da comparação escolhida depois (M7)",
    },
    "selo_calculado": {"forma_do_criterio": dict(MQ.FORMA_DO_CRITERIO, papel="só na régua comum: declarada | p | zona | outra | q | q_folga | conf | ha_conf | uma_conf | lista | rod (regua.regime_comum.papeis)"),
                       "leitura_da_regra": MQ.LEITURA_DA_REGRA,
                       "campo_da_conclusao": "conclusoes[].regra_maquina = {ordem: [{selo, exige: {id_do_criterio: passou}}], selo_padrao}; conclusoes[].regime; conclusoes[].entradas_da_regua = {regime, papeis: {papel: [ids]}, declarada_constante}",
                       "regra_do_selo": "conclusoes[].regra_do_selo continua como texto para leitura; quem decide é regra_maquina"},
    "selo_documento_e_tela": "o selo do CONCLUSOES.md e o forca_esperada_hoje saem da medida conferida da rodada (script nomeado) contra o dado novo de 15/09. A tela só mostra a conclusão quando o gerador gravar todo critério com decide=true; até lá ela fica fora da tela e fora das cinco. Não existe selo provisório nem rótulo de espera.",
}
