# Tema 3: jogo e padrões (J)
from sp6_base import *

C = []

def rep_clube(ind, valor, passou):
    return K("repetição: o mesmo clube no ano seguinte", f"etapa_6.rho.{ind}.p", valor, passou)

C.append(conc(
    id="J1", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe finaliza de mais perto do gol",
    frase="{m_sobe} metros em média, contra {m_meio} no meio da tabela e {m_cai} em quem cai, de {ano_ini} a {ano_fim}; {sobe_perto} dos {n_prom} que subiram chutaram de mais perto que a metade da liga no seu ano. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo testados, e o número do primeiro turno acompanha os pontos do segundo mesmo entre times com pontos parecidos (contando os {n_testados_e7} números do primeiro turno, isso pode ser sorte).",
    numero="Pegando um time que subiu e um do meio, o que subiu chuta de mais perto em {auc_100}. Em {periodo_antigo} foi para o mesmo lado, sem diferença clara (o acaso produziria aquilo em {p_antigo_chance}); é essa conferência que falta para o selo forte.",
    ressalva="Não quer dizer 'mande chutar de perto', nem 'trabalhe a chegada à área e o time sobe'. Quem toca mais na área chuta de mais perto, mas, comparando times com as mesmas entradas e toques na área, quem sobe continua chutando de mais perto; o estudo não mediu de onde vem a diferença.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_meio"),
        "m_cai": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_cai"),
        "sobe_perto": N("inteiro", "etapa_2.por_clube", "promovidos com dist_remate abaixo da mediana do próprio ano"),
        "auc_100": D("pares_em_100", "1 - etapa_2.linhas[indicador=dist_remate].auc_SM (sinal -1)", ["etapa_2.linhas[indicador=dist_remate].auc_SM"]),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].p_SM"),
    },
    val={"sobe_perto": "14", "auc_100": "81 de cada 100 pares"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=dist_remate].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=dist_remate].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=dist_remate].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=dist_remate].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=dist_remate].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: chuta de mais perto)", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "forte_se": "q_SM < 0,05 E as duas conferências testáveis passam (1º turno com p parcial < 0,05 no lado declarado; 2018-2021 com p < 0,05 no mesmo lado)",
           "moderado_se": "q_SM < 0,05 E alguma conferência falha (as conferências discordam → o mais fraco)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno passa a valer pelo p parcial (não pelo q dos 28)",
           "proibido": ["'o único sinal de jogo que passa em tudo'", "'o mais firme'", "'é consequência de chegar bem à área'", "'o sinal mais sólido'", "'continua entre elencos de valor parecido'", "'o mesmo clube tende a repetir'"]},
    p=P("etapa_2.linhas[indicador=dist_remate].p_bruto_SM", 3e-05), ceticos=True, rev="reconferência 14/09: universo e critérios; a falha de 2018-2021 está gravada no teste cego",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'o mesmo clube tende a repetir'; firme (q 0,0008); conferências: 1º turno passa pelo p (0,0022, lado declarado) e 2018-2021 falha (0,079): discordam, vale a mais fraca",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J2", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe acerta mais chutes no gol",
    frase="{m_sobe}% dos chutes no alvo, contra {m_meio}% no meio da tabela e {m_cai}% em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo, e o número do primeiro turno acompanha os pontos do segundo (contando os {n_testados_e7} números do primeiro turno, isso pode ser sorte).",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}. Em {periodo_antigo} não se viu diferença contra o meio (o acaso produziria aquilo em {p_antigo_chance}); quem subiu ainda ficou acima de quem caiu (em {p_antigo_sc_chance}).",
    ressalva="Não quer dizer que pontaria é traço do elenco que se contrata: pode ser forma da temporada, e a conferência em {periodo_antigo} contra o meio falhou.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_meio"),
        "m_cai": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_cai"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM"),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SM"),
        "p_antigo_sc_chance": G("chance_em_1000", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SC"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=remates_baliza_pct].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=remates_baliza_pct].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=remates_baliza_pct].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=remates_baliza_pct].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 E alguma conferência testável falha (aqui 2018-2021 contra o meio)",
           "regra_de_desempate": "conferências que discordam: o selo mais fraco",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno e 2018-2021 passam a decidir",
           "proibido": ["'o 1º turno ajuda a prever o 2º' sem a ressalva dos 28", "'em 2018-2021 o sinal apareceu fraco demais' (p 0,25: 'não se viu')", "'não se viu o mesmo clube repetir a pontaria'"]},
    p=P("etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM", 0.00013), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números (tudo reproduziu); '2018-2021 apareceu fraco demais' virou 'não se viu diferença contra o meio', com quem sobe acima de quem cai",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'não se viu o mesmo clube repetir a pontaria'; firme (q 0,002); 1º turno passa (p 0,030) e 2018-2021 falha (0,25): o 1º turno e 2018-2021 passam a decidir. A ressalva não cita mais a etapa 10: `remates_baliza_pct` saiu da lista de lá (é porta A no catálogo novo)",
    faixa_keep=True,
    rodape_ops=[("replace", "2018-2021 d 0,35, p 0,25", "2018-2021 sobe x meio d 0,35, p 0,25, q 0,33 nos 31; sobe x cai p 0,0009 · reconferido pelo cético de 14/09")],
))

C.append(conc(
    id="J3", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe faz menos faltas",
    frase="{m_sobe} faltas por jogo, contra {m_meio} no meio da tabela, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo, mas não se viu o primeiro turno prever o segundo, e em {periodo_antigo} foi para o mesmo lado sem força para confirmar.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}. Não se viu que seja por ter mais a bola: posse e faltas quase não andam juntas, e comparando times com a mesma posse o acaso produziria a diferença em {p_desc_posse_chance}.",
    ressalva="Não quer dizer 'faça menos falta para subir', nem 'tenha a bola para fazer menos falta'. O estudo não sabe por que quem sobe faz menos falta.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=faltas].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=faltas].m_meio"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=faltas].p_bruto_SM"),
        "p_desc_posse_chance": N("chance_em_1000", "etapa_2.linhas[].p_SM_descontada_posse", "faltas"),
    },
    val={"p_desc_posse_chance": "3 de cada 1.000 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=faltas].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=faltas].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=faltas].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=faltas].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=faltas].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=faltas].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: menos faltas)", "teste_cego_2018_2021.json porta.velho[ind=faltas].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 E as conferências testáveis falham (1º turno p 0,90; 2018-2021 p 0,12)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno e 2018-2021 passam a decidir",
           "proibido": ["'time que tem a bola faz menos falta'", "correlação na frase de reunião", "'resiste ao dinheiro'"]},
    p=P("etapa_2.linhas[indicador=faltas].p_bruto_SM", 0.00169), ceticos=True, rev="reconferência 14/09: correlação posse × faltas saiu da frase (fica no rodapé)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'resiste ao dinheiro' e 'não se viu o mesmo clube repetir'; firme (q 0,017); o 1º turno (0,90) e 2018-2021 (0,12) falham e passam a decidir",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J4", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe ganha mais duelos — e isso também apareceu em {periodo_antigo}",
    frase="Na posição no ranking de duelos ganhos do ano, de {ano_ini} a {ano_fim}, quem sobe fica bem acima do meio (em porcentagem a diferença é pequena: {m_sobe} contra {m_meio}), e em {periodo_antigo} apareceu com força. É um sinal {selo}: não resiste à conta dos {n_familia_tecnico_col} números de jogo, mas a lista inteira do técnico do time tem mais achados do que a sorte produz.",
    numero="Em {periodo_antigo}, o acaso produziria a diferença em {p_antigo_chance}. Não se viu o número do primeiro turno acompanhar os pontos do segundo (o acaso daria aquilo em {p_turno_chance}).",
    ressalva="Não quer dizer que duelo ganho faz subir. Em {periodo_antigo} não há valor de mercado: lá o resultado é cru. Quem cai não se distinguiu dos outros em duelo em nenhum dos dois períodos.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=duelos_pct].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=duelos_pct].m_meio"),
        "p_antigo_chance": G("chance_em_1000", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].p_SM"),
        "p_turno_chance": G("chance_em_100", "etapa_2.linhas[indicador=duelos_pct].p_1T_2T"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=duelos_pct].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=duelos_pct].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=duelos_pct].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=duelos_pct].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=duelos_pct].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista inteira do técnico do time acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso < 0,05",
           "fraco_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E lista no nível da sorte",
           "nota": "a conferência de 2018-2021 que passa não substitui a falha na conta dos testes (as conferências só decidem entre forte e moderado)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte"},
    p=P("etapa_2.linhas[indicador=duelos_pct].p_bruto_SM", 0.0208), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números; acrescentado que o primeiro turno não acompanha o segundo (p 0,90, gravado)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre times de valor de elenco parecido' e 'não se viu o mesmo clube repetir'; q 0,13 e a lista do técnico do time tem mais achados que a sorte (7 contra 1, p 0,037)",
    faixa_keep=True,
    rodape_ops=[("replace", "ρ de repetição 0,05", "1º → 2º turno parcial 0,015 (p 0,90, `etapa_2.linhas[duelos_pct].p_1T_2T`) · reconferido pelo cético de 14/09 (lista 7 contra 1, p 0,037 noutra semente)")],
))

C.append(conc(
    id="J5", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=False,
    titulo="Quem cai ganhou uma parte menor dos duelos aéreos de {ano_ini} a {ano_fim}; em {periodo_antigo} não se repetiu",
    frase="De {ano_ini} a {ano_fim}, {cai_metade_baixo} dos {n_cai} que caíram ficaram na metade de baixo do ano em duelo aéreo ganho, e {cai_5_piores} entre os {k_extremos} piores. Contra todos os outros times, o acaso produziria a diferença em {p_cr_chance}. É um sinal {selo} de {ano_ini} a {ano_fim}: a comparação quem cai contra o resto foi escolhida depois da pergunta do dono, mas a lista dos {n_familia_tecnico_col} números de jogo nessa comparação tem mais achados do que a sorte, que é o que a regra do dono pede para uma comparação escolhida depois.",
    numero="Em {periodo_antigo} não se repetiu: só {cai_metade_baixo_antigo} dos {n_cai_antigo} que caíram estavam na metade de baixo, e {n_cai_melhores_antigo} deles entre os {k_extremos} melhores do ano ({exemplos_antigo}).",
    ressalva="Não quer dizer que zagueiro bom no alto evita queda, nem que o duelo aéreo passou a pesar mais de um período para o outro: a diferença entre os dois períodos pode ser sorte ({p_diferenca_chance}). Não se viu o primeiro turno prever o segundo. Na comparação declarada antes, quem sobe contra quem cai, a diferença aparece ({p_sc_chance}). Nos zagueiros (atletas com {corte_min_ind}+ minutos) aparece o mesmo lado, mas é um sinal {selo_zagueiros}: a lista do técnico individual nessa comparação não tem mais achados que a sorte, e são poucos zagueiros por time.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "cai_metade_baixo": N("inteiro", "etapa_2.linhas[].cai_metade_baixo", "duelos_aereos_pct"),
        "cai_5_piores": N("inteiro", "etapa_2.linhas[].cai_entre_5_piores", "duelos_aereos_pct"),
        "k_extremos": D("inteiro", "k_extremos declarado (5)", []),
        "p_cr_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CR", "duelos_aereos_pct"),
        "cai_metade_baixo_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: cai_metade_baixo"),
        "n_cai_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: n_cai"),
        "n_cai_melhores_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: len(cai_entre_5_melhores)"),
        "exemplos_antigo": N("texto", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: cai_entre_5_melhores, 'CLUBE ANO, Nº', vírgulas e 'e'"),
        "p_diferenca_chance": N("chance_em_100", "etapa_2.linhas[].diferenca_entre_periodos_CR", "duelos_aereos_pct: p"),
        "p_sc_chance": G("chance_em_100", "etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_SC"),
        "selo_zagueiros": D("selo_minusculo", "regra do selo aplicada a ti_zaga_duelos_aereos_ganhos, comparação CR, lista tecnico_ind (p_excesso CR bruto)", ["etapa_2.linhas[indicador=ti_zaga_duelos_aereos_ganhos]", "etapa_3.por_familia.tecnico_ind.excesso.CR.bruto.p_excesso"]),
    },
    val={"cai_metade_baixo": "14", "cai_5_piores": "8", "k_extremos": "5", "p_cr_chance": "3 de cada 1.000 tentativas",
         "cai_metade_baixo_antigo": "9", "n_cai_antigo": "16", "n_cai_melhores_antigo": "2", "exemplos_antigo": "Remo 2021, 1º, e Criciúma 2019, 3º", "p_diferenca_chance": "11 de cada 100 tentativas",
         "selo_zagueiros": "fraco"},
    crit=[
        CONST("1. comparação do título declarada antes", False, papel="declarada", txt="não: quem cai contra o resto foi escolhida depois da pergunta do dono"),
        KM("p bruto < 0,05 (quem cai contra o resto)", "etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_CR", papel="p", op="<", lim=0.05, v=0.0034),
        KM("4. lista da comparação acima da sorte (técnico do time, quem cai contra o resto, p do excesso < 0,05)", "etapa_3.por_familia.tecnico_col.excesso.CR.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("conferência (descrição, não decide numa comparação escolhida depois): o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=duelos_aereos_pct].p_parcial", op="<", lim=0.05, decide=False),
        KM("conferência (descrição): 2018-2021, quem cai contra o resto, p < 0,05", "etapa_2.linhas[indicador=duelos_aereos_pct].antigo_CR", op="<", lim=0.05, sub="p", v=0.52, decide=False),
        KM("comparação declarada, quem sobe contra quem cai (descrição): firme, q < 0,05", "etapa_2.linhas[indicador=duelos_aereos_pct].q_SC", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, moderado só com a lista DELA acima da sorte; nunca forte",
           "comparacao_da_frase": "CR, escolhida depois da pergunta do dono",
           "moderado_se": "p_bruto_CR < 0,05 E etapa_3.por_familia.tecnico_col.excesso.CR.bruto.p_excesso < 0,05",
           "fraco_se": "p_bruto_CR < 0,05 E p_excesso CR bruto >= 0,05",
           "forte": "impossível: comparação escolhida depois tem teto moderado; q_CR não conta como passar na conta dos testes",
           "zagueiros": "ti_zaga_duelos_aereos_ganhos CR: p 0,0014, lista tecnico_ind CR 8 contra 5 (p 0,19) → fraco",
           "saiu_em_15_09": "o 'E sobreviver ao desconto do dinheiro' da regra da comparação escolhida depois, e o mesmo clube no ano seguinte",
           "proibido": ["'não antes' como diferença entre períodos", "usar q_CR para o selo", "'perdeu mais duelos aéreos' (a medida é porcentagem ganha)", "'continua entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_CR", 0.0034), ceticos=True,
    rev="reconferência 14/09 (decisão 1 do dono): fraco → moderado de 2022 a 2025, com 'em 2018-2021 não se repetiu' escrito; título pela porcentagem ganha ('ganhou uma parte menor'), não 'perdeu mais'",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Da regra da comparação escolhida depois sai o 'E sobreviver ao desconto do dinheiro'; fica a lista dela (13 contra 1, p 0,0024). Saem a frase do clube no ano seguinte e 'na declarada some entre elencos de valor parecido': quem sobe contra quem cai é firme por pouco (q 0,043), só descrição",
    faixa_keep=True,
    rodape_ops=[("replace", "selo: FRACO na rodada de conserto (antes MODERADO) pela regra da comparação escolhida depois de olhar", "**selo: MODERADO de 2022 a 2025 na reconferência de 14/09 (decisão 1 do dono)**: comparação escolhida depois, com a lista dela acima da sorte (13 contra 1, p 0,002); na rodada de conserto tinha ficado FRACO"),
                ("replace", "cai x resto (escolhida depois, só descrição):", "cai x resto (escolhida depois da pergunta; é a comparação do título e decide o selo pela decisão 1 do dono):"),
                ("replace", "13 achados contra 1 do sorteio (p do excesso 0,002), que não conta para o selo", "13 achados contra 1 do sorteio (p do excesso 0,002), que é a condição da decisão 1 para chegar a moderado (o q da família montada depois não conta como passar na conta dos testes)"),
                ("append", " · contagens da frase (`r4_saida.json`): 14 de 16 rebaixados na metade de baixo e 8 entre os 5 piores do ano")],
))

C.append(conc(
    id="J6", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Os meias de quem sobe dão mais passes-chave",
    frase="{m_sobe} passe-chave por jogo por meia (atletas com {corte_min_ind}+ minutos), contra {m_meio} no meio da tabela e em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_ind} indicadores individuais, mas não houve como conferir por outro caminho: não há técnico individual em {periodo_antigo} nem jogo a jogo individual.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que contratar meia de passe-chave faz subir: o número pode vir de quem estava em campo naquele ano, e passe-chave depende de alguém finalizar.",
    universo=UNIVERSOS["tec_ind"],
    lac={
        "m_sobe": G("dec2", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].m_sobe"),
        "m_meio": G("dec2", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].m_meio"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 92 indicadores individuais (q < 0,05)", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: técnico individual não processado em 2018-2021 e sem jogo a jogo individual"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do técnico individual, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte", "proibido": ["'resiste ao dinheiro'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM", 0.00026), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números (recalculado do serieb_tecnico.csv); média em duas casas",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'resiste ao dinheiro' e 'não se viu o mesmo clube repetir'; motivo: firme (q 0,020) sem conferência testável",
    faixa_keep=True,
    rodape_ops=[("replace", "ρ de repetição 0,20", "reconferido pelo cético de 14/09 a partir de `serieb_tecnico.csv`")],
))

C.append(conc(
    id="J7", tema="jogo_e_padroes", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="Os meias de quem sobe ganham mais duelos defensivos; quem cai não se mostrou bem pior",
    frase="Quem mais destoa é quem sobe, para cima: {sobe_metade_cima} dos {n_prom} que subiram ficaram na metade de cima do ano em duelo defensivo ganho pelos meias, de {ano_ini} a {ano_fim} ({med_sobe}% contra {med_meio}% no meio da tabela). É um sinal {selo}: entre os {n_familia_tecnico_ind} números individuais testados, o número dos que separam é o que a sorte produz.",
    numero="Olhando só este número, o acaso produziria a diferença contra o meio em {p_chance}. Quem cai não se mostrou bem pior: contra o meio da tabela não se viu diferença, e contra o resto não há diferença clara (fica na zona cinzenta).",
    ressalva="Não quer dizer que meia que ganha duelo defensivo faz subir. Não há como conferir em {periodo_antigo}, nem com jogo a jogo individual.",
    universo=UNIVERSOS["tec_ind"],
    lac={
        "sobe_metade_cima": N("inteiro", "etapa_2.linhas[].sobe_metade_cima", "ti_meio_duelos_defensivos_ganhos"),
        "med_sobe": N("dec1", "etapa_2.linhas[].mediana_sobe", "ti_meio_duelos_defensivos_ganhos (valor cru)"),
        "med_meio": N("dec1", "etapa_2.linhas[].mediana_meio", "ti_meio_duelos_defensivos_ganhos (valor cru)"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM"),
    },
    val={"sobe_metade_cima": "13", "med_sobe": "59,3", "med_meio": "57,2"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 92 indicadores individuais (q < 0,05)", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: técnico individual não processado em 2018-2021 e sem jogo a jogo individual"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista inteira do técnico individual acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem sobe contra o resto (escolhida depois; descrição): lista acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SR.bruto.p_excesso", op="<", lim=0.05, decide=False),
        KM("quem cai contra o resto (escolhida depois; descrição): p < 0,05", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_CR", op="<", lim=0.05, v=0.093, txt="0,093: zona cinzenta", decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E a lista do técnico individual SM no nível da sorte",
           "parte_depois_de_olhar": "SR: lista 10 contra 5, p 0,085 → teto fraco; CR: zona cinzenta; CM p 0,29 → 'não se viu'",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; a citação da etapa 10 (a medida saiu da lista fixa de lá)"},
    p=P("etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM", 0.01208), ceticos=True,
    rev="reconferência 14/09: regra do dono reaplicada à parte 'quem sobe contra o resto' (lista 0,082): segue fraco; mediana crua no molde",
    rev15="rodada sem dinheiro (15/09): segue FRACO (q 0,22; lista 0,082). Saem 'continua entre times de valor de elenco parecido' e 'não se viu o clube repetir'; a ressalva não cita mais a etapa 10, porque `ti_meio_duelos_defensivos_ganhos` saiu da lista fixa de lá",
    faixa_keep=True, rodape_ops=[("append", " · contagem da frase (`r4_saida.json`): 13 de 16 promovidos na metade de cima do ano · regra do dono de 14/09 reaplicada: quem sobe contra o resto é comparação escolhida depois e a lista dela não passa da sorte (0,082), então não sobe de fraco")],
))

C.append(conc(
    id="J13", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe cede chutes com menos chance de gol",
    frase="{xgr_sobe} de gol esperado por chute cedido, contra {xgr_meio} no meio da tabela e {xgr_cai} em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: contando os {n_familia_tecnico_col} números de jogo testados já não dá para descartar a sorte, mas a lista inteira tem mais achados do que a sorte produz; em {periodo_antigo} foi para o mesmo lado sem força para confirmar.",
    numero="Olhando só o gol esperado por chute, o acaso produziria a diferença em {p_chance}; em {periodo_antigo}, em {p_antigo_chance}. No total de chances cedidas, quem sobe cede bem menos que quem cai ({xg_sobe} contra {xg_cai} gol esperado por jogo), e isso é firme contando os {n_familia_tecnico_col} números; contra o meio, o total cedido pode ser sorte olhando os {n_familia_tecnico_col}, mas a mesma lista tem mais achados do que a sorte.",
    ressalva="Não quer dizer 'defenda longe da área e você sobe': gol esperado por chute mede a qualidade da chance (de onde, de cabeça, sob pressão), e ceder pouco pode vir de ter mais a bola ou de estar ganhando. Em {periodo_antigo} não se viu diferença entre quem caiu e o resto da liga no gol esperado cedido.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "xgr_sobe": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_sobe"),
        "xgr_meio": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_meio"),
        "xgr_cai": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_cai"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM"),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].p_SM"),
        "xg_sobe": G("dec2", "etapa_2.linhas[indicador=xg_contra].m_sobe"),
        "xg_cai": G("dec2", "etapa_2.linhas[indicador=xg_contra].m_cai"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=xg_por_remate_contra].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=xg_por_remate_contra].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: cede menos)", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: 2018-2021 (sem versão por jogo, o 1º turno não é testável)"),
        CONST("há uma conferência testável só", True, papel="uma_conf", txt="sim: só 2018-2021"),
        KM("4. lista inteira do técnico do time acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso < 0,05",
           "total_cedido": "xg_contra, só descrição: quem sobe contra quem cai q_SC 0,0017 (firme); quem sobe contra o meio p 0,049, q 0,21 (pode ser sorte), com a lista do técnico do time acima da sorte",
           "saiu_em_15_09": "o desconto do dinheiro, o mesmo clube no ano seguinte e os selos do total cedido montados com o desconto",
           "proibido": ["'deixa o adversário chutar de onde é mais difícil'", "'em 2018-2021 quem caiu cedia o mesmo'", "'não é traço de clube' como fato", "'entre quem caiu e o meio' para o número de quem cai contra o resto", "'some quando se comparam elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM", 0.01038), ceticos=True,
    rev="reconferência 14/09: o p de 2018-2021 já está gravado no teste cego (0,1134); 'entre quem caiu e o meio' virou 'o resto da liga' (p 0,68); frase do traço no molde da ELE-02",
    rev15="rodada sem dinheiro (15/09): segue MODERADO (q 0,080; lista do técnico do time 7 contra 1, p 0,037). Saem 'continua de pé entre times de elenco de valor parecido', 'não se viu o mesmo clube repetir' e os dois selos do total cedido que dependiam do desconto (o total contra o meio era fraco só pelo dinheiro); o total cedido fica descrito com o vocabulário da sorte",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J14", tema="jogo_e_padroes", etapa="etapa_2", selo="sem_sinal", declarada=True,
    titulo="Pressão alta, bola parada, escanteio e intensidade: não se viu quem sobe diferente do meio",
    frase="Nem em {periodo_recente} nem em {periodo_antigo} se viu quem sobe diferente do meio da tabela em pressão alta, bola parada, escanteio ou intensidade. Com {n_sobe} contra {n_meio} em cada período, {frase_tamanho}. Contra-ataque e cruzamento têm conclusão própria (J18), e a pressão alta contra quem cai também (J19).",
    numero="Na medida que ficou mais perto do limite, o acaso produziria a diferença em {menor_p_recente} em {periodo_recente} e em {menor_p_antigo} em {periodo_antigo}.",
    ressalva="Não quer dizer que pressão, bola parada ou escanteio não importam: com {n_sobe} times que subiram, uma diferença pequena não apareceria. E estilo anda com o valor do elenco: elenco mais valioso pressiona mais alto (J15).",
    tecnico="tamanho detectável {d_min}",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "menor_p_recente": D("chance_em_100", "min p_bruto_SM de ppda, bolas_paradas, cantos, intensidade", ["etapa_2.linhas"]),
        "menor_p_antigo": N("chance_em_100", "etapa_2.linhas[].antigo_SM", "min p de ppda, bolas_paradas, cantos, intensidade"),
        "d_min": G("dec2", "etapa_0.poder.d_minimo_16x48"),
    },
    val={"menor_p_recente": "25 de cada 100 tentativas", "menor_p_antigo": "19 de cada 100 tentativas"},
    crit=[
        K("as quatro, quem sobe contra o meio, p >= 0,10 em 2022-2025", "etapa_2.linhas", "menor 0,25", True),
        K("as quatro, quem sobe contra o meio, p >= 0,10 em 2018-2021", "etapa_2.linhas[].antigo_SM", "menor 0,19", True),
    ],
    regra={"lista_declarada": ["ppda", "bolas_paradas", "cantos", "intensidade"], "sem_sinal_se": "p_bruto_SM >= 0,10 nos dois períodos para as quatro",
           "proibido": ["'não adianta olhar'", "incluir posse (J15)", "'estilo não é de graça'", "citar contra-ataque e cruzamento (J18) ou a PPDA contra quem cai (J19) como parte desta"]},
    p=P("etapa_2.linhas[indicador=intensidade].p_bruto_SM", 0.24985), ceticos=True,
    rev="reconferência 14/09: a PPDA de quem sobe contra quem cai (p 0,0019) ganhou conclusão própria (J19); 2018-2021 das quatro colunas pedido ao gerador (antigo_SM)",
    faixa_keep=True,
    rodape_ops=[("replace", " · PPDA sobe x cai p 0,0019, q 0,009, descontado 0,83", " · a PPDA de quem sobe contra quem cai (p 0,0019) está na J19"),
                ("replace", "2018-2021: PPDA 0,85; bolas paradas 0,19; escanteios 0,20; intensidade 0,29", "2018-2021: PPDA 0,85; bolas paradas 0,19; escanteios 0,20; intensidade 0,29 (reconferido em `r13_varios.py`)")],
))

C.append(conc(
    id="J15", tema="jogo_e_padroes", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="A posse de quem sobe é maior, no limite do acaso",
    frase="{posse_sobe}% contra {posse_meio}% no meio da tabela, de {ano_ini} a {ano_fim}, no limite do acaso. É um sinal {selo}: contra o meio fica no limite, e contra quem cai a diferença aparece.",
    numero="Na Série B inteira, elenco mais valioso tem mais a bola e pressiona mais alto: as duas coisas andam com o valor do elenco.",
    ressalva="Não quer dizer que ter a bola faz subir: elenco valioso tende a ter mais a bola, e o estudo não separa as duas coisas.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "posse_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=posse].m_sobe"),
        "posse_meio": G("pct_inteiro", "etapa_2.linhas[indicador=posse].m_meio"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05 (quem sobe contra o meio)", "etapa_2.linhas[indicador=posse].p_bruto_SM", papel="p", op="<", lim=0.05, txt="0,056 (zona cinzenta)"),
        KM("zona cinzenta: p < 0,10", "etapa_2.linhas[indicador=posse].p_bruto_SM", papel="zona", op="<", lim=0.10),
        KM("sinal bruto em outra comparação da mesma linha (quem sobe contra quem cai), p < 0,05", "etapa_2.linhas[indicador=posse].p_bruto_SC", papel="outra", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=posse].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=posse].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=posse].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=posse].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=posse].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=posse].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): zona cinzenta com p < 0,05 em outra comparação da mesma linha → fraco",
           "fraco_se": "0,05 <= p_bruto_SM < 0,10 E p_bruto_SC < 0,05",
           "ressalva": "sem desconto e sem receita: 'elenco valioso tende a ter mais a bola; o estudo não separa as duas coisas'",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC) como critério; do título, 'mas anda com o valor do elenco' como desconto",
           "proibido": ["'tenha a bola'", "ρ na frase de reunião"]},
    p=P("etapa_2.linhas[indicador=posse].p_bruto_SM", 0.05612), ceticos=True, rev="reconferência 14/09: correlações com o valor no rodapé, não na frase",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o critério do desconto do dinheiro; decide a zona cinzenta de quem sobe contra o meio (0,056) com p 0,008 em quem sobe contra quem cai. Título sem o desconto; a relação com o valor fica como ressalva sem desconto",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J19", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe pressiona mais alto que quem cai",
    frase="De {ano_ini} a {ano_fim}, quem sobe deixou o adversário trocar {ppda_sobe} passes por ação defensiva, contra {ppda_cai} em quem cai (menos passes é pressão mais alta). É um sinal {selo}: na comparação declarada antes, quem sobe contra quem cai, contando os {n_familia_tecnico_col} números de jogo, {frase_q}; mas não se viu o primeiro turno prever o segundo, e em {periodo_antigo} não se viu diferença entre quem subiu e quem caiu (o acaso produziria aquilo em {p_antigo_sc_chance}).",
    numero="Olhando só este número, o acaso produziria a diferença em {p_sc_chance}. Contra o meio da tabela não se viu diferença (J14).",
    ressalva="Não quer dizer que pressionar alto faz subir, nem que evita cair. Elenco valioso tende a pressionar mais alto (J15); o estudo não separa as duas coisas.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "ppda_sobe": G("dec1", "etapa_2.linhas[indicador=ppda].m_sobe"),
        "ppda_cai": G("dec1", "etapa_2.linhas[indicador=ppda].m_cai"),
        "frase_q": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=ppda].q_SC"]),
        "p_sc_chance": G("chance_em_1000", "etapa_2.linhas[indicador=ppda].p_bruto_SC"),
        "p_antigo_sc_chance": N("chance_em_100", "etapa_2.linhas[].antigo_SC", "ppda: p"),
    },
    val={"frase_q": "é firme", "p_antigo_sc_chance": "87 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ppda].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=ppda].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ppda].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=ppda].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=ppda].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra quem cai, p < 0,05 no mesmo lado", "etapa_2.linhas[indicador=ppda].antigo_SC", papel="conf", op="<", lim=0.05, sub="p", v=0.87),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra quem cai, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SC < 0,05 E as conferências testáveis falham (1º turno p 0,31; 2018-2021 p 0,87)",
           "ressalva": "sem desconto e sem receita (resposta b do dono): 'elenco valioso tende a pressionar mais alto; o estudo não separa as duas coisas' — medido: ppda anda com o valor do elenco (ρ −0,55, `etapa_2.estilo_x_valor`)",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC 0,83) e o mesmo clube no ano seguinte; do título, '— mas isso some entre elencos de valor parecido'",
           "proibido": ["'pressione alto'", "'PPDA' sem traduzir na frase", "'some entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=ppda].p_bruto_SC", 0.00194), ceticos=False, nova_em="2026-09-14 (reconferência)",
    rev="nova na reconferência de 14/09: era um número sem selo no rodapé da J14 (PPDA sobe x cai p 0,0019, q 0,009, descontado 0,83)",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só pelo desconto do valor (0,83). Pela régua final: firme em quem sobe contra quem cai (q 0,0086); o 1º turno (0,31) e 2018-2021 (0,87) falham. Ressalva obrigatória sem desconto: elenco valioso tende a pressionar mais alto; o estudo não separa as duas coisas",
    faixa_texto="**Vale também pela faixa de pontos?** (provisório): na faixa baixa x média, PPDA p 0,029 (2022-25) e 0,88 em 2018-21 (lido da J14).",
    rodape_texto="nova na reconferência de 14/09 (era número sem selo no rodapé da J14), sem cético próprio · `ppda` média 9,83 / 10,15 / 11,11 passes do adversário por ação defensiva (menor = pressão mais alta) · sobe x cai d no posto, p 0,0019, q 0,0086 (31) (`etapa_2.linhas[ppda].{p_bruto_SC, q_SC}`, gravados) · sobe x meio p 0,60 (J14) · 1º → 2º turno parcial −0,12 (p 0,31) · 2018-2021 sobe x cai p 0,87, médias 9,4 / 9,6 / 9,4 (`r13_varios.py`) · valor do elenco x pressão, 80 temporadas: ρ 0,55 (J15), é o que a ressalva descreve, sem descontar · na conta de 14/09 o selo fraco vinha do desconto do valor (p 0,83), que saiu da régua em 15/09 · onde ver na aba: etapa 2",
))

C.append(conc(
    id="J8", tema="jogo_e_padroes", etapa="etapa_7", selo="fraco", declarada=True,
    titulo="Números de jogo acrescentam pouco à tabela do primeiro turno para prever o segundo",
    frase="De {ano_ini} a {ano_fim}, dos {n_testados_e7} números de jogo testados, {n_passam} acrescentam algo à tabela do primeiro turno mesmo entre times com pontos parecidos. É um sinal {selo}: contando os {n_testados_e7}, nenhum se sustenta sozinho, e a lista inteira não tem mais achados do que a sorte (num sorteio, o típico é {nulo_mediana}, {texto_p95}). Por uma conta que só olha os de lado certo, a lista passa do acaso por pouco; as duas contas discordam e vale a mais fraca.",
    numero="Os pontos do primeiro turno andam com os do segundo com força {rho_pts}, numa escala em que um é andar sempre junto e zero é não andar; o melhor número de jogo, {melhor_ind}, fica em {melhor_rho}. Nenhum ficou acima da tabela, mas a diferença é pequena demais para ordenar os dois.",
    ressalva="Não quer dizer que a tabela do primeiro turno é a melhor pista, nem que números de jogo não servem para prever. Os números de escalação não puderam entrar.",
    universo="{n_clube_temporadas} clube-temporadas da Série B de {ano_ini} a {ano_fim}, primeiro turno contra segundo turno do mesmo ano; {ano_parcial} fica fora de toda conta",
    lac={
        "n_passam": D("inteiro", "linhas de etapa_7 com p_parcial < 0,05 E sinal_certo", ["etapa_7.linhas"]),
        "nulo_mediana": N("inteiro", "etapa_7.excesso.sem_sinal.nulo_mediana"),
        "texto_p95": N("texto", "etapa_7.excesso.sem_sinal.nulo_p95", "'e até N em 95 de cada 100 vezes'"),
        "rho_pts": G("dec2", "etapa_7.referencia_pts1t_x_pts2t.rho"),
        "melhor_ind": D("texto", "linha de menor p_parcial com sinal_certo, pelo nome simples do glossário ('a distância média do chute')", ["etapa_7.linhas"]),
        "melhor_rho": D("dec2", "abs(rho_bruto) dessa linha", ["etapa_7.linhas"]),
    },
    val={"n_passam": "4", "nulo_mediana": "1", "texto_p95": "e até 5 em 95 de cada 100 vezes", "melhor_ind": "a distância média do chute", "melhor_rho": "0,44", "selo": "fraco"},
    crit=[
        K("algum número com p parcial < 0,05", "etapa_7.linhas", "4 de lado certo", True),
        K("conta dos 28 (q parcial < 0,05)", "etapa_7.linhas[].q_parcial", "menor q 0,062", False),
        K("lista inteira acima da sorte, sem olhar o lado (a conta da régua)", "etapa_7.excesso.sem_sinal.p_excesso", "4 contra 1, p 0,12", False),
        K("lista inteira acima da sorte, só de lado certo (descrição)", "etapa_7.excesso.sinal_certo.p_excesso", "4 contra 0, p 0,044", True, decide=False),
    ],
    regra={"fraco_se": "algum p_parcial < 0,05 E nenhum q_parcial < 0,05 E (etapa_7.excesso.sem_sinal.p_excesso >= 0,05 OU as duas contagens discordam)",
           "moderado_se": "algum q_parcial < 0,05 OU as duas contagens com p_excesso < 0,05 (contas da mesma pergunta: com lados discordando vale a mais fraca)",
           "proibido": ["'a melhor pista'", "'nenhum número chega nela'", "'com força que nenhum número de jogo passa' (o intervalo não deixa ordenar)", "comparar ρ parcial com ρ bruto dos pontos"]},
    p=P("etapa_7.excesso.sem_sinal.p_excesso", 0.1183), ceticos=True,
    rev15="rodada sem dinheiro (15/09): segue FRACO (as contas da lista dos 28 discordam). Sai a constante 'desconto do dinheiro: não existe nesta etapa'",
    rev="reconferência 14/09: o número do melhor indicador é a correlação BRUTA (0,44), não a parcial (0,34); a frase não diz mais que nenhum número passa da tabela, porque o intervalo não deixa ordenar; lacuna do intervalo saiu (não estava no molde)",
    faixa_keep=True,
    rodape_ops=[("replace", "tabela menos o melhor número: +0,057", "tabela menos o melhor número: 0,496 − 0,439 (correlações brutas; a parcial da distância do chute é −0,34) = +0,057")],
))

C.append(conc(
    id="J9", tema="jogo_e_padroes", etapa="etapa_8", selo="fraco", declarada=True,
    titulo="Os {n_prom} que subiram, cortados em dois eixos, caem em quatro estilos de jogo — um contínuo cortado em quatro, não tipos naturais",
    frase="Cruzando de quem é o campo e a área (território) com como a bola chega lá, pelo chão ou direta (rota), os {n_prom} que subiram de {ano_ini} a {ano_fim} se dividem em grupos de {tamanhos}. Os grupos se distinguem em indicadores que não entraram na construção mais do que o acaso faria. É um sinal {selo}: numa bateria mais limpa a conta muda com os indicadores usados para validar. Em {n_tipos} grupos a diferença passa no teste; no {grupo_descritivo} não se viu diferença.",
    numero="Contra divisões feitas com indicadores reais de futebol, o acaso produziria essa separação em {p_placebo_chance}; na bateria mais limpa, em {p_limpa_faixa}, conforme os indicadores usados para validar.",
    ressalva="Não quer dizer que existem tipos naturais de time que sobe: é um contínuo cortado por duas medianas, e, tirando um time de cada vez, {fronteira} mudam de grupo. Não prevê quem sobe, não diz a chance de subir e não é mapa de rota. Os dois eixos andam com o valor do elenco (J10).",
    universo=UNIVERSOS["tipologia"],
    lac={
        "tamanhos": D("texto", "etapa_8.tipologia.grupos[].n, vírgulas e 'e'", ["etapa_8.tipologia.grupos"]),
        "n_tipos": D("inteiro_por_extenso", "grupos com status = TIPO", ["etapa_8.tipologia.grupos"]),
        "grupo_descritivo": D("texto", "grupos com status != TIPO: 'grupo do NOME (times)'", ["etapa_8.tipologia.grupos"]),
        "p_placebo_chance": G("chance_em_1000", "etapa_8.tipologia.teste_de_fora.p_placebo"),
        "p_limpa_faixa": N("texto", "etapa_8.tipologia.bateria_limpa.por_conjunto_de_validadores", "menor e maior p_placebo, 'N a M de cada 100 tentativas'"),
        "fronteira": D("texto", "times que mudam de grupo em etapa_8.tipologia.estabilidade.tirar_um_time[].trocaram, sem repetição, 'X e Y'", ["etapa_8.tipologia.estabilidade.tirar_um_time"]),
    },
    val={"tamanhos": "5, 3, 3 e 5", "n_tipos": "três", "grupo_descritivo": "grupo do cerco de bola direta (Bahia 2022, Sport 2024, Ceará 2024)", "p_limpa_faixa": "4 a 10 de cada 100 tentativas",
         "fronteira": "Vitória 2023 e Sport 2024", "selo": "fraco"},
    crit=[
        K("teste de fora contra divisões com indicadores reais (p < 0,05)", "etapa_8.tipologia.teste_de_fora.p_placebo", "0,0039", True),
        K("bateria limpa com os dois conjuntos de validadores (p < 0,05)", "etapa_8.tipologia.bateria_limpa.por_conjunto_de_validadores", "0,035 (22), 0,063 (22, teste cego), 0,099 (23): discordam", False),
    ],
    regra={"fraco_se": "teste_de_fora.p_placebo < 0,05 E bateria_limpa discorda entre conjuntos de validadores (contas da mesma pergunta: vale a mais fraca)",
           "moderado_se": "p_placebo < 0,05 E bateria limpa < 0,05 em todos os conjuntos de validadores",
           "proibido": ["'quatro tipos de time que sobe'", "'não há um jeito só de subir' (afirmação categórica para um selo fraco)", "'muito mais do que o acaso'", "'é só descrição' para um grupo"]},
    p=P("etapa_8.tipologia.teste_de_fora.p_placebo", 0.0039), ceticos=True,
    rev15="rodada sem dinheiro (15/09): segue FRACO (a bateria limpa discorda). Saem o critério do desconto do dinheiro por grupo e, da ressalva, 'descontado o dinheiro, N mudam de lado no território'",
    rev="reconferência 14/09: passou pelo cético de números; título sem 'não há um jeito só'; a bateria limpa cita os três valores (0,035; 0,063; 0,099)",
    faixa_keep=True,
    rodape_ops=[("replace", "bateria limpa: p placebo 0,035 (22 validadores) contra 0,099 (23)", "bateria limpa: p placebo 0,035 (22 validadores, `prototipo.json`), 0,0627 (22, `teste_cego_2018_2021.json bateria_limpa.2022-2025`) e 0,099 (23, TIPOLOGIA.md) · controle a favor da tipologia: a partição feita só com dinheiro não separa os validadores (`dinheiro.particao_rival_so_dinheiro.p` 0,71), só descrição · reconferido pelo cético de 14/09")],
))

C.append(conc(
    id="J10", tema="jogo_e_padroes", etapa="etapa_8", selo="sem_sinal", declarada=True,
    titulo="Não se viu o valor do elenco separar os quatro estilos de subir; os {n_g1} do dono do jogo estavam todos entre os {k_top_g1} elencos mais caros do ano",
    frase="Pela conta declarada (o quanto os quatro grupos de quem subiu, de {ano_ini} a {ano_fim}, diferem na posição de valor do elenco no ano, sorteando os grupos), o acaso produziria a diferença em {p_perm_chance}. Por outra conta sobre as mesmas posições (Kruskal-Wallis), em {p_kruskal_chance}. As duas vão para o mesmo lado e o selo segue a declarada. Com {n_prom} times, só uma diferença grande apareceria. O que se viu, e fica nomeado: {excecao_g1}.",
    numero="O acaso produziria a diferença de valor entre os grupos em {p_perm_chance}, pela conta declarada.",
    ressalva="Não quer dizer que estilo e dinheiro não têm relação, nem que escolher entre bola pelo chão ou direta é livre do elenco: na Série B inteira, elenco mais valioso ocupa mais o campo adversário e também joga mais pelo chão. Valor de mercado não é custo.",
    universo=UNIVERSOS["tipologia"],
    lac={
        "n_g1": G("inteiro", "etapa_8.tipologia.grupos[grupo=G1].n"),
        "k_top_g1": D("inteiro", "max(posto_valor) em etapa_8.tipologia.grupos[G1].times", ["etapa_8.tipologia.grupos"]),
        "p_perm_chance": G("chance_em_100", "etapa_8.tipologia.dinheiro.p_permutacao"),
        "p_kruskal_chance": G("chance_em_100", "etapa_8.tipologia.dinheiro.p_kruskal"),
        "excecao_g1": D("texto", "se max(posto_valor) em grupos[G1].times <= 3: 'os N do grupo dono do jogo (nomes) estavam, sem exceção, entre os K elencos mais caros do seu ano'", ["etapa_8.tipologia.grupos"]),
    },
    val={"k_top_g1": "3", "excecao_g1": "os 5 do grupo dono do jogo (Grêmio 2022, Cruzeiro 2022, Atlético-GO 2023, Santos 2024 e Athletico-PR 2025) estavam, sem exceção, entre os 3 elencos mais caros do seu ano"},
    crit=[
        K("conta declarada: diferença de posição de valor entre os grupos, sorteio, p >= 0,10", "etapa_8.tipologia.dinheiro.p_permutacao", "0,124", True),
        K("outra conta (Kruskal-Wallis), mesmo lado, não decide", "etapa_8.tipologia.dinheiro.p_kruskal", "0,0325", None, decide=False),
    ],
    regra={"sem_sinal_se": "dinheiro.p_permutacao >= 0,10 (decisão do dono de 14/09: segue a régua escrita)", "obrigatorio": ["citar o G1 com zero exceção verificada", "citar o Kruskal gravado (p_kruskal)"],
           "proibido": ["'escolher a rota não mostrou custo'", "'custa'", "NÃO DÁ PARA AFIRMAR por contas no mesmo lado", "'valor médio' para as contas da J10", "número digitado no título ('3 elencos')"]},
    p=P("etapa_8.tipologia.dinheiro.p_permutacao", 0.1244), ceticos=True, rev="reconferência 14/09: o '3' do título virou lacuna; universo e critérios",
    rev15="rodada sem dinheiro (15/09): segue SEM SINAL (é o valor contra os estilos, descrição). Sai da ressalva o recorte refeito descontado o valor (quantos mudam de rota e de território), que saiu do gerador", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J16", tema="jogo_e_padroes", etapa="etapa_8", selo="fraco", declarada=False,
    titulo="Os {n_fora} que subiram com elenco fora do top {k8} ocuparam menos o campo adversário",
    frase="Os {n_fora} que subiram sem estar entre os {k8} elencos mais valiosos ({nomes_fora}) ocuparam menos o campo adversário que a metade dos {n_prom} que subiram: {estilos_fora}. É um sinal {selo}: são {n_fora} times, a linha foi escolhida depois de olhar, não há lista de onde ela saia para comparar com a sorte, e {colado_na_linha} ficou colado nela.",
    numero="{n_fora_abaixo} de {n_fora} abaixo da mediana: o acaso produziria isso em {p_hiper_chance}.",
    ressalva="Não quer dizer que time barato tem que jogar reativo para subir, nem que ocupar o campo adversário exige dinheiro: nos mesmos dois estilos, {n_caros_mesmos_estilos} dos que subiram tinham elenco entre os {k5} mais caros. O grupo dono do jogo está na J10.",
    universo=UNIVERSOS["tipologia"],
    lac={
        "n_fora": N("inteiro", "etapa_8.tipologia.fora_do_top_k.n_fora"),
        "k8": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.k"),
        "nomes_fora": N("texto", "etapa_8.tipologia.fora_do_top_k.nomes", "'Clube Ano', vírgulas e 'e'"),
        "estilos_fora": N("texto", "etapa_8.tipologia.fora_do_top_k.estilos", "contagem por grupo em palavras: 'dois foram controladores pacientes e dois reativos de bola direta'"),
        "colado_na_linha": N("texto", "etapa_8.tipologia.fora_do_top_k.colado_na_linha", "'o CLUBE ANO' com |território - corte| < 1"),
        "n_fora_abaixo": N("inteiro", "etapa_8.tipologia.fora_do_top_k.abaixo_da_mediana"),
        "p_hiper_chance": N("chance_em_100", "etapa_8.tipologia.fora_do_top_k.p_hipergeometrico"),
        "n_caros_mesmos_estilos": N("inteiro", "etapa_8.tipologia.fora_do_top_k.caros_nos_mesmos_estilos"),
        "k5": D("inteiro", "tamanho do quartil de cima por ano (etapa_1.quartis[quartil=4].n / n_anos)", ["etapa_1.quartis"]),
    },
    val={"n_fora": "4", "nomes_fora": "Vitória 2023, Mirassol 2024, Criciúma 2023 e Chapecoense 2025", "estilos_fora": "dois foram controladores pacientes e dois reativos de bola direta",
         "colado_na_linha": "o Vitória 2023", "n_fora_abaixo": "4", "p_hiper_chance": "4 de cada 100 tentativas", "n_caros_mesmos_estilos": "4", "k5": "5"},
    crit=[
        CONST("1. linha declarada antes", False, papel="declarada", txt="não: a linha (fora do top 8) foi escolhida depois de olhar"),
        KM("4 de 4 abaixo da mediana, hipergeométrica, p < 0,05", "etapa_8.tipologia.fora_do_top_k.p_hipergeometrico", papel="p", op="<", lim=0.05, v=0.038),
        CONST("4. lista acima da sorte (regra do dono)", False, papel="lista", txt="não há lista"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): linha escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "p hipergeométrico < 0,05 E linha escolhida depois de olhar sem lista", "moderado_se": "impossível: linha escolhida depois, sem lista",
           "saiu_em_15_09": "'comparando elencos de valor parecido, 3 dos 4 mudam de lado' (trocam_no_dinheiro)",
           "proibido": ["repetir a exceção do G1 (J10)", "'estilo de quem não tem dinheiro'"]},
    p=P("etapa_8.tipologia.fora_do_top_k.p_hipergeometrico", 0.038), ceticos=True, rev="reconferência 14/09: regra do dono reaplicada (sem lista, some no dinheiro): segue fraco",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o critério 'trocam de lado descontado o dinheiro' e a frase correspondente; decide a regra da linha escolhida depois, sem lista",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J11", tema="jogo_e_padroes", etapa="etapa_15", selo="sem_sinal", declarada=True,
    titulo="Formação: não se viu diferença entre quem sobe e o meio da tabela, nem entre os estilos de quem subiu",
    frase="A formação mais usada foi a {form_top} em {n_sobe_top} dos {n_sobe} que subiram, {n_meio_top} dos {n_meio} do meio e {n_cai_top} dos {n_cai} que caíram, de {ano_ini} a {ano_fim}. Com {n_sobe} contra {n_meio}, {frase_tamanho}. Do lado de baixo há uma diferença no número de formações usadas, com selo próprio (J17).",
    numero="Entre quem sobe e o meio, o acaso produziria a diferença no número de formações em {p_sistemas_chance}; entre os estilos de quem subiu, a diferença na linha de três em {p_linha3_chance}.",
    ressalva="Não quer dizer que formação não importa, nem que qualquer desenho serve: a formação anotada é a do papel, não a do campo, e uma diferença pequena não apareceria.",
    universo=UNIVERSOS["clube"],
    lac={
        "form_top": N("texto", "etapa_15.proxy_sistema.formacao_principal_por_faixa.mais_comum_sobe"),
        "n_sobe_top": N("inteiro", "etapa_15.proxy_sistema.formacao_principal_por_faixa", "sobe[mais_comum_sobe]"),
        "n_meio_top": N("inteiro", "etapa_15.proxy_sistema.formacao_principal_por_faixa", "meio[mais_comum_sobe]"),
        "n_cai_top": N("inteiro", "etapa_15.proxy_sistema.formacao_principal_por_faixa", "cai[mais_comum_sobe]"),
        "p_sistemas_chance": G("chance_em_100", "etapa_15.proxy_sistema.testes.sistemas_distintos.p_SM"),
        "p_linha3_chance": G("chance_em_100", "etapa_8.tipologia.formacao.linha3.p"),
    },
    val={"form_top": "4-2-3-1", "n_sobe_top": "9", "n_meio_top": "29", "n_cai_top": "9"},
    crit=[
        K("formação entre estilos, p >= 0,10", "etapa_8.tipologia.formacao.linha3.p", "linha de três 0,78; formações 0,83; % na principal 0,94", True),
        K("proxy do gerador, quem sobe contra o meio, p >= 0,10", "etapa_15.proxy_sistema.testes.sistemas_distintos.p_SM", "sistemas 0,68; trocas 0,99; fidelidade 0,24", True),
    ],
    regra={"sem_sinal_se": "formacao.*.p >= 0,10 E proxy_sistema.testes.*.p_SM >= 0,10", "proibido": ["'não separou nada'", "'o 4-2-3-1 é de todo mundo'", "'a única diferença'"]},
    p=P("etapa_15.proxy_sistema.testes.sistemas_distintos.p_SM", 0.6764), ceticos=True, rev="reconferência 14/09: contagem da formação principal por faixa pedida ao gerador (9, 29, 9 conferidos em `r13_varios.py`)", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="J17", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem cai usou mais formações diferentes que quem sobe de {ano_ini} a {ano_fim}",
    frase="De {ano_ini} a {ano_fim}, quem caiu usou {form_cai} formações diferentes na temporada (mediana), contra {form_sobe} em quem subiu e {form_meio} no meio da tabela. É um sinal {selo}: na comparação declarada antes, quem sobe contra quem cai, o acaso produziria a diferença em {p_sc_chance}; contando os {n_familia_elenco} números do elenco, {frase_q}; e em {periodo_antigo} quem caiu também usou mais formações que quem subiu ({p_sc_antigo_chance}). Firme por pouco e conferida por um caminho só, fica moderado.",
    numero="Contra o meio da tabela a diferença também aparece ({p_cm_chance}; em {periodo_antigo}, {p_cm_antigo_chance}), mas essa comparação foi escolhida depois de olhar e fica só descrita: o título continua sendo o da comparação declarada.",
    ressalva="Não quer dizer que mudar pouco o desenho evita cair. Trocar de técnico ou de time no meio do ano pode mudar a formação; o estudo não tem o técnico nem a data da troca (J12). O número de formações anda com o número de jogadores usados (ELE-01). Elenco valioso tende a ter isso; o estudo não separa as duas coisas. A fidelidade à formação principal tem duas contas: pela declarada não se viu diferença; pela do gerador, quem cai é menos fiel que quem sobe, mas o selo segue a declarada.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "form_cai": N("dec1", "etapa_2.linhas[].mediana_cai", "formacoes"),
        "form_meio": N("dec1", "etapa_2.linhas[].mediana_meio", "formacoes"),
        "form_sobe": N("dec1", "etapa_2.linhas[].mediana_sobe", "formacoes"),
        "p_sc_chance": G("chance_em_100", "etapa_2.linhas[indicador=formacoes].p_bruto_SC"),
        "frase_q": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=formacoes].q_SC"]),
        "p_sc_antigo_chance": N("chance_em_100", "etapa_2.linhas[].antigo_SC", "formacoes: p"),
        "p_cm_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CM", "formacoes"),
        "p_cm_antigo_chance": N("chance_em_100", "etapa_2.linhas[].antigo_CM", "formacoes: p"),
    },
    val={"form_cai": "8,5", "form_meio": "6,5", "form_sobe": "6,5", "frase_q": "é firme por pouco", "p_sc_antigo_chance": "3 de cada 100 tentativas", "p_cm_chance": "3 de cada 1.000 tentativas",
         "p_cm_antigo_chance": "14 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação do título declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05 (quem sobe contra quem cai)", "etapa_2.linhas[indicador=formacoes].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=formacoes].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025); entre 0,025 e 0,05 é firme por pouco", "etapa_2.linhas[indicador=formacoes].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: 2018-2021, quem sobe contra quem cai, p < 0,05 no mesmo lado (medianas 5,0 / 5,5 / 6,0)", "etapa_2.linhas[indicador=formacoes].antigo_SC", papel="conf", op="<", lim=0.05, sub="p", v=0.025),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: 2018-2021 (formação sem versão por jogo na etapa 7)"),
        CONST("há uma conferência testável só", True, papel="uma_conf", txt="sim: só 2018-2021"),
        KM("4. lista do elenco, quem sobe contra quem cai, acima da sorte", "etapa_3.por_familia.elenco.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem cai contra o meio (escolhida depois de olhar; só descrição, não vai para o título): lista do elenco acima da sorte", "etapa_3.por_familia.elenco.excesso.CM.bruto.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum), com a regra geral da resposta a do dono: firme por pouco (0,025 <= q < 0,05) com uma conferência só = moderado",
           "comparacao_da_frase": "SC declarada (linha do catálogo, família elenco)",
           "moderado_se": "q_SC < 0,05 E (alguma conferência falha OU firme por pouco com uma conferência só OU nenhuma conferência testável)",
           "forte_se": "q_SC < 0,05 E pelo menos uma conferência testável, todas passando, E não firme por pouco com uma conferência só",
           "parte_CM": "escolhida depois de olhar; descrita ao lado com o próprio resultado (lista do elenco 5 contra 0, p 0,0067); não vai para o título",
           "fonte": "coluna formacoes do painel = proxy sistemas_distintos do gerador nas 80 temporadas (conferido pelo cético); a linha JÁ existe no catálogo (família elenco)",
           "ressalva": "sem desconto e sem receita (resposta b do dono); a medida por coluna vai para etapa_2.andam_com_o_valor",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC 0,125, era o único motivo do fraco) e o mesmo clube no ano seguinte",
           "proibido": ["'mude pouco a formação'", "'trocar de técnico muda o desenho' como fato", "'menos fiel' sem as duas contas", "'as medidas de formação não têm a conta dos muitos testes' (estão na família do elenco)", "título pela comparação quem cai contra o meio (escolhida depois)", "'some entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=formacoes].p_bruto_SC", 0.02428), ceticos=True, nova_em="2026-09-14 (conserto)",
    rev="conserto final 14/09: moderado → fraco. Na reconferência o título tinha sido trocado da comparação declarada (quem sobe contra quem cai) para quem cai contra o meio, a única das duas que passa no dinheiro (0,009 contra 0,125), e o selo subia pela troca. A decisão 1 do dono vale para a comparação que a conclusão já tinha no título; o título volta à declarada e quem cai contra o meio fica descrita ao lado",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. O desconto do valor (p 0,125) era o único motivo do fraco. Pela régua final seria forte (firme, q 0,0447, e 2018-2021 passa, p 0,025), mas é firme por pouco e com uma conferência só: MODERADO pela regra geral da resposta a do dono. Título sem '— mas isso some entre elencos de valor parecido'; entra a ressalva sem desconto",
    faixa_keep=True,
    rodape_texto="nova na rodada de conserto de 14/09 (era sinal sem selo dentro da J11); reconferida pelo cético de números em 14/09 · `formacoes` do painel (`dados/serieb_clube_temporada.csv` e `_2018_2021.csv`), idêntica ao proxy `sistemas_distintos` do gerador nas 80 temporadas (6,88 / 6,69 / 8,06) · a coluna está na família declarada do elenco (10), linha gravada em `etapa_2.linhas[formacoes]` · **selo: MODERADO na rodada sem dinheiro de 15/09** (em 14/09 era FRACO, só pelo desconto do valor, p 0,125): firme por pouco (q 0,0447) e com uma conferência só (2018-2021) · 2022-2025, medianas sobe / meio / cai 6,5 / 6,5 / 8,5 · **sobe x cai (declarada, a do título):** Mann-Whitney 0,033, Welch no posto 0,024, q 0,045 (10) · **cai x meio (escolhida depois, só descrição):** Welch no posto p 0,0025; lista do elenco cai x meio 5 contra 0 (atletas usados, XI mais usado, concentração de minutos, núcleo de 300+ minutos e formações), p do excesso 0,006 (`r4_saida.json`; 0,0067 no dado novo) · sobe x meio 0,61 · 2018-2021, medianas 5,0 / 5,5 / 6,0: sobe x cai 0,025 (Mann-Whitney 0,020), refeito no CSV, ainda não gravado (`etapa_2.linhas[formacoes].antigo_SC`); cai x meio no posto 0,14 (Mann-Whitney 0,11) · fidelidade: `fidelidade_media` do gerador 87,0 / 85,4 / 83,6, sobe x cai p 0,016; `formPrincipalPct` do painel (a declarada) sobe x cai 0,29 (2022-25) e 0,12 (2018-21) → segue a declarada (`cf_num/v_j17.py`) · onde ver na aba: etapa 2 e etapa 15",
))

C.append(conc(
    id="J18", tema="jogo_e_padroes", etapa="etapa_2", selo="sem_sinal", declarada=True,
    titulo="Contra-ataque e cruzamento: não se viu quem sobe diferente do meio em {periodo_recente}; em {periodo_antigo} separaram, no número cru",
    frase="Em {periodo_recente}, quem subiu ficou praticamente no mesmo lugar que o meio da tabela no ranking de contra-ataques e de cruzamentos do ano: o acaso produziria as diferenças em {p_ca_chance} e {p_cruz_chance}. Com {n_sobe} contra {n_meio}, {frase_tamanho}. Em {periodo_antigo}, quem subiu ficou bem acima do meio nos dois, e isso resiste à conta dos {n_familia_tecnico_col} números de jogo daquele período.",
    numero="Os dois períodos vão para o mesmo lado; o selo sai do período principal.",
    ressalva="Não quer dizer que contra-ataque e cruzamento deixaram de importar, nem que passaram a pesar menos: a diferença entre os períodos não foi testada. O contra-ataque só se compara pela posição no ranking do ano, porque a contagem crua muda muito entre os anos.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "p_ca_chance": G("chance_em_100", "etapa_2.linhas[indicador=contra_ataques].p_bruto_SM"),
        "p_cruz_chance": G("chance_em_100", "etapa_2.linhas[indicador=cruzamentos].p_bruto_SM"),
    },
    crit=[
        K("período principal, quem sobe contra o meio, p >= 0,10 nas duas", "etapa_2.linhas[indicador=contra_ataques].p_bruto_SM", "0,68 e 0,78", True),
        K("período antigo (descrição: o selo sai do período principal, declarado)", "etapa_2.linhas[].antigo_SM", "0,0057 e 0,0018", None, decide=False),
    ],
    regra={"sem_sinal_se": "p_bruto_SM >= 0,10 em 2022-2025 nas duas linhas", "nao_da_para_afirmar_se": "os dois períodos com d de sinais opostos", "proibido": ["'passaram a pesar menos'", "'não importam'"]},
    p=P("etapa_2.linhas[indicador=contra_ataques].p_bruto_SM", 0.67641), ceticos=True, nova_em="2026-09-14 (conserto)",
    rev="reconferência 14/09: passou pelo cético de números (2018-2021 reproduzido: 0,0057 e 0,0018)", rev15="rodada sem dinheiro (15/09): segue SEM SINAL (p 0,68). Sai 'mas não há valor de mercado para descontar' como motivo de o período antigo não promover: o selo sai do período principal", faixa_keep=True,
    rodape_ops=[("replace", "nova na rodada de conserto de 14/09 (era sinal sem selo dentro da J14)", "nova na rodada de conserto de 14/09 (era sinal sem selo dentro da J14); reconferida pelo cético de números em 14/09")],
))

C.append(conc(
    id="J12", tema="jogo_e_padroes", etapa="etapa_15", selo="nao_da_para_afirmar", declarada=True,
    titulo="Trocar de técnico ajuda ou atrapalha?",
    frase="Não há, em nenhuma base do estudo, o nome do técnico nem a data da troca. A pergunta nunca foi medida.",
    numero="Bases conferidas: {bases}.",
    ressalva="Não quer dizer nada, para nenhum lado. A coleta que resolveria é uma tabela {coleta}, do ogol.",
    universo="todas as bases do estudo ({bases})",
    lac={
        "bases": G("texto", "etapa_15.bases_conferidas.procurado_em"),
        "coleta": G("texto", "etapa_15.coleta_que_resolveria.tabela"),
    },
    crit=[K("o dado existe", "etapa_15.tem_nome_de_treinador", "não", False)],
    regra={"nao_da_para_afirmar_se": "etapa_15.tem_nome_de_treinador = false (caso b da régua)"},
    p=P(None, None), ceticos=False, rev="reconferência 14/09: universo e critério; p_principal nulo (dado inexistente)", faixa_keep=True, rodape_ops=[],
))
