# Tema 1: dinheiro e elenco (DIN, ORI, ELE)
from sp6_base import *

C = []

C.append(conc(
    id="DIN-01", tema="dinheiro_e_elenco", etapa="etapa_1", selo="forte", declarada=True,
    titulo="O valor do elenco separa quem sobe, e é um dos sinais fortes do estudo (a DIN-02 é o mesmo sinal visto por outro corte)",
    frase="Quem sobe costuma ter um dos elencos mais valiosos do ano: {prom_top8} dos {n_prom} que subiram estavam entre os {k8} mais caros, {fracao_simples}. Somando os {n_anos} anos, entre os {k_quartil} elencos mais caros de cada temporada ({n_q4} no total), {sub_q4} subiram; entre os {k_quartil} mais baratos, subiu {sub_q1} e caíram {cai_q1}.",
    numero="Comparando a posição de cada time no ranking de valor do seu ano, o time que subiu tinha elenco mais caro que o que não subiu em {auc_sr_100}; contra quem caiu, em {auc_sc_100}.",
    ressalva="Não quer dizer que montar o elenco mais valioso faz subir: elenco valioso vem com torcida, estrutura e camisa, e o estudo não distingue uma coisa da outra. Estar entre os mais caros não bastou: dos {clubes_top8} elencos que eram top {k8} do seu ano, {top8_nao_subiram} não subiram ({exemplo_top1_nao_subiu}). Nem que fora do top {k8} não se sobe: {prom_fora_top8} dos {n_prom} subiram assim. Qual indicador separa mais nunca foi testado contra os outros. Em {ano_parcial}, com {rodadas_parcial} rodadas, o grupo de acesso de hoje aponta para o mesmo lado, mas só vale no fim do campeonato.",
    tecnico="acerto de pares {auc_sr} (intervalo de 95% de {ic_lo} a {ic_hi}); por ano {auc_por_ano}; deixando um ano de fora {loso}",
    extra={"descricao_em_euros": "Para ter um dos {k4} elencos mais valiosos da Série B era preciso um elenco avaliado entre {eur_k4_min} e {eur_k4_max} milhões de euros, conforme o ano; para estar entre os {k8}, entre {eur_k8_min} e {eur_k8_max} milhões. Essa régua sobe: o elenco típico da liga foi de {eur_mediana_primeiro} para {eur_mediana_ultimo} milhões de {ano_ini} a {ano_fim}, então o valor em euros de um ano não vale para o outro — o que conta é a posição no ranking do ano. Dos {n_bloco_1_4} elencos que eram top {k4} do ano, {sub_bloco_1_4} subiram e {cai_bloco_1_4} caiu; dos {n_bloco_5_8} entre o {k5}º e o {k8}º, subiram {sub_bloco_5_8} e caíram {cai_bloco_5_8}. E a posição de valor não decide sozinha: contando os times a até duas posições de valor de cada um que subiu, {vizinhos_2_por_sobe} não subiram para cada um que subiu (a até uma posição, {vizinhos_1_por_sobe}). Valor de mercado não é quanto se gastou."},
    universo=UNIVERSOS["clube_valor"],
    lac={
        "prom_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].promovidos_acumulados"),
        "k8": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.k"),
        "k4": G("inteiro", "etapa_1.curva_top_k.curva[k=4].k"),
        "fracao_simples": D("texto", "prom_top8/n_prom reduzida a 'N em cada M' quando M <= 5", ["prom_top8", "n_prom"]),
        "n_anos": G("contagem_da_lista", "etapa_1.curva_top_k.anos"),
        "k_quartil": D("inteiro", "etapa_1.quartis[quartil=4].n / n_anos", ["etapa_1.quartis", "n_anos"]),
        "n_q4": G("inteiro", "etapa_1.quartis[quartil=4].n"),
        "sub_q4": G("inteiro", "etapa_1.quartis[quartil=4].subiram"),
        "sub_q1": G("inteiro", "etapa_1.quartis[quartil=1].subiram"),
        "cai_q1": N("inteiro", "etapa_1.quartis[].cairam", "quartil 1"),
        "auc_sr_100": G("pares_em_100", "etapa_1.auc_posto_de_valor.sobe_x_resto"),
        "auc_sc_100": G("pares_em_100", "etapa_1.auc_posto_de_valor.sobe_x_cai"),
        "clubes_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].clubes_no_top_k"),
        "top8_nao_subiram": D("inteiro", "clubes_no_top_k - promovidos_acumulados em curva[k=8]", ["etapa_1.curva_top_k.curva"]),
        "exemplo_top1_nao_subiu": N("texto", "etapa_1.top4_de_valor.por_ano[].posicao_final", "o posto 1 que não subiu: 'o mais caro de ANO, o CLUBE, terminou em Nº'"),
        "prom_fora_top8": D("inteiro", "promovidos com posto_valor > k8", ["etapa_1.curva_top_k.promovidos"]),
        "rodadas_parcial": G("inteiro", "etapa_1.fora_da_amostra_2026.J"),
        "auc_sr": G("dec2", "etapa_1.auc_posto_de_valor.sobe_x_resto"),
        "ic_lo": N("dec2", "etapa_1.auc_posto_de_valor.ic95", "[0]"),
        "ic_hi": N("dec2", "etapa_1.auc_posto_de_valor.ic95", "[1]"),
        "auc_por_ano": N("texto", "etapa_1.auc_posto_de_valor.por_ano", "auc_sobe_x_resto por ano, dec2 separados por ' / '"),
        "loso": G("dec2", "etapa_1.auc_posto_de_valor.loso_sobe_x_resto"),
        "eur_k4_min": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=4, menor ano"),
        "eur_k4_max": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=4, maior ano"),
        "eur_k8_min": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=8, menor ano"),
        "eur_k8_max": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=8, maior ano"),
        "eur_mediana_primeiro": N("milhoes_dec1", "etapa_1.valor_mediano_da_liga_por_ano", "primeiro ano"),
        "eur_mediana_ultimo": N("milhoes_dec1", "etapa_1.valor_mediano_da_liga_por_ano", "último ano"),
        "n_bloco_1_4": N("inteiro", "etapa_1.blocos_de_posto", "posto 1-4: n"),
        "sub_bloco_1_4": N("inteiro", "etapa_1.blocos_de_posto", "posto 1-4: subiram"),
        "cai_bloco_1_4": N("inteiro_por_extenso_se_zero", "etapa_1.blocos_de_posto", "posto 1-4: cairam"),
        "n_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: n"),
        "k5": N("inteiro", "etapa_1.blocos_de_posto", "primeiro posto do bloco 5-8"),
        "sub_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: subiram"),
        "cai_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: cairam"),
        "vizinhos_2_por_sobe": N("dec1", "etapa_1.vizinhos_de_valor", "ate=2: por_promovido"),
        "vizinhos_1_por_sobe": N("dec1", "etapa_1.vizinhos_de_valor", "ate=1: por_promovido"),
    },
    val={"fracao_simples": "3 em cada 4", "k_quartil": "5", "cai_q1": "8", "top8_nao_subiram": "20", "exemplo_top1_nao_subiu": "o mais caro de 2023, o Ceará, terminou em 11º",
         "prom_fora_top8": "4", "ic_lo": "0,70", "ic_hi": "0,94", "auc_por_ano": "1,00 / 0,72 / 0,84 / 0,75",
         "eur_k4_min": "18", "eur_k4_max": "25", "eur_k8_min": "14", "eur_k8_max": "20", "eur_mediana_primeiro": "12,5", "eur_mediana_ultimo": "18,0",
         "n_bloco_1_4": "16", "sub_bloco_1_4": "10", "cai_bloco_1_4": "nenhum", "n_bloco_5_8": "16", "k5": "5", "sub_bloco_5_8": "2", "cai_bloco_5_8": "2",
         "vizinhos_2_por_sobe": "2,5", "vizinhos_1_por_sobe": "1,3"},
    crit=[
        CONST("1. teste declarado antes (baseline do valor do elenco): quem sobe contra o meio na posição de valor do ano", True, papel="declarada", txt="sim"),
        KM("p bilateral < 0,05", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="p", op="<", lim=0.05),
        KM("2. firme: teste único declarado, q = p < 0,05", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: cada ano sozinho, acerto de pares acima de 0,5", "etapa_1.auc_posto_de_valor.por_ano", papel="conf", op=">", lim=0.5, ag="todos", sub="auc_sobe_x_resto", v=[1.0, 0.72, 0.84, 0.75]),
        KM("3. conferência: deixando um ano de fora, acerto acima de 0,5", "etapa_1.auc_posto_de_valor.loso_sobe_x_resto", papel="conf", op=">", lim=0.5),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: cada ano sozinho e deixando um ano de fora"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum; o teste é por ano, então valem 'cada ano sozinho' e 'deixando um ano de fora')",
           "forte_se": "p_sobe_x_meio < 0,05 (teste único, q = p) E todo auc_posto_de_valor.por_ano[].auc_sobe_x_resto > 0,5 E loso_sobe_x_resto > 0,5",
           "moderado_se": "p_sobe_x_meio < 0,05 E alguma das duas conferências falha",
           "conferencia_sem_p": "as duas conferências (cada ano sozinho e deixando um ano de fora) são acerto de pares de quem sobe contra o resto acima de 0,5, sem p; com poucos promovidos por ano, um acerto pouco acima de 0,5 não se distingue do acaso. Pergunta em aberto para o dono: se ele não aceitar isso como conferência, a DIN-01 cai para moderado pela cláusula 'sem conferência testável'; até a decisão, o selo segue o plano aprovado",
           "saiu_em_15_09": "o controle da cobertura do valor (p_valor_descontada_cobertura) e a constante 'o desconto do dinheiro não se aplica'",
           "proibido": ["'o que MAIS separa' sem teste de ordem", "contar 2026 como repetição", "'gasto', 'gastar', 'custa', 'orçamento' para valor de mercado", "'quase sempre'", "'o sinal mais sólido'", "'um dos três sinais fortes' (DIN-01 e DIN-02 são o mesmo sinal)", "'descontado quanto do elenco o Transfermarkt avalia' (controle da cobertura saiu em 15/09)"],
           "descricao_em_euros": "sem teste próprio: herda o selo da DIN-01 (não existe sexto rótulo)"},
    p=P("etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", 0.000491), ceticos=True,
    rev="reconferência 14/09: título sem 'três sinais fortes' (DIN-01 e DIN-02 são o mesmo sinal), 'grupo de acesso' no lugar de G4, universo e critérios escritos; o p de quem sobe contra o meio já estava gravado em valor_por_setor.setores[total]",
    rev15="rodada sem dinheiro (15/09): segue FORTE. Sai o controle da cobertura do valor (sem preço = valor baixo, decisão do dono de 14/09) e a frase 'descontado quanto do elenco o Transfermarkt avalia'; teste declarado p 0,0005 (teste único: q = p), acerto acima de 0,5 em todo ano e 0,81 deixando um ano de fora. Fica fora das cinco até o gerador gravar `etapa_1.auc_posto_de_valor.por_ano`",
    faixa_keep=True,
    rodape_ops=[("replace", " · descontada a cobertura p 0,005, AUC 0,78", " · a cobertura do valor (quanto do elenco tem preço) fica descrita na etapa 1 e deixou de ser controle em 15/09"),
                ("append", " · o p de quem sobe contra o meio já está gravado em `etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio` (0,00049); faltam gravar `auc_posto_de_valor.ic95` e `.por_ano`")],
))

C.append(conc(
    id="DIN-02", tema="dinheiro_e_elenco", etapa="etapa_1", selo="forte", declarada=True,
    titulo="{prom_top8} dos {n_prom} que subiram estavam entre os {k8} elencos mais caros do ano",
    frase="E {prom_top4} entre os {k4} mais caros. O palpite de {palpite} entre os {k8} mais caros não se confirma: esse número só aparece somando o {k_palpite}º. Vieram de fora dos {k8}: {fora_top8}.",
    numero="Num sorteio, o esperado seriam {esp_top8} no top {k8}; o acaso produziria {prom_top8} ou mais em {p_top8_em_1000}. Aconteceu nos {n_anos} anos: {prom_top8_por_ano} dos {prom_por_ano} que subiram em cada ano.",
    ressalva="Não quer dizer que a linha de corte é o {k8}º ou o {k_palpite}º: o salto de {prom_top8} para {palpite} são {degrau} times em {n_anos} anos. E não é receita: dos {clubes_top8} elencos que eram top {k8} do seu ano, {top8_nao_subiram} não subiram.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "prom_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].promovidos_acumulados"),
        "k8": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.k"),
        "prom_top4": G("inteiro", "etapa_1.curva_top_k.curva[k=4].promovidos_acumulados"),
        "k4": G("inteiro", "etapa_1.curva_top_k.curva[k=4].k"),
        "palpite": D("inteiro", "o número em palpite_do_dono.afirmado ('>= 14' → 14)", ["etapa_1.curva_top_k.palpite_do_dono.afirmado"]),
        "k_palpite": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.menor_k_com_14"),
        "fora_top8": D("texto", "etapa_1.curva_top_k.promovidos com posto_valor > k8, ordenados pelo posto: 'Clube Ano (Nº)', vírgulas e 'e' no último", ["etapa_1.curva_top_k.promovidos", "k8"]),
        "esp_top8": G("faixa_inteira", "etapa_1.curva_top_k.curva[k=8].esperado_por_acaso"),
        "p_top8_em_1000": G("em_1000", "etapa_1.curva_top_k.curva[k=8].p_exato_maior_igual"),
        "n_anos": G("contagem_da_lista", "etapa_1.curva_top_k.anos"),
        "prom_top8_por_ano": D("texto", "contagem por ano de etapa_1.curva_top_k.promovidos com posto_valor <= k8, vírgulas e 'e' no último", ["etapa_1.curva_top_k.promovidos", "k8"]),
        "prom_por_ano": G("inteiro", "etapa_1.curva_top_k.promovidos_por_ano[0]"),
        "degrau": D("inteiro_por_extenso", "palpite - prom_top8", ["palpite", "prom_top8"]),
        "clubes_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].clubes_no_top_k"),
        "top8_nao_subiram": D("inteiro", "clubes_no_top_k - promovidos_acumulados em curva[k=8]", ["etapa_1.curva_top_k.curva"]),
    },
    val={"palpite": "14", "fora_top8": "Vitória 2023 (9º), Mirassol 2024 (9º), Criciúma 2023 (12º) e Chapecoense 2025 (18º)", "prom_top8_por_ano": "4, 2, 3 e 3", "degrau": "dois", "top8_nao_subiram": "20"},
    crit=[
        K("corte declarado antes (o palpite do dono, sem busca de corte)", "etapa_1.curva_top_k.palpite_do_dono.k", "8", True),
        K("sorteio: 12 ou mais no top 8, p exato < 0,05", "etapa_1.curva_top_k.curva[k=8].p_exato_maior_igual", "0,0023", True),
        K("repetição: acima do esperado por acaso em todo ano (contagem da lista gravada de promovidos)", "etapa_1.curva_top_k.promovidos", "4, 2, 3 e 3 contra 1,6 por ano", True),
    ],
    regra={"forte_se": ["k declarado antes (palpite_do_dono.k), sem busca de corte", "p_exato_maior_igual em curva[k=palpite] < 0,05", "promovidos no top k acima de esperado_por_acaso/n_anos em todo ano (contagem direta da lista gravada etapa_1.curva_top_k.promovidos)"],
           "moderado_se": "algum ano abaixo do esperado", "sem_selo": "a escolha da fronteira (k)"},
    p=P("etapa_1.curva_top_k.curva[k=8].p_exato_maior_igual", 0.00227), ceticos=True,
    rev="reconferência 14/09: contagem por ano tirada da lista gravada de promovidos (não precisa de campo novo); universo e critérios escritos",
    rev15="rodada sem dinheiro (15/09): segue FORTE. Só sai a constante 'desconto do dinheiro — não se aplica'",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="DIN-03", tema="dinheiro_e_elenco", etapa="etapa_1", selo="fraco", declarada=False,
    titulo="Do lado de baixo, o valor do elenco também pesa — menos, e não se viu isso em todo ano",
    frase="Entre os {k_quartil} elencos mais valiosos de cada ano, de {ano_ini} a {ano_fim}, {cai_q4} caiu pelo Transfermarkt e caiu {cai_q4_wyscout} pelo valor do Wyscout ({exemplo_wyscout}); a sorte produziria tão poucos em {p_q4_chance} e em {p_q4_wy_chance}. Quem caiu tinha elenco mais barato que o time do meio da tabela em {auc_cm_100}. É um sinal {selo}: a comparação quem cai contra o meio foi escolhida depois de olhar os números, e não há uma lista de onde ela saia para comparar com a sorte, então pela regra do dono não passa de fraco. Além disso, em {ano_sem_sinal_cai} não se viu o valor distinguir rebaixado de meio de tabela, e não há como conferir antes de {ano_ini}.",
    numero="Por ano, esse acerto foi de {auc_cm_por_ano} de cada 100 pares.",
    ressalva="Não quer dizer que elenco caro não cai, nem que elenco top {k_quartil} nunca cai: pelo valor do Wyscout, {exemplo_wyscout}, caiu, e os rebaixados mais caros por essa fonte aparecem nos postos {postos_cai_wyscout}.",
    universo="{n_clube_temporadas} clube-temporadas da Série B de {ano_ini} a {ano_fim} ({n_sobe} subiram, {n_meio} ficaram no meio, {n_cai} caíram), com valor de mercado do Transfermarkt e, como segunda fonte, do Wyscout; {ano_parcial} fica fora de toda conta",
    lac={
        "k_quartil": D("inteiro", "etapa_1.quartis[quartil=4].n / n_anos", ["etapa_1.quartis", "etapa_1.curva_top_k.anos"]),
        "cai_q4": N("inteiro_por_extenso_se_zero", "etapa_1.quartis[].cairam", "quartil 4"),
        "cai_q4_wyscout": N("inteiro", "etapa_1.sensibilidade_fonte_valor.rebaixados_no_top_k"),
        "exemplo_wyscout": N("texto", "etapa_1.sensibilidade_fonte_valor.nomes", "'o CLUBE ANO, Nº'"),
        "p_q4_chance": N("chance_em_100", "etapa_1.curva_top_k_rebaixados.p_quartil"),
        "p_q4_wy_chance": N("chance_em_100", "etapa_1.sensibilidade_fonte_valor.p_quartil"),
        "auc_cm_100": N("pares_em_100", "etapa_1.auc_posto_de_valor.meio_x_cai"),
        "ano_sem_sinal_cai": D("texto", "anos com meio_x_cai_por_ano[].auc <= 0,5, vírgulas", ["etapa_1.auc_posto_de_valor.meio_x_cai_por_ano"]),
        "auc_cm_por_ano": N("texto", "etapa_1.auc_posto_de_valor.meio_x_cai_por_ano", "inteiro(100 × auc) por ano, ' / '"),
        "postos_cai_wyscout": N("texto", "etapa_1.sensibilidade_fonte_valor.postos_rebaixados_valor_total", "os três menores, vírgulas e 'e'"),
    },
    val={"k_quartil": "5", "cai_q4": "nenhum", "cai_q4_wyscout": "1", "exemplo_wyscout": "o Amazonas 2025, 5º", "p_q4_chance": "menos de 1 de cada 100 tentativas",
         "p_q4_wy_chance": "5 de cada 100 tentativas", "auc_cm_100": "75 de cada 100 pares", "ano_sem_sinal_cai": "2022", "auc_cm_por_ano": "50 / 90 / 75 / 83", "postos_cai_wyscout": "5, 6 e 6"},
    crit=[
        CONST("1. comparação declarada antes", False, papel="declarada", txt="não: quem cai contra o meio foi escolhida depois de olhar"),
        KM("p bilateral < 0,05 (quem cai contra o meio, posição de valor no ano)", "etapa_1.auc_posto_de_valor.p_meio_x_cai", papel="p", op="<", lim=0.05, v=0.003),
        CONST("4. lista da comparação com mais achados que a sorte (p do excesso < 0,05)", False, papel="lista", txt="não há lista: é um teste só"),
        KM("nenhum rebaixado no top 5 pelo Transfermarkt, sorteio < 0,05 (descrição)", "etapa_1.curva_top_k_rebaixados.p_quartil", op="<", lim=0.05, v=0.006, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "p_meio_x_cai < 0,05 E comparação escolhida depois de olhar sem lista declarada",
           "moderado_se": "impossível sem uma lista declarada de onde a comparação saia (a regra do dono pede a lista DELA acima da sorte)",
           "sem_sinal_se": "p_meio_x_cai >= 0,10",
           "proibido": ["'nunca cai'", "ancorar a frase no corte do 6º posto", "'o Guarani em 7º desmente top 5' (quem desmente é o 5º pelo Wyscout)"]},
    p=P("etapa_1.auc_posto_de_valor.p_meio_x_cai", 0.003), ceticos=True,
    rev="reconferência 14/09: moderado → fraco pela regra do dono (comparação escolhida depois de olhar só chega a moderado com lista acima da sorte E desconto do dinheiro; aqui não há lista); '1 e 5 de cada 100' escrito por inteiro; exemplo trocado para o Amazonas 2025",
    rev15="rodada sem dinheiro (15/09): segue FRACO, sem mudança de conteúdo. Sai a constante 'desconto do dinheiro: não se aplica' e, da regra do dono, o 'E desconto do dinheiro'",
    faixa_keep=True,
    rodape_ops=[("replace", "recalculado em `selos_a_coletivo.py`, conferido", "recalculado em `selos_a_coletivo.py`, conferido · **selo: FRACO na reconferência de 14/09 (antes MODERADO)**: quem cai contra o meio é comparação escolhida depois de olhar e não sai de lista nenhuma, então a regra do dono (a lista dela acima da sorte) não tem como ser cumprida")],
))

C.append(conc(
    id="DIN-04", tema="dinheiro_e_elenco", etapa="etapa_1", selo="sem_sinal", declarada=True, regime="propria: sem sinal",
    titulo="Não se viu a defesa de quem sobe valer mais do que a parte do elenco que ela ocupa",
    frase="Contando por jogador, a defesa de quem sobe tem um índice de {idx_def_sobe} (a fatia do valor dividida pela fatia de jogadores; um é valor na proporção da gente), contra {idx_def_meio} no meio da tabela, de {ano_ini} a {ano_fim}. Não se viu diferença: o acaso produziria algo assim em {p_idx_chance}, e com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="Em euros, a defesa de quem sobe fica com {pct_def_sobe}% do valor do elenco, contra {pct_def_meio}% no meio (olhando só a defesa, o acaso produziria isso em {p_bruto_chance}; contando os {n_setores} setores, já não dá para descartar a sorte), e ela tem {jog_def_sobe}% dos jogadores, contra {jog_def_meio}%.",
    ressalva="Não quer dizer 'invista na defesa para subir', nem que o ataque de quem sobe vale menos: vale mais em euros, só ocupa uma fatia menor de um bolo maior. Varia muito: {exemplo_min_max}. {sobe_abaixo_meio} dos {n_prom} que subiram tinham fatia em euros abaixo do time típico do meio.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "idx_def_sobe": G("dec2", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].indice_mediano_sobe"),
        "idx_def_meio": G("dec2", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].indice_mediano_meio"),
        "p_idx_chance": G("chance_em_100", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto"),
        "pct_def_sobe": G("pct_inteiro", "etapa_1.valor_por_setor.setores[setor=defesa].pct_do_elenco_mediano_sobe"),
        "pct_def_meio": G("pct_inteiro", "etapa_1.valor_por_setor.setores[setor=defesa].pct_do_elenco_mediano_meio"),
        "n_setores": G("inteiro", "etapa_1.valor_por_setor.particao.testes"),
        "p_bruto_chance": G("chance_em_100", "etapa_1.valor_por_setor.particao.setores[setor=defesa].p_bruto"),
        "jog_def_sobe": G("pct_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].pct_dos_jogadores_mediano_sobe"),
        "jog_def_meio": G("pct_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].pct_dos_jogadores_mediano_meio"),
        "exemplo_min_max": N("texto", "etapa_1.valor_por_setor.por_clube", "no último ano, o promovido de menor e o de maior pct_defesa: 'em ANO subiram X com N% na defesa e Y com M%'"),
        "sobe_abaixo_meio": N("inteiro", "etapa_1.valor_por_setor.por_clube", "promovidos com pct_defesa abaixo da mediana do meio"),
    },
    val={"exemplo_min_max": "em 2025 subiram o Coritiba com 22% na defesa e a Chapecoense com 44%", "sobe_abaixo_meio": "5"},
    crit=[
        KM("pergunta do título, por jogador: índice da defesa, quem sobe contra o meio, p >= 0,10", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto", papel="p", op=">=", lim=0.10),
        KM("contando os 4 setores, por jogador (q < 0,05; descrição)", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].q_bh", op="<", lim=0.05, decide=False),
        KM("fatia em euros, p < 0,05 (descrição: o título lê por jogador, decisão do coordenador de 14/09)", "etapa_1.valor_por_setor.particao.setores[setor=defesa].p_bruto", op="<", lim=0.05, decide=False),
        KM("fatia em euros, contando os 4 setores (q < 0,05; descrição)", "etapa_1.valor_por_setor.particao.setores[setor=defesa].q_bh", op="<", lim=0.05, decide=False),
    ],
    regra_propria=[("sem_sinal", {0: True})],
    regra={"regua": "régua final de 15/09, sem sinal: p >= 0,10 na pergunta do título",
           "familia": "etapa_1.valor_por_setor.ponderado_por_jogador.particao (4 setores, BH), a mesma leitura por jogador da decisão da etapa 1",
           "sem_sinal_se": "ponderado_por_jogador.particao.setores[defesa].p_bruto >= 0,10",
           "descreve": "a fatia em euros (valor_por_setor.particao.setores[defesa]) fica descrita: p < 0,05 olhando só a defesa e q >= 0,05 nos 4 setores",
           "saiu_em_15_09": "o desconto do valor total (p_liquido_do_valor_total)",
           "proibido": ["tratar q_bh como chance de acaso", "'gasta'", "'invista na defesa'", "'é a defesa ter mais gente' como fato (a diferença de gente não foi testada)"]},
    p=P("etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto", 0.26), ceticos=True,
    rev="reconferência 14/09: universo, critérios e anos na frase",
    rev15="rodada sem dinheiro (15/09): FRACO → SEM SINAL. Relida por jogador (decisão do coordenador, a mesma da etapa 1): o índice da defesa (fatia do valor ÷ fatia de jogadores) dá p 0,26 e q 0,94, 'não se viu'. A fatia em euros (p 0,036, q 0,144) fica descrita no número. Sai o desconto do valor total. Título novo, pela pergunta por jogador",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 · leitura por jogador (`etapa_1.valor_por_setor.ponderado_por_jogador`, declarada antes de medir em 14/09, sem desconto pelo valor do elenco): índice da defesa (fatia do valor ÷ fatia de jogadores) mediano 0,97 em quem sobe, 0,86 no meio e 0,89 em quem cai; posto no ano, Mann-Whitney sobe x meio p 0,26, q BH nos 4 setores 0,94 · fatia em euros (`valor_por_setor.particao`): medianas 33,9 / 27,4 / 27,6, p 0,036, q 0,144 · fatia de jogadores da defesa 33,1% contra 31,7% · por ano sobe/meio na fatia em euros 28,6/25,6 · 30,6/28,2 · 41,2/29,7 · 33,9/21,9 · na conta de 14/09 o selo fraco vinha também do desconto do valor total (p 0,20), que saiu da régua · onde ver na aba: etapa 1 · faixa de pontos: não medido",
))

C.append(conc(
    id="DIN-05", tema="dinheiro_e_elenco", etapa="etapa_1", selo="sem_sinal", declarada=True, regime="propria: sem sinal",
    titulo="Setor por setor, não se viu o valor dizer algo além do valor do elenco inteiro",
    frase="Contando por jogador, não se viu nenhum dos {n_setores} setores de quem sobe com uma parte do valor diferente da parte de gente que ocupa, de {ano_ini} a {ano_fim}: no setor mais perto do limite, {setor_menor_p}, o acaso produziria a diferença em {p_menor_chance}. Com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="O valor por jogador de quem sobe é maior na defesa ({eur_j_def_sobe} mil euros contra {eur_j_def_meio} no meio da tabela) e no ataque ({eur_j_ata_sobe} contra {eur_j_ata_meio}), no mesmo lado da DIN-01, sem selo próprio. Contra todos os outros times, o valor da defesa acerta {auc_def}, o do meio-campo {auc_meio}, o do ataque {auc_ataque} e o do elenco inteiro {auc_total} de cada 100 pares.",
    ressalva="Não quer dizer 'invista na defesa', nem que quem sobe acerta num setor específico, nem que o setor e o elenco inteiro dizem a mesma coisa: o estudo não tem tamanho para ordenar os dois (DIN-06).",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "n_setores": G("inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.testes"),
        "setor_menor_p": G("texto", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.setor"),
        "p_menor_chance": G("chance_em_100", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto"),
        "eur_j_def_sobe": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].eur_por_jogador_mediano_sobe"),
        "eur_j_def_meio": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].eur_por_jogador_mediano_meio"),
        "eur_j_ata_sobe": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].eur_por_jogador_mediano_sobe"),
        "eur_j_ata_meio": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].eur_por_jogador_mediano_meio"),
        "auc_def": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=defesa].auc_sobe_x_resto"),
        "auc_meio": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=meio].auc_sobe_x_resto"),
        "auc_ataque": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=ataque].auc_sobe_x_resto"),
        "auc_total": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=total].auc_sobe_x_resto"),
    },
    crit=[
        KM("pergunta do título, por jogador: menor p entre os 4 setores (índice do setor), p >= 0,10", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto", papel="p", op=">=", lim=0.10),
        KM("valor por jogador maior na defesa, contando os 4 setores (q < 0,05; descrição sem selo próprio)", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].q_bh_sobe_x_meio", op="<", lim=0.05, decide=False),
        KM("valor por jogador maior no ataque, contando os 4 setores (q < 0,05; descrição sem selo próprio)", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].q_bh_sobe_x_meio", op="<", lim=0.05, decide=False),
    ],
    regra_propria=[("sem_sinal", {0: True})],
    regra={"regua": "régua final de 15/09, sem sinal: p >= 0,10 na pergunta do título",
           "pergunta": "o setor diz algo além do valor do elenco? — lida pela partição por jogador (declaracoes_novas.din04_din05_por_jogador)",
           "sem_sinal_se": "ponderado_por_jogador.particao.menor_p.p_bruto >= 0,10",
           "descreve": "o valor por jogador maior na defesa e no ataque (q 0,0024) vai no mesmo lado da DIN-01 e não vira selo próprio: não contar o mesmo achado duas vezes nem sugerir 'invista na defesa'",
           "proibido": ["pôr no mesmo número AUC sobe x resto e sobe x meio", "'custa'", "'o setor não diz nada que o total não diga' (a DIN-06 não deixa ordenar)", "'é o mesmo dinheiro' e 'é o valor do elenco inteiro visto por setor' (equivalência afirmada como fato)", "'invista na defesa'"]},
    p=P("etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto", 0.26), ceticos=True,
    rev="reconferência 14/09: ressalva e número sem afirmar equivalência que a DIN-06 não deixa afirmar; q derivado dos p gravados. Conserto final 14/09: o título ('é o mesmo dinheiro') e a frase ('é o valor do elenco inteiro visto por setor') ainda afirmavam a equivalência; viraram 'não se viu'",
    rev15="rodada sem dinheiro (15/09): FRACO → SEM SINAL. A pergunta do título ('algo além do valor do elenco') passa a ser lida pela partição por jogador (decisão do coordenador): menor p 0,26 nos 4 setores, 'não se viu'. O valor por jogador maior na defesa e no ataque (q 0,0024) fica como descrição no mesmo lado da DIN-01, sem selo próprio. O critério antigo lia a DIN-04 fraca por causa do desconto, que saiu",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 · partição por jogador (`etapa_1.valor_por_setor.ponderado_por_jogador.particao`): índice do setor (fatia do valor ÷ fatia de jogadores), Mann-Whitney sobe x meio no posto do ano, p goleiro 0,87 · defesa 0,26 · meio-campo 0,99 · ataque 0,47; q BH 0,99 / 0,94 / 0,99 / 0,94 · valor por jogador (`ponderado_por_jogador.setores`), medianas sobe / meio em mil euros: goleiro 170 / 109, defesa 428 / 250, meio-campo 396 / 261, ataque 513 / 285; q BH sobe x meio 0,19 / 0,0024 / 0,051 / 0,0024 · valor mediano do setor sobe / meio: defesa 7,9 / 3,9 mi €; meio-campo 5,8 / 4,7; ataque 7,2 / 4,8 · AUC sobe x resto goleiro / defesa / meio / ataque 0,64 / 0,84 / 0,75 / 0,78 · `etapa_1.valor_por_setor.setores` · onde ver na aba: etapa 1 · faixa de pontos: não medido",
))

C.append(conc(
    id="DIN-06", tema="dinheiro_e_elenco", etapa="etapa_1", selo="nao_da_para_afirmar", declarada=False,
    titulo="O valor da defesa sozinho prevê melhor que o elenco inteiro?",
    frase="O valor da defesa acerta {auc_setor} de cada 100 pares, contra {auc_total} do elenco inteiro, e a defesa foi escolhida justamente por ter saído na frente entre {entre} setores.",
    numero="A diferença pode ir de {ic_lo_pares} pares a menos até {ic_hi_pares} a mais, em cada 100.",
    ressalva="Não quer dizer que olhar só a defesa basta, nem que os dois são equivalentes: o estudo não tem tamanho para ordenar os dois.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "auc_setor": G("pares_numero", "etapa_1.valor_por_setor.melhor_setor_contra_total.auc_setor"),
        "auc_total": G("pares_numero", "etapa_1.valor_por_setor.melhor_setor_contra_total.auc_total"),
        "ic_lo_pares": G("pares_em_100_absoluto", "etapa_1.valor_por_setor.melhor_setor_contra_total.ic95_lo"),
        "ic_hi_pares": G("pares_em_100_absoluto", "etapa_1.valor_por_setor.melhor_setor_contra_total.ic95_hi"),
        "entre": G("inteiro", "etapa_1.valor_por_setor.melhor_setor_contra_total.entre"),
    },
    crit=[
        K("a pergunta é qual dos dois é maior (caso a da régua)", None, "sim", True),
        K("o intervalo da diferença cruza zero", "etapa_1.valor_por_setor.melhor_setor_contra_total.ic_cruza_zero", "de −0,089 a +0,119", True),
        K("setor escolhido depois de olhar (descrição)", "etapa_1.valor_por_setor.melhor_setor_contra_total.escolhido_depois_de_olhar", "sim, entre 4", True, decide=False),
    ],
    regra={"nao_da_para_afirmar_se": "melhor_setor_contra_total.ic_cruza_zero = true", "campo_que_decide": "melhor_setor_contra_total.ic_cruza_zero"},
    p=P(None, None), ceticos=True, rev="reconferência 14/09: universo e critérios; p_principal nulo (pergunta de intervalo)", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="ORI-01", tema="dinheiro_e_elenco", etapa="conclusoes_base", selo="fraco", declarada=False,
    titulo="Quem acabou de cair da Série A subiu mais e não caiu",
    frase="De {ano_ini_ori} a {ano_fim}, quem tinha acabado de cair da Série A subiu {sub_A} vezes em {n_A} ({pct_sub_A}%) e {cai_A_extenso}. Quem já estava na B subiu {sub_B} em {n_B} ({pct_sub_B}%) e caiu {cai_B}. É um sinal {selo}: a comparação da origem foi montada depois de olhar os números, e não há lista de onde ela saia para comparar com a sorte.",
    numero="Só existe valor de elenco de {ano_ini} a {ano_fim}; nesse período estão {n_A_valor} dos {n_A} casos, e eles tinham tipicamente o {posto_mediano_A}º elenco mais valioso do ano.",
    ressalva="Não quer dizer que cair da A ajuda a subir: esses clubes chegam com um dos elencos mais valiosos do ano (DIN-01), e o estudo não separa as duas coisas. Que ninguém caiu vale sem exceção para os {n_A} casos (e os {n_A_sens} contando {ano_ini_sens}), mas não é regra.",
    universo="{n_origem} clube-temporadas da Série B de {ano_ini_ori} a {ano_fim} ({n_A} vieram da Série A, {n_B} já estavam na B, {n_C} vieram da C), com a origem da base pública gravada; valor de elenco só nas {n_origem_valor} de {ano_ini} a {ano_fim}; {ano_parcial} fica fora de toda conta",
    lac={
        "ano_ini_ori": N("ano", "conclusoes_base.origem.anos_da_conta", "[0]"),
        "sub_A": N("inteiro", "conclusoes_base.origem.por_origem", "A.subiu"),
        "n_A": N("inteiro", "conclusoes_base.origem.por_origem", "A.n"),
        "pct_sub_A": D("inteiro", "100 × sub_A / n_A", ["sub_A", "n_A"]),
        "cai_A_extenso": D("texto", "0 -> 'não caiu nenhuma vez'; senão 'caiu N vezes'", ["conclusoes_base.origem.por_origem"]),
        "sub_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.subiu"),
        "n_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.n"),
        "pct_sub_B": D("inteiro", "100 × sub_B / n_B", ["sub_B", "n_B"]),
        "cai_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.caiu"),
        "n_C": N("inteiro", "conclusoes_base.origem.por_origem", "C.n"),
        "n_origem": D("inteiro", "n_A + n_B + n_C", ["n_A", "n_B", "n_C"]),
        "n_origem_valor": N("inteiro", "conclusoes_base.origem.dinheiro", "soma de por_origem[].n (só descrição)"),
        "n_A_valor": N("inteiro", "conclusoes_base.origem.dinheiro", "por_origem.A.n (só descrição)"),
        "posto_mediano_A": N("inteiro", "conclusoes_base.origem.dinheiro", "por_origem.A.posto_mediano (só descrição)"),
        "n_A_sens": N("inteiro", "conclusoes_base.origem.sensibilidade", "A.n (anos_sensibilidade)"),
        "ano_ini_sens": N("ano", "conclusoes_base.origem.anos_sensibilidade", "[0]"),
    },
    val={"ano_ini_ori": "2019", "sub_A": "11", "n_A": "28", "pct_sub_A": "39", "cai_A_extenso": "não caiu nenhuma vez", "sub_B": "13", "n_B": "84", "pct_sub_B": "15", "cai_B": "23", "n_C": "28",
         "n_origem": "140", "n_origem_valor": "80", "n_A_valor": "16", "posto_mediano_A": "3", "n_A_sens": "32", "ano_ini_sens": "2018"},
    crit=[
        CONST("1. comparação declarada antes", False, papel="declarada", txt="não: a análise da origem foi declarada em 14/09, depois de olhar"),
        KM("A contra B, Fisher bilateral, p < 0,05 (queda ou subida)", "conclusoes_base.origem.fisher.A_x_B", papel="p", op="<", lim=0.05, ag="algum", sub=["p_queda", "p_subida"],
           v={"p_queda": 0.00081, "p_subida": 0.015}, txt="queda 0,0008; subida 0,015"),
        CONST("4. lista de onde a comparação saia, com mais achados que a sorte", False, papel="lista", txt="não há lista: é uma comparação só"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "comparacao": "A x B, Fisher bilateral, subida e queda (declaracoes_novas.origem)",
           "fraco_se": "p Fisher < 0,05 E comparação montada depois de olhar sem lista",
           "moderado_se": "impossível sem lista declarada",
           "ressalva": "sem desconto e sem receita: 'esses clubes chegam com um dos elencos mais valiosos do ano (DIN-01); o estudo não separa as duas coisas' (resposta b do dono)",
           "saiu_em_15_09": "a permutação dentro de ano × quartil de valor, a razão de verossimilhança e as subidas e quedas 'esperadas pelo valor' (eram desconto)",
           "pre_requisito": "bases.origem com sha256",
           "proibido": ["'de onde o clube vem pesa mais que qualquer número de jogo'", "'nunca cai' sem o universo", "juntar 2019-2025 e 2022-2025 sem dizer", "'é o elenco caro que vem junto' como fato",
                        "'é o que o elenco caro (ou o valor) já prevê' como fato", "'descontado o valor do elenco, não se viu a origem acrescentar nada' (o desconto saiu em 15/09)"]},
    p=P("conclusoes_base.origem.fisher.A_x_B.p_queda", 0.00081), ceticos=True,
    rev="reconferência 14/09: subidas esperadas '7 a 8' e quedas 'menos de 2 em qualquer conta (0,6 a 1,75)', com a conta da taxa do quartil sem os próprios clubes da A; raiz conclusoes_base.origem",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Saem do selo e do texto a permutação dentro de ano × quartil, a razão de verossimilhança e as quedas e subidas 'esperadas pelo valor'; do título sai 'descontado o valor do elenco, não se viu a origem acrescentar nada'. Fica a ressalva sem desconto: esses clubes chegam com um dos elencos mais valiosos do ano, e o estudo não separa as duas coisas. A regra_maquina ganha a linha 'escolhida depois, sem lista → fraco'",
    faixa_keep=True,
    rodape_ops=[("replace", "subidas esperadas 7,2 a 7,5 sem penalização", "subidas esperadas 7,2 a 7,5 sem penalização · **conta fora da amostra** (`cf_num/v_ori.py`, taxa do quartil de posto sem os próprios clubes da A): subidas 8,21 esperadas, quedas 0,71; faixas de 3 postos (não declaradas, só descrição): 11,5 e 0,40 sem os A, 7,7 e 0,33 com eles · a frase de 14/09 usava as especificações declaradas mais essas duas contas: subidas 7,2 a 8,2, quedas 0,57 a 1,75 · **rodada sem dinheiro de 15/09:** essas contas de 'esperado pelo valor' e a permutação deixaram de decidir o selo e de ir para a frase; ficam aqui como registro")],
))

C.append(conc(
    id="ORI-02", tema="dinheiro_e_elenco", etapa="conclusoes_base", selo="sem_sinal", declarada=False,
    titulo="Quem acabou de subir da Série C: não se viu diferença de quem já estava na B",
    frase="De {ano_ini_ori} a {ano_fim}, quem subiu da Série C subiu {sub_C} vezes em {n_C} ({pct_sub_C}%) e caiu {cai_C} em {n_C} ({pct_cai_C}%); quem já estava na B subiu {sub_B} em {n_B} ({pct_sub_B}%) e caiu {cai_B} ({pct_cai_B}%). Não se viu diferença, e {n_C} times só dariam boa chance a uma diferença grande: {frase_poder}.",
    numero="Subida: o acaso produziria a diferença em {p_sub_chance}; queda, em {p_cai_chance}.",
    ressalva="Não quer dizer que quem sobe da C está condenado a brigar contra a queda, nem que está protegido: não se ver não é não existir, e {pct_cai_C}% contra {pct_cai_B}% cabe no acaso.",
    universo="{n_origem} clube-temporadas da Série B de {ano_ini_ori} a {ano_fim} ({n_A} vieram da Série A, {n_B} já estavam na B, {n_C} vieram da C), com a origem da base pública gravada; {ano_parcial} fica fora de toda conta",
    lac={
        "ano_ini_ori": N("ano", "conclusoes_base.origem.anos_da_conta", "[0]"),
        "sub_C": N("inteiro", "conclusoes_base.origem.por_origem", "C.subiu"),
        "n_C": N("inteiro", "conclusoes_base.origem.por_origem", "C.n"),
        "cai_C": N("inteiro", "conclusoes_base.origem.por_origem", "C.caiu"),
        "pct_sub_C": D("inteiro", "100 × sub_C / n_C", ["sub_C", "n_C"]),
        "pct_cai_C": D("inteiro", "100 × cai_C / n_C", ["cai_C", "n_C"]),
        "sub_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.subiu"),
        "n_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.n"),
        "cai_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.caiu"),
        "pct_sub_B": D("inteiro", "100 × sub_B / n_B", ["sub_B", "n_B"]),
        "pct_cai_B": D("inteiro", "100 × cai_B / n_B", ["cai_B", "n_B"]),
        "n_A": N("inteiro", "conclusoes_base.origem.por_origem", "A.n"),
        "n_origem": D("inteiro", "n_A + n_B + n_C", ["n_A", "n_B", "n_C"]),
        "frase_poder": N("texto", "conclusoes_base.origem.poder", "menor subida de C detectada com poder >= limiar (0,70) contra a taxa de B: 'uma subida de X% contra Y% apareceria em N de cada 10 amostras, e uma queda mais baixa só se fosse perto de zero'"),
        "p_sub_chance": N("chance_em_100", "conclusoes_base.origem.fisher.C_x_B.p_subida"),
        "p_cai_chance": N("chance_em_100", "conclusoes_base.origem.fisher.C_x_B.p_queda"),
    },
    val={"ano_ini_ori": "2019", "sub_C": "4", "n_C": "28", "cai_C": "5", "pct_sub_C": "14", "pct_cai_C": "18", "sub_B": "13", "n_B": "84", "cai_B": "23", "pct_sub_B": "15", "pct_cai_B": "27", "n_A": "28", "n_origem": "140",
         "frase_poder": "uma subida de 40% contra 15% apareceria em 7 de cada 10 amostras, e uma queda mais baixa só se fosse perto de zero",
         "p_sub_chance": "100 de cada 100 tentativas", "p_cai_chance": "45 de cada 100 tentativas"},
    crit=[
        K("C contra B, Fisher bilateral, p >= 0,10 na subida e na queda", "conclusoes_base.origem.fisher.C_x_B", "subida 1,0; queda 0,45", True),
        K("tamanho detectável por simulação escrito na frase", "conclusoes_base.origem.poder", "40% contra 15% em 71% das amostras (28 × 84)", True, decide=False),
    ],
    regra={"sem_sinal_se": "Fisher C x B p >= 0,10 na subida E na queda", "obrigatorio": "tamanho detectável por simulação (poder, limiar 0,70)"},
    p=P("conclusoes_base.origem.fisher.C_x_B.p_subida", 1.0), ceticos=True,
    rev="reconferência 14/09: poder de 28 × 84 na frase ('7 de cada 10 amostras'), não o de 16 × 48; ressalva sem 'não existe'", faixa_keep=True,
    rodape_ops=[("replace", "poder 16 x 48: subida de 45% contra 17% em 54% das vezes; queda zero contra 25% em 54%", "poder 28 x 84 (a frase): subida de 40% contra 15% em 71% das amostras, 35% contra 15% em 51%; queda zero sempre detectada, queda de 10% em 43% · poder 16 x 48: subida de 45% contra 17% em 54% das vezes; queda zero contra 25% em 54%")],
))

C.append(conc(
    id="ELE-01", tema="dinheiro_e_elenco", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem cai roda muito mais gente",
    frase="Quem cai usa muito mais jogadores no ano: {usados_cai} em média, contra {usados_sobe} em quem sobe e {usados_meio} no meio da tabela, de {ano_ini} a {ano_fim}; o rastreamento físico conta a mesma história por outra fonte ({fis_cai} jogadores com minutos medidos, contra {fis_sobe} e {fis_meio}). É um sinal {selo}: na comparação declarada antes, quem cai contra quem sobe, a sorte produziria essa diferença em {p_sc_chance}; contando os {n_familia_elenco} números do elenco, {frase_q_sc}; mas não houve como conferir por outro caminho, porque não há escalação por rodada nem essa coluna em {periodo_antigo}.",
    numero="Contra o meio da tabela a diferença também aparece (o acaso a produziria em {p_cm_chance}); essa comparação foi escolhida depois de olhar, mas a lista do elenco nela tem mais achados do que a sorte, então pela regra do dono também seria moderada. Entre quem sobe e o meio não se viu diferença; com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    ressalva="Não quer dizer que rodar muito faz cair nem que elenco curto faz subir: time que está perdendo pode trocar de técnico e contratar no meio do ano, e o estudo não tem esse dado nem escalação por rodada para distinguir uma coisa da outra. As duas contagens andam juntas, então não são duas confirmações.",
    universo=UNIVERSOS["clube"],
    lac={
        "usados_cai": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_cai"),
        "usados_sobe": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_sobe"),
        "usados_meio": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_meio"),
        "fis_cai": G("dec1", "etapa_1.controle_n_atletas.media_cai"),
        "fis_sobe": G("dec1", "etapa_1.controle_n_atletas.media_sobe"),
        "fis_meio": G("dec1", "etapa_1.controle_n_atletas.media_meio"),
        "p_sc_chance": G("chance_em_1000", "etapa_2.linhas[indicador=atletas_usados].p_bruto_SC"),
        "frase_q_sc": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=atletas_usados].q_SC"]),
        "p_cm_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CM", "atletas_usados"),
    },
    val={"frase_q_sc": "é firme", "p_cm_chance": "1 de cada 1.000 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=atletas_usados].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=atletas_usados].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=atletas_usados].q_SC", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem escalação por rodada (1º turno) e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra quem cai, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem cai contra o meio (escolhida depois; descrição): lista do elenco acima da sorte", "etapa_3.por_familia.elenco.excesso.CM.bruto.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "comparacao_da_frase": "SC (sobe x cai), declarada no catálogo",
           "forte_se": "q_SC < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "moderado_se": "q_SC < 0,05 sem conferência testável, OU q_SC >= 0,05 com a lista do elenco SC acima da sorte", "fraco_se": "q_SC >= 0,05 E lista no nível da sorte", "sem_sinal_se": "p_bruto_SC >= 0,10",
           "parte_CM": "escolhida depois de olhar; pela regra do dono chegaria a moderado (lista do elenco CM 5 contra 0, p 0,0067); não muda o selo",
           "proibido": ["'quase certamente é consequência'", "'e não é o valor do elenco'", "'time que perde troca de técnico' como fato", "'continua entre times de valor parecido'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=atletas_usados].p_bruto_SC", 0.00019), ceticos=True,
    rev="reconferência 14/09: parte quem cai contra o meio reavaliada pela regra do dono (lista CM do elenco 5 contra 0, p 0,006; descontado 0,002): também moderada, sem efeito no selo",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre times de valor parecido' e 'não se viu o mesmo clube repetir'. Motivo do moderado: firme (q 0,0005) sem conferência testável; sem essa cláusula a máquina daria forte",
    faixa_keep=True,
    rodape_ops=[("replace", "cai x meio (escolhida depois de olhar, só descrição): Welch no posto p 0,001 (Mann-Whitney 0,0003), descontado o valor p 0,002, q 0,006 (líquido 0,011)",
                 "cai x meio (escolhida depois de olhar): Welch no posto p 0,001 (Mann-Whitney 0,0003), q 0,006; a lista do elenco nessa comparação tem 5 achados contra 0 do sorteio (p do excesso 0,006 em `r4_saida.json`, 0,0067 no dado novo), então pela regra do dono também seria moderada — não muda o selo")],
))

C.append(conc(
    id="ELE-02", tema="dinheiro_e_elenco", etapa="etapa_10", selo="moderado", declarada=True,
    titulo="Quem sobe repete mais o time-base — e isto não é critério de contratação",
    frase="O XI mais usado de quem sobe joga {share_sobe}% dos minutos, contra {share_meio}% no meio da tabela e {share_cai}% em quem cai, de {ano_ini} a {ano_fim}; {sobe_acima} dos {n_prom} que subiram ficaram acima do time típico do meio. É um sinal {selo}: contando os {n_familia_elenco} números do elenco, {frase_q}, e não houve como conferir por outro caminho, porque não há escalação por rodada.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que escalar sempre os mesmos onze faz subir: o estudo não tem escalação por rodada para testar a direção, e a etapa {etapa_redescrito} marca o número como consequência do resultado; a especificação proíbe usá-lo para contratar. A concentração de minutos diz a mesma coisa com outra conta, e não é segunda confirmação.",
    universo=UNIVERSOS["clube"],
    lac={
        "share_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_sobe"),
        "share_meio": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_meio"),
        "share_cai": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_cai"),
        "sobe_acima": N("inteiro", "etapa_2.por_clube", "promovidos com share_11 acima da mediana do meio"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=share_11].p_bruto_SM"),
        "frase_q": D("texto", "q_SM < 0,025: 'é firme'; 0,025 <= q_SM < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=share_11].q_SM"]),
        "etapa_redescrito": D("inteiro", "número de etapa_10.titulo_chave", ["etapa_10.titulo_chave"]),
    },
    val={"sobe_acima": "12", "frase_q": "é firme por pouco", "etapa_redescrito": "10"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=share_11].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=share_11].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=share_11].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem escalação por rodada (etapa_7.nao_testaveis) e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra o meio, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável (firme por pouco com nenhuma conferência também é moderado)",
           "nao_sobe_para_forte_porque": "o teste do primeiro turno é impossível (etapa_7.nao_testaveis) e a coluna não existe em 2018-2021: nenhuma conferência testável",
           "marca_obrigatoria": "consequência do resultado (etapa_10, lista fixa do ranking_gaps), nunca critério de encaixe",
           "fronteira_da_lista": "a lista do elenco SM está na fronteira (p do excesso 0,0502 no dado novo): não se afirma excesso, e o selo não depende disso",
           "proibido": ["'não se viu o mesmo clube repetir, então não pode ser usado como traço' (o ano seguinte saiu dos critérios em 15/09)", "'continua entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=share_11].p_bruto_SM", 0.00452), ceticos=True,
    rev="reconferência 14/09: ressalva do spec igual à do documento ('não se viu o mesmo clube repetir, então não pode ser usado como traço')",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'não se viu o mesmo clube repetir o padrão no ano seguinte'; o motivo passa a ser 'firme por pouco (q 0,038) sem conferência testável'. A marca de consequência (etapa 10) continua",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="ELE-03", tema="dinheiro_e_elenco", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe dá mais minutos a estrangeiros",
    frase="{est_sobe}% dos minutos, contra {est_meio}% no meio da tabela, de {ano_ini} a {ano_fim}. É um sinal {selo}: contando os {n_familia_elenco} números do elenco, {frase_q}, e não houve como conferir por outro caminho: não há essa coluna em {periodo_antigo} nem versão por jogo.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que estrangeiro ajuda nem que atrapalha. Elenco valioso tende a dar mais minutos a estrangeiro; o estudo não separa as duas coisas. Varia muito de ano para ano: {ano_contra}, e {sobe_zero} dos {n_prom} que subiram não deram minuto nenhum a estrangeiro.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "est_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=min_estrangeiros].m_sobe"),
        "est_meio": G("pct_inteiro", "etapa_2.linhas[indicador=min_estrangeiros].m_meio"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM"),
        "frase_q": D("texto", "q_SM < 0,025: 'é firme'; 0,025 <= q_SM < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=min_estrangeiros].q_SM"]),
        "ano_contra": N("texto", "etapa_2.linhas[].media_por_ano", "min_estrangeiros: anos com média de sobe abaixo da de meio, 'em ANO quem subiu usou menos que o meio (X% contra Y%)'"),
        "sobe_zero": N("inteiro", "etapa_2.por_clube", "promovidos com min_estrangeiros = 0"),
    },
    val={"frase_q": "é firme por pouco", "ano_contra": "em 2023 quem subiu usou menos que o meio (0,5% contra 1,2%)", "sobe_zero": "3"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=min_estrangeiros].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=min_estrangeiros].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem versão por jogo e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra o meio, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável",
           "ressalva": "sem desconto e sem receita (resposta b do dono): 'elenco valioso tende a dar mais minutos a estrangeiro; o estudo não separa as duas coisas' — medido na parte 1: ρ +0,36 com o posto de valor; a medida por coluna vai para etapa_2.andam_com_o_valor",
           "saiu_em_15_09": "o critério 'desconto do dinheiro' (porta C) e, do título, '— mas estrangeiro anda junto com elenco caro' como desconto",
           "proibido": ["'a média é puxada por poucos clubes'", "'orçamento'", "'comparando times de valor de elenco parecido'", "'contrate estrangeiro'"]},
    p=P("etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM", 0.00826), ceticos=True,
    rev="reconferência 14/09: universo e critérios",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só pelo desconto do valor (p líquido 0,076). Pela régua final: firme por pouco (p 0,008, q 0,038) sem conferência testável. Sai do título '— mas estrangeiro anda junto com elenco caro'; entra a ressalva sem desconto e sem receita (resposta b do dono)",
    faixa_keep=True, rodape_ops=[("append", " · rodada sem dinheiro de 15/09: na parte 1, o posto de minutos de estrangeiros anda com o posto de valor do elenco (ρ +0,36); é o que a ressalva descreve, sem descontar")],
))

C.append(conc(
    id="ELE-04", tema="dinheiro_e_elenco", etapa="etapa_1", selo="sem_sinal", declarada=True,
    titulo="Goleiro caro: não se viu diferença entre quem sobe e o meio da tabela",
    frase="O valor do goleiro acerta {auc_gol} de cada 100 pares, perto dos {auc_acaso} do acaso; o estudo só enxergaria uma diferença de uns {auc_detectavel} em 100. Contra quem cai, o goleiro de quem sobe vale mais, no mesmo lado do elenco inteiro (DIN-01); essa comparação não é a do título.",
    numero="Na fatia do elenco, {fatia_sobe}% contra {fatia_meio}%: o acaso produziria isso em {p_fatia_chance}.",
    ressalva="Não quer dizer que goleiro não importa: uma diferença menor pode existir, e valor de mercado mede mal goleiro.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "auc_gol": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=goleiro].auc_sobe_x_meio"),
        "auc_acaso": D("inteiro", "AUC nula = 0,5 → 50", []),
        "auc_detectavel": D("pares_numero", "Phi(etapa_0.poder.d_minimo_16x48 / raiz de 2)", ["etapa_0.poder.d_minimo_16x48"]),
        "fatia_sobe": G("dec1", "etapa_1.valor_por_setor.setores[setor=goleiro].pct_do_elenco_mediano_sobe"),
        "fatia_meio": G("dec1", "etapa_1.valor_por_setor.setores[setor=goleiro].pct_do_elenco_mediano_meio"),
        "p_fatia_chance": G("chance_em_100", "etapa_1.valor_por_setor.particao.setores[setor=goleiro].p_bruto"),
    },
    val={"auc_acaso": "50", "auc_detectavel": "72"},
    crit=[
        K("valor do goleiro, quem sobe contra o meio, p >= 0,10", "etapa_1.valor_por_setor.setores[setor=goleiro].p_sobe_x_meio", "0,24", True),
        K("fatia do goleiro, p >= 0,10", "etapa_1.valor_por_setor.particao.setores[setor=goleiro].p_bruto", "0,83", True),
    ],
    regra={"sem_sinal_se": "setores[goleiro].p_sobe_x_meio >= 0,10 E particao.setores[goleiro].p_bruto >= 0,10", "obrigatorio": "tamanho detectável (etapa_0.poder)", "proibido": ["'não separa' como fato", "'é só o elenco mais caro no geral' (ausência afirmada)", "'descontado o valor do elenco inteiro' (o desconto saiu em 15/09)"]},
    p=P("etapa_1.valor_por_setor.setores[setor=goleiro].p_sobe_x_meio", 0.241), ceticos=True,
    rev="reconferência 14/09: 'é só o elenco mais caro no geral' virou 'descontado o valor do elenco inteiro, não se viu diferença'",
    rev15="rodada sem dinheiro (15/09): segue SEM SINAL. Sai 'descontado o valor do elenco inteiro, não se viu diferença' (era desconto): contra quem cai o goleiro vale mais, no mesmo lado do elenco inteiro, e essa não é a comparação do título", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="ELE-05", tema="dinheiro_e_elenco", etapa="etapa_2", selo="sem_sinal", declarada=True,
    titulo="Tamanho do plantel e idade do XI: não se viu diferença",
    frase="{plantel_sobe} inscritos em quem sobe contra {plantel_meio} no meio; {idade_sobe} contra {idade_meio} anos no time-base, de {ano_ini} a {ano_fim}. Com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="Plantel: o acaso produziria a diferença em {p_plantel_chance}. Idade do XI: em {p_idade_chance}.",
    ressalva="Não quer dizer que plantel e idade não importam: se existe diferença, é pequena demais para este número de times mostrar.",
    tecnico="tamanho detectável {d_min}",
    universo=UNIVERSOS["clube"],
    lac={
        "plantel_sobe": G("inteiro", "etapa_2.linhas[indicador=plantel].m_sobe"),
        "plantel_meio": G("inteiro", "etapa_2.linhas[indicador=plantel].m_meio"),
        "idade_sobe": G("dec1", "etapa_2.linhas[indicador=idade_11].m_sobe"),
        "idade_meio": G("dec1", "etapa_2.linhas[indicador=idade_11].m_meio"),
        "p_plantel_chance": G("chance_em_100", "etapa_2.linhas[indicador=plantel].p_bruto_SM"),
        "p_idade_chance": G("chance_em_100", "etapa_2.linhas[indicador=idade_11].p_bruto_SM"),
        "d_min": G("dec2", "etapa_0.poder.d_minimo_16x48"),
    },
    crit=[K("plantel e idade do XI, quem sobe contra o meio, p >= 0,10 nas duas", "etapa_2.linhas[indicador=plantel].p_bruto_SM", "0,42 e 0,63", True)],
    regra={"sem_sinal_se": "p_bruto_SM >= 0,10 nas duas linhas", "proibido": ["'não separam ninguém'"]},
    p=P("etapa_2.linhas[indicador=plantel].p_bruto_SM", 0.42), ceticos=True, rev="reconferência 14/09: universo e critérios", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="ELE-06", tema="dinheiro_e_elenco", etapa="etapa_6", selo="sem_sinal", declarada=False, regime="propria: contas da mesma pergunta",
    titulo="Não se viu a colocação de um ano repetir no ano seguinte, no limite",
    frase="Entre os clubes que ficaram na Série B ({n_pares_pos} pares de anos seguidos), dos {n_5_8} que terminaram entre o {faixa_a_ini}º e o {faixa_a_fim}º, {sub_5_8} subiram e {cai_5_8} caíram no ano seguinte; dos {n_13_16} entre o {faixa_b_ini}º e o {faixa_b_fim}º, {sub_13_16} subiram e {cai_13_16} caíram. Não se viu a posição de um ano andar com a do seguinte: o acaso produziria a relação em {p_posicao_chance}, no limite. Ela apareceu nos pares que começam de {per1} e não se viu nos que começam de {per2}.",
    numero="O aproveitamento vai para o mesmo lado e passa do corte ({p_aprov_chance}). As duas contas vão para o mesmo lado, nenhuma foi declarada antes de olhar e os dois períodos discordam: vale o selo mais fraco, sem sinal.",
    ressalva="Não quer dizer que a campanha anterior não conta: quem terminou embaixo caiu mais ({cai_13_16} contra {cai_5_8}), só que, com {n_13_16} contra {n_5_8}, não se viu diferença além do acaso. Quem subiu ou caiu sai da Série B e não entra na conta.",
    universo="{n_pares_pos} pares de anos seguidos de clubes que ficaram na Série B, de {t_ini}→{t_ini1} a {t_fim}→{t_fim1} (das {n_antigo} clube-temporadas de {periodo_antigo} e das {n_clube_temporadas} de {ano_ini} a {ano_fim}); {ano_parcial} fica fora de toda conta",
    lac={
        "n_pares_pos": N("inteiro", "etapa_6.colocacao.n_pares"),
        "n_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "n_5_8"),
        "faixa_a_ini": D("inteiro", "bloco declarado em declaracoes_novas.colocacao_t_t1 (5-8): início", []),
        "faixa_a_fim": D("inteiro", "bloco declarado (5-8): fim", []),
        "sub_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "sub_5_8"),
        "cai_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "cai_5_8"),
        "n_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "n_13_16"),
        "faixa_b_ini": D("inteiro", "bloco declarado (13-16): início", []),
        "faixa_b_fim": D("inteiro", "bloco declarado (13-16): fim", []),
        "sub_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "sub_13_16"),
        "cai_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "cai_13_16"),
        "p_posicao_chance": N("chance_em_100", "etapa_6.colocacao.p_posicao"),
        "per1": N("texto", "etapa_6.colocacao.por_periodo", "t[0] 'A a B' do primeiro período"),
        "per2": N("texto", "etapa_6.colocacao.por_periodo", "t[1] 'A a B' do segundo período"),
        "p_aprov_chance": N("chance_em_100", "etapa_6.colocacao.p_aproveitamento"),
        "t_ini": D("ano", "primeiro ano t dos pares", ["etapa_6.colocacao.por_periodo"]),
        "t_ini1": D("ano", "t_ini + 1", ["t_ini"]),
        "t_fim": D("ano", "último ano t dos pares", ["etapa_6.colocacao.por_periodo"]),
        "t_fim1": D("ano", "t_fim + 1", ["t_fim"]),
    },
    val={"n_pares_pos": "84", "n_5_8": "28", "faixa_a_ini": "5", "faixa_a_fim": "8", "sub_5_8": "6", "cai_5_8": "6", "n_13_16": "28", "faixa_b_ini": "13", "faixa_b_fim": "16", "sub_13_16": "2", "cai_13_16": "11",
         "p_posicao_chance": "6 de cada 100 tentativas", "per1": "2018 a 2020", "per2": "2021 a 2024", "p_aprov_chance": "2 de cada 100 tentativas",
         "t_ini": "2018", "t_ini1": "2019", "t_fim": "2024", "t_fim1": "2025"},
    crit=[
        KM("conta do título: posição em t contra t+1, p < 0,05", "etapa_6.colocacao.p_posicao", papel="p", op="<", lim=0.05, v=0.0642, txt="0,064 (zona cinzenta)"),
        KM("outra conta da mesma pergunta: aproveitamento em t contra t+1, p < 0,05", "etapa_6.colocacao.p_aproveitamento", papel="outra", op="<", lim=0.05, v=0.025),
        CONST("1. alguma das duas contas declarada antes", False, papel="declarada", txt="não"),
        KM("os dois períodos concordam (posição com p < 0,05 nos dois)", "etapa_6.colocacao.por_periodo", papel="conf", op="<", lim=0.05, ag="todos", sub="p_posicao", v=[0.025, 0.60], txt="2018-2020 p 0,025; 2021-2024 p 0,60"),
    ],
    regra_propria=[("sem_sinal", {0: False, 1: True, 2: False, 3: False})],
    regra={"regua": "régua final de 15/09, regra própria das contas da mesma pergunta (o assunto é a repetição do clube: fica, com selo)",
           "sem_sinal_se": "p_posicao >= 0,05 (zona cinzenta, conta do título) E o aproveitamento passa E nenhuma das duas foi declarada antes E os períodos discordam: vale o selo mais fraco entre fraco (aproveitamento, escolhida depois e sem lista) e sem sinal (posição)",
           "fraco_se": "a conta declarada antes der fraco (não há conta declarada antes)",
           "saiu_em_15_09": "o aproveitamento descontado o valor nos 36 pares (não decidia o selo) e a frase do valor do elenco que se repete",
           "proibido": ["'ajuda pouco' (causa)", "'não separa isso do acaso'", "'e não de 2021 a 2025' (p 0,60: 'não se viu')", "ρ na frase de reunião", "'some quando se desconta o dinheiro'"]},
    p=P("etapa_6.colocacao.p_posicao", 0.0642), ceticos=True,
    rev="reconferência 14/09: fraco → sem sinal. O aproveitamento descontado o dinheiro some (parcial 0,24, p 0,16, nos 36 pares; resíduo do valor nas 80 temporadas, ρ 0,10, p 0,55); a posição, conta do título, fica no limite (0,064); nenhuma das duas foi declarada antes e vale a mais fraca",
    rev15="rodada sem dinheiro (15/09): segue SEM SINAL. O assunto é a repetição da colocação do clube, então a conclusão fica com o selo. Saem o aproveitamento descontado o valor e a frase 'o valor do elenco se repete com força'; decide a regra das contas da mesma pergunta (posição 0,064, aproveitamento 0,025, nenhuma declarada, períodos discordam)",
    faixa_keep=True,
    rodape_ops=[("replace", "selo pela zona cinzenta, com sinal no aproveitamento e períodos que discordam", "**selo: SEM SINAL** (reconferência de 14/09, antes FRACO) · a posição é a conta do título e fica no limite; o aproveitamento passa; nenhuma das duas foi declarada antes e os períodos discordam: vale a mais fraca · na conta de 14/09 entrava também o aproveitamento descontado o valor nos 36 pares (0,16, `cf_num/v_ele06.py`); saiu da régua em 15/09 e não mudava o selo")],
))

C.append(conc(
    id="ELE-07", tema="dinheiro_e_elenco", etapa="etapa_2", selo="fraco", declarada=False,
    titulo="Manter a base e trazer menos reforços: diferença pequena, com {n_sobe_base} times que subiram",
    frase="De {ano_ini_base} a {ano_fim}, entre os {n_base} clubes que já estavam na Série B no ano anterior ({n_sobe_base} subiram, {n_meio_base} ficaram no meio, {n_cai_base} caíram), quem subiu manteve {ficou_sobe}% do elenco do ano anterior, contra {ficou_meio}% no meio da tabela; quem caiu trouxe {novos_cai} jogadores novos no ano, contra {novos_sobe} em quem subiu. É um sinal {selo}: as duas medidas foram montadas depois de olhar, nenhuma das {n_testes_base} comparações passa na conta dos muitos testes, e uma lista de duas medidas não tem como ficar acima da sorte.",
    numero="Parte que ficou, quem sobe contra o meio: o acaso produziria a diferença em {p_ficou_chance}. Novos, quem sobe contra quem cai: em {p_novos_chance}.",
    ressalva="Não quer dizer 'mantenha a base e você sobe', nem 'reformular faz cair'. A contagem de novos é do ano inteiro e inclui quem chegou no meio da temporada: time que está perdendo contrata mais, então pode ser consequência. Para quem chega da Série A ou da C isso não foi medido: o dado não existe.",
    universo="{n_base} clubes de {ano_ini_base} a {ano_fim} que já estavam na Série B no ano anterior ({n_sobe_base} subiram, {n_meio_base} ficaram no meio, {n_cai_base} caíram); {ano_parcial} fica fora de toda conta",
    lac={
        "n_sobe_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_sobe"),
        "ano_ini_base": N("ano", "etapa_2.elenco_base.anos", "[0]"),
        "n_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n"),
        "n_meio_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_meio"),
        "n_cai_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_cai"),
        "ficou_sobe": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: mediana_sobe"),
        "ficou_meio": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: mediana_meio"),
        "novos_cai": N("inteiro", "etapa_2.elenco_base.linhas", "novos: mediana_cai"),
        "novos_sobe": N("inteiro", "etapa_2.elenco_base.linhas", "novos: mediana_sobe"),
        "n_testes_base": N("inteiro", "etapa_2.elenco_base.bh_testes"),
        "p_ficou_chance": N("chance_em_100", "etapa_2.elenco_base.linhas", "pctFicou: p_bruto_SM"),
        "p_novos_chance": N("chance_em_100", "etapa_2.elenco_base.linhas", "novos: p_bruto_SC"),
    },
    val={"n_sobe_base": "6", "ano_ini_base": "2023", "n_base": "36", "n_meio_base": "22", "n_cai_base": "8", "ficou_sobe": "44", "ficou_meio": "31", "novos_cai": "42", "novos_sobe": "30", "n_testes_base": "6",
         "p_ficou_chance": "4 de cada 100 tentativas", "p_novos_chance": "3 de cada 100 tentativas"},
    crit=[
        CONST("1. comparações declaradas antes", False, papel="declarada", txt="não: as duas medidas e as comparações foram montadas depois de olhar"),
        KM("p bruto < 0,05 em alguma das duas (parte que ficou, quem sobe contra o meio; novos, quem sobe contra quem cai)", "etapa_2.elenco_base.linhas", papel="p", op="<", lim=0.05, ag="algum", sub=["p_bruto_SM", "p_bruto_SC"],
           v={"pctFicou": 0.0416, "novos": 0.028}, txt="parte que ficou 0,042; novos 0,028"),
        CONST("4. lista acima da sorte (regra do dono)", False, papel="lista", txt="não dá: duas medidas não formam lista"),
        KM("conta dos 6 testes (q < 0,05; descrição)", "etapa_2.elenco_base.linhas", op="<", lim=0.05, ag="algum", sub=["q_SM", "q_SC", "q_CM"], v=0.083, txt="menor q 0,083", decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "algum p bruto < 0,05 E comparação montada depois de olhar sem lista acima da sorte", "sem_sinal_se": "todo p bruto >= 0,10",
           "familia": "elenco_base (2 colunas × comparações SM, SC, CM = 6 testes de BH), fora do catálogo e fora das 293",
           "saiu_em_15_09": "os p descontados do valor do elenco (0,045 a 0,089 conforme a conta; não decidiam o selo)",
           "proibido": ["'resiste ao dinheiro'", "'não vale para quem chega da A ou da C' (não medido)"]},
    p=P("etapa_2.elenco_base.linhas[indicador=pctFicou].p_bruto_SM", 0.0416), ceticos=True,
    rev="reconferência 14/09: o desconto pela conta da casa (posto do ano sobre o percentil de valor) dá 0,045 e não 0,050; o 0,050 e o 0,089 vêm de outras duas contas (`v578.py`); o selo segue fraco pela regra da comparação montada depois de olhar e pelos 6 testes",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Saem os p descontados do valor do elenco da frase e dos critérios; decide a regra da comparação escolhida depois de olhar (sem lista)",
    faixa_keep=True,
    rodape_ops=[
        ("replace", "descontado o dinheiro 0,050 (resíduo do posto) a 0,089 (resíduo do valor cru)", "na conta de 14/09, descontado o valor do elenco: 0,045 pela conta da casa, 0,050 e 0,089 por outras duas (`c78_colocacao_base.py`, `r13_varios.py`, `v578.py`); saiu da régua em 15/09 e não decidia o selo"),
        ("replace", "nenhuma das 6 comparações passa no BH", "nenhuma das 6 comparações (2 colunas × quem sobe contra o meio, quem sobe contra quem cai, quem cai contra o meio) passa no BH: menor q 0,083 (`r13_varios.py`)"),
        ("replace", "sobe x cai Welch 0,014, Mann-Whitney 0,024, descontado o dinheiro 0,055 a 0,096", "sobe x cai Welch 0,014, Mann-Whitney 0,024, posto 0,028")],
))

