# Tema 5: mercado e contratação (M)
from sp6_base import *

C = []

U_M1 = "atletas presentes no físico ({corte_jogos}+ jogos rastreados) e no técnico ({corte_min_tec}+ minutos) da Série B no mesmo par de anos, de {par_ini} a {par_fim}, com o físico ligado por nome e nascimento; sem {ano_parcial}"

C.append(conc(
    id="M1", tema="mercado_e_contratacao", etapa="etapa_11", selo="nao_da_para_afirmar", declarada=False,
    titulo="Quando o jogador troca de clube, o físico se repete mais que o técnico?",
    frase="Entre os jogadores que trocaram de clube ({n_mudou} atletas presentes nas duas bases no mesmo par de anos), não dá para afirmar: comparando cada atleta com os da mesma posição nas duas bases, o físico manteve a ordem em {fis_pos_mudou} e o técnico em {tec_pos_mudou}, e essa diferença pode ser sorte; comparando com os do mesmo setor, {fis_setor_mudou} contra {tec_setor_mudou}, também.",
    numero="Diferença por posição {dif_pos_mudou} (intervalo de {ic_pos_mudou}); por setor {dif_setor_mudou} ({ic_setor_mudou}). Quem ficou no clube tem conclusão própria (M7).",
    ressalva="Não quer dizer 'para contratar, use o físico': repetir não é render — não se viu o físico, no conjunto, separar quem sobe (FIS-09), nem a nota prever minutos (M2). Nem que o técnico não viaja. Entre os {pares_tec_mudou} pares do técnico de quem mudou, duelos ({rho_duelos_mudou}) e duelos aéreos ({rho_aereos_mudou}) mantiveram a ordem no nível do físico de quem mudou ou acima ({rho_fis_pos_mudou}, nos {pares_fis_mudou} pares do físico); são populações diferentes, então é descrição.",
    universo=U_M1,
    lac={
        "n_mudou": N("inteiro", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.n"),
        "fis_pos_mudou": N("dec2", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.rho_fisico"),
        "tec_pos_mudou": N("dec2", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.rho_tecnico"),
        "fis_setor_mudou": N("dec2", "etapa_11.comparacao_fisico_tecnico.mudou.setor.rho_fisico"),
        "tec_setor_mudou": N("dec2", "etapa_11.comparacao_fisico_tecnico.mudou.setor.rho_tecnico"),
        "dif_pos_mudou": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.dif", "dec2 com sinal"),
        "ic_pos_mudou": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.ic95", "'X a Y' com sinal; três casas se a ponta arredondar para zero"),
        "dif_setor_mudou": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.setor.dif", "dec2 com sinal"),
        "ic_setor_mudou": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.setor.ic95", "'X a Y' com sinal"),
        "pares_tec_mudou": V("inteiro", "etapa_11.tecnico.pares_mudou", "etapa_11.tecnico.pares_mudou", "o gravado hoje (233) inclui pares que terminam em 2026; sem 2026 são 176"),
        "rho_duelos_mudou": V("dec2", "etapa_11.tecnico.metricas[metrica=Duelos/90].rho_mudou", "etapa_11.tecnico.metricas[].rho_mudou", "gravado com 2026 (0,682); sem 2026 0,715"),
        "rho_aereos_mudou": V("dec2", "etapa_11.tecnico.metricas[metrica=Duelos aéreos/90].rho_mudou", "etapa_11.tecnico.metricas[].rho_mudou", "gravado com 2026 (0,625); sem 2026 0,642"),
        "rho_fis_pos_mudou": N("dec2", "etapa_11.fisico.por_posicao.rho_mudou"),
        "pares_fis_mudou": N("inteiro", "etapa_11.fisico.por_setor.n_mudou"),
        "corte_jogos": N("inteiro", "etapa_11.fisico.corte_jogos"),
        "corte_min_tec": N("inteiro", "etapa_11.tecnico.corte_minutos"),
        "par_ini": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.por_par_de_anos", "primeiro par 'A→B'"),
        "par_fim": N("texto", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.por_par_de_anos", "último par 'A→B'"),
    },
    val={"n_mudou": "155", "fis_pos_mudou": "0,57", "tec_pos_mudou": "0,45", "fis_setor_mudou": "0,65", "tec_setor_mudou": "0,56", "dif_pos_mudou": "+0,12", "ic_pos_mudou": "−0,004 a +0,21",
         "dif_setor_mudou": "+0,10", "ic_setor_mudou": "−0,01 a +0,17", "pares_tec_mudou": "176", "rho_duelos_mudou": "0,72", "rho_aereos_mudou": "0,64", "rho_fis_pos_mudou": "0,55",
         "pares_fis_mudou": "295", "corte_jogos": "8", "corte_min_tec": "900", "par_ini": "2022→2023", "par_fim": "2024→2025"},
    crit=[
        K("a pergunta é qual base se repete mais (caso a da régua)", None, "sim", True),
        K("intervalo da diferença por posição cruza zero", "etapa_11.comparacao_fisico_tecnico.mudou.posicao.ic95", "−0,004 a +0,21", True),
        K("intervalo da diferença por setor cruza zero", "etapa_11.comparacao_fisico_tecnico.mudou.setor.ic95", "−0,01 a +0,17", True),
        K("mesma régua nos dois lados, mesma população, sem 2026, chave nome + nascimento", "etapa_11.comparacao_fisico_tecnico", "sim (`r11_m1_chave_nascimento.py`)", True),
    ],
    regra={"nao_da_para_afirmar_se": "etapa_11.comparacao_fisico_tecnico.mudou.posicao.ic95 cruza zero OU mudou.setor.ic95 cruza zero",
           "fraco_se": "os dois intervalos acima de zero em quem mudou, comparação montada depois de olhar sem lista (teto fraco)",
           "pre_requisito": "etapa_11.tecnico com ano <= 2025; físico com chave nome + nascimento",
           "regua": "regua.repeticao_do_atleta (diferença entre bases = qual é maior)",
           "proibido": ["'para contratar, o físico do ano anterior é pista melhor que o técnico'", "comparar rho técnico por posição com rho físico só por ano", "'um número que se repete não é um número que ajuda a subir' (ausência afirmada)", "'duelo se repete quase como o físico'"]},
    p=P(None, None), ceticos=True,
    rev="reconferência 14/09: a comparação de quem ficou no clube, que tinha intervalo acima de zero e nenhum selo, virou a M7; ressalva 'repetir não é render' com 'não se viu'; os rho do técnico gravados hoje incluem 2026 e não servem",
    faixa_keep=True,
    rodape_ops=[("replace", "**ficou (128)**: posição 0,67 x 0,47, +0,20 (IC95 +0,11 a +0,32); setor 0,74 x 0,59, +0,15 (+0,07 a +0,25)", "quem ficou (128) tem selo próprio na M7")],
))

C.append(conc(
    id="M7", tema="mercado_e_contratacao", etapa="etapa_11", selo="fraco", declarada=False,
    titulo="Entre quem ficou no clube, o físico se repete mais que o técnico",
    frase="Entre os {n_ficou} jogadores que ficaram no clube e estão nas duas bases no mesmo par de anos, comparando cada atleta com os da mesma posição, o físico manteve a ordem em {fis_pos_ficou} e o técnico em {tec_pos_ficou}; comparando com os do mesmo setor, {fis_setor_ficou} contra {tec_setor_ficou}. Nas duas contas o intervalo da diferença fica todo acima de zero. É um sinal {selo}: a comparação entre as duas bases foi montada depois de olhar os números, não há lista de onde ela saia para comparar com a sorte, e a repetição por par de anos ainda não foi refeita com a chave nova do atleta.",
    numero="Diferença por posição {dif_pos_ficou} (intervalo de {ic_pos_ficou}); por setor {dif_setor_ficou} ({ic_setor_ficou}).",
    ressalva="Não quer dizer 'para contratar, use o físico': repetir não é render (FIS-09, M2), e quem ficou no clube não é quem se contrata. Entre quem trocou de clube não dá para afirmar a mesma coisa (M1).",
    universo=U_M1,
    lac={
        "n_ficou": N("inteiro", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.n"),
        "fis_pos_ficou": N("dec2", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.rho_fisico"),
        "tec_pos_ficou": N("dec2", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.rho_tecnico"),
        "fis_setor_ficou": N("dec2", "etapa_11.comparacao_fisico_tecnico.ficou.setor.rho_fisico"),
        "tec_setor_ficou": N("dec2", "etapa_11.comparacao_fisico_tecnico.ficou.setor.rho_tecnico"),
        "dif_pos_ficou": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.dif", "dec2 com sinal"),
        "ic_pos_ficou": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.ic95", "'X a Y' com sinal"),
        "dif_setor_ficou": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.setor.dif", "dec2 com sinal"),
        "ic_setor_ficou": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.setor.ic95", "'X a Y' com sinal"),
        "corte_jogos": N("inteiro", "etapa_11.fisico.corte_jogos"),
        "corte_min_tec": N("inteiro", "etapa_11.tecnico.corte_minutos"),
        "par_ini": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.por_par_de_anos", "primeiro par 'A→B'"),
        "par_fim": N("texto", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.por_par_de_anos", "último par 'A→B'"),
    },
    val={"n_ficou": "128", "fis_pos_ficou": "0,67", "tec_pos_ficou": "0,47", "fis_setor_ficou": "0,74", "tec_setor_ficou": "0,59", "dif_pos_ficou": "+0,20", "ic_pos_ficou": "+0,11 a +0,32",
         "dif_setor_ficou": "+0,15", "ic_setor_ficou": "+0,07 a +0,25", "corte_jogos": "8", "corte_min_tec": "900", "par_ini": "2022→2023", "par_fim": "2024→2025", "selo": "fraco"},
    crit=[
        K("pergunta de qual base se repete mais, com o intervalo da diferença inteiro acima de zero", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.ic95", "+0,11 a +0,32 e +0,07 a +0,25", True),
        K("comparação declarada antes", None, "não: montada depois de olhar (declaracoes_novas.etapa_11_mesma_regua)", False),
        K("lista acima da sorte (regra do dono)", None, "não há lista", False),
        K("repetição por par de anos com a chave nova do atleta", "etapa_11.comparacao_fisico_tecnico.ficou.posicao.por_par_de_anos", "não medida", False, decide=False),
    ],
    regra={"fraco_se": "ic95 da diferença (posição e setor) inteiro acima de zero E comparação montada depois de olhar sem lista (teto fraco)",
           "nao_da_para_afirmar_se": "algum dos dois ic95 cruza zero",
           "moderado_se": "impossível sem lista declarada (regra do dono)",
           "proibido": ["'para contratar, use o físico'", "juntar quem ficou e quem mudou"]},
    p=P(None, None), ceticos=False, nova_em="2026-09-14 (reconferência)",
    rev="nova na reconferência de 14/09: era um sinal sem selo dentro da M1 (intervalo acima de zero em quem ficou)",
    faixa_texto="<sub>faixa de pontos: não se aplica (repetição do atleta, sem faixa de clube)</sub>",
    rodape_texto="nova na reconferência de 14/09 (era sinal sem selo dentro da M1), sem cético próprio · mesma população da M1 (atletas nas duas bases no mesmo par de anos; o último par é 2024→2025, então sem 2026 por construção), físico ligado por nome E nascimento, bootstrap de 1.000, [99, 12] (`r11_m1_chave_nascimento.py`, `r11.log`) · **ficou (128)**: posição nos dois lados físico 0,667 x técnico 0,471, +0,196, IC95 +0,11 a +0,32 (0% das réplicas ≤ 0); setor 0,736 x 0,589, +0,147, IC95 +0,07 a +0,25 (0%) · por par de anos: não refeito com a chave nova · a comparação físico x técnico está em `declaracoes_novas.etapa_11_mesma_regua` com declarada_depois_de_olhar = true · onde ver na aba: etapa 11",
))

C.append(conc(
    id="M2", tema="mercado_e_contratacao", etapa="etapa_13", selo="sem_sinal", declarada=True,
    titulo="Não se viu a nota física de encaixe prever minutos nem permanência",
    frase="Entre as {n_chegadas} chegadas à Série B de {ano_ini_bt} a {ano_fim_bt} com nota, as que a nota aprovaria jogaram em média {min_rec} minutos, e as reprovadas {min_rep}; ficaram no clube {perm_rec}% contra {perm_rep}%. O estudo {frase_tamanho_bt}, e não viu nenhuma.",
    numero="Minutos: o acaso produziria a diferença em {p_min_chance}; permanência, em {p_perm_chance}.",
    ressalva="Não quer dizer que a nota é inútil, nem que ela escolhe mal: ela foi feita para aproximar o perfil físico de quem subiu, e o teste mede minutos e permanência, não contribuição para subir. Mas não pode ser apresentada como previsão de que o atleta vai jogar ou ficar.",
    tecnico="tamanho detectável {d_min}",
    universo="{n_chegadas} chegadas à Série B de {ano_ini_bt} a {ano_fim_bt} com nota física do ano anterior ({n_rec} aprovadas e {n_rep} reprovadas); {ano_parcial} fica fora de toda conta",
    lac={
        "n_chegadas": G("inteiro", "etapa_13.backtest.chegadas_com_nota"),
        "ano_ini_bt": D("ano", "primeiro ano de backtest.rotulo_da_definicao_ampla ('2023-2025' → 2023)", ["etapa_13.backtest.rotulo_da_definicao_ampla"]),
        "ano_fim_bt": G("ano", "etapa_13.backtest.ano_maximo_usado"),
        "min_rec": G("milhar", "etapa_13.backtest.min_medio_recomendados"),
        "min_rep": G("milhar", "etapa_13.backtest.min_medio_reprovados"),
        "perm_rec": G("dec1", "etapa_13.backtest.permanencia_recomendados_pct"),
        "perm_rep": G("dec1", "etapa_13.backtest.permanencia_reprovados_pct"),
        "frase_tamanho_bt": D("tamanho_em_palavras", "d_minimo_detectavel(n_recomendados, n_reprovados)", ["etapa_13.backtest.n_recomendados", "etapa_13.backtest.n_reprovados"]),
        "p_min_chance": G("chance_em_100", "etapa_13.backtest.p_minutos"),
        "p_perm_chance": G("chance_em_100", "etapa_13.backtest.p_permanencia"),
        "d_min": D("dec2", "d_minimo_detectavel(n_recomendados, n_reprovados)", ["etapa_13.backtest.n_recomendados", "etapa_13.backtest.n_reprovados"]),
        "n_rec": G("inteiro", "etapa_13.backtest.n_recomendados"),
        "n_rep": G("inteiro", "etapa_13.backtest.n_reprovados"),
    },
    val={"ano_ini_bt": "2023", "frase_tamanho_bt": "enxergaria até uma diferença pequena", "d_min": "0,28"},
    crit=[
        K("minutos, aprovadas contra reprovadas, p >= 0,10", "etapa_13.backtest.p_minutos", "0,71", True),
        K("permanência, p >= 0,10", "etapa_13.backtest.p_permanencia", "1,0", True),
    ],
    regra={"sem_sinal_se": "backtest.p_minutos >= 0,10 E backtest.p_permanencia >= 0,10", "proibido": ["'a nota não previu' (ausência afirmada)"]},
    p=P("etapa_13.backtest.p_minutos", 0.70935), ceticos=False, rev="reconferência 14/09: universo e critérios", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="M3", tema="mercado_e_contratacao", etapa="etapa_13", selo="nao_da_para_afirmar", declarada=True,
    titulo="A ordem da lista de candidatos é mérito medido?",
    frase="{n_empatados} dos {n_candidatos} candidatos com nota física empatam no teto ou no piso da margem, e a ordem dentro do empate não vem de medida nenhuma.",
    numero="",
    ressalva="Não quer dizer que os nomes do topo são ruins: a posição de um nome contra o vizinho, dentro do empate, não diz nada.",
    universo="os {n_candidatos} candidatos da lista com margem física calculada, de {n_pool} no conjunto (ficam de fora os goleiros, sem físico, e quem não tem margem)",
    lac={
        "n_empatados": N("inteiro", "etapa_13.empates_na_margem.n"),
        "n_candidatos": N("inteiro", "etapa_13.empates_na_margem.de"),
        "n_pool": G("inteiro", "etapa_13.n"),
    },
    val={"n_empatados": "213", "n_candidatos": "586"},
    crit=[
        K("a pergunta é se um nome está acima do vizinho (caso a da régua: qual dos dois é maior)", None, "sim", True),
        K("há empate na margem (|margem normalizada| >= 1,0)", "etapa_13.empates_na_margem.n", "213 de 586", True),
        K("há desempate medido gravado", None, "não", True),
    ],
    regra={"nao_da_para_afirmar_se": "empates_na_margem.n > 0 E não há desempate medido gravado: é o caso (a) da régua — 'este nome está acima do vizinho?' com diferença zero dentro do empate",
           "definicao": "n = candidatos com |nota_fisica.margem_normalizada| >= 1,0; de = candidatos com margem_normalizada não nula",
           "numero_da_tela": "sai de etapa_13.empates_na_margem; nunca digitado"},
    p=P(None, None), ceticos=False,
    rev="reconferência 14/09: o gerador de hoje dá 213 de 586 pela definição escrita (586 = candidatos com margem, de 603); o número não era do gerador velho, só não pode ser digitado; o selo passa a citar o caso (a) da régua",
    regra_da_etapa_14="frases com nomes da etapa 14 só do gerador novo: contagem por POSIÇÃO, 2.000 réplicas, default_rng([SEMENTE,14,i]) por proposta, recomendado = limite inferior do IC95 > 50%, empate_tecnico = IC95 contém 50%",
    faixa_keep=True,
    rodape_ops=[("replace", "A contagem de 12/09 (213 de 586, CONFERENCIA.md §5.4) é do gerador velho e não vai para a tela.",
                 "O gerador de hoje, pela mesma definição, dá 213 de 586 (`r13_varios.py`): 586 são os candidatos com margem calculada, de 603 no conjunto (ficam de fora 2 goleiros, sem setor físico, e 15 meias sem margem); é o mesmo número de CONFERENCIA.md §5.4. Não é número velho: só não pode ser digitado, a tela lê `etapa_13.empates_na_margem`.")],
))

C.append(conc(
    id="M4", tema="mercado_e_contratacao", etapa="etapa_13", selo="fraco", declarada=True,
    titulo="Na zaga e na lateral, o perfil físico que a nota de encaixe procura é fraco",
    frase="Contando o clube como um caso, de {ano_ini} a {ano_fim}, algumas medidas físicas da nota separam quem subiu de quem caiu na zaga e na lateral ({bruto_zaga} de {n_zaga} e {bruto_lateral} de {n_lateral} no número cru; descontado só o rodízio, {sobra_zaga} e {sobra_lateral}), mas nenhuma é firme contando as medidas do setor, e a lista de nenhum dos dois setores tem mais achados do que a sorte. É um sinal {selo}.",
    numero="Na zaga, a lista tem {bruto_zaga} achados quando a sorte daria {nulo_zaga}; na lateral, {bruto_lateral} contra {nulo_lateral}. O ataque tem conclusão própria (M8), e o meio-campo também (M5).",
    ressalva="Não quer dizer que físico não conta nesses setores, nem que a nota escolhe jogador ruim: com {n_sobe} clubes contra {n_cai}, só diferenças grandes aparecem. A nota mira quem sobe contra quem cai, não contra o meio. O ataque, que estava junto nesta conclusão, foi separado depois de olhar os números (M8); a família e a comparação foram declaradas antes.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos atletas do setor com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.p5_clube"),
        "bruto_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.p5_clube"),
        "n_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.testes"),
        "n_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.testes"),
        "sobra_zaga": G("zero_por_extenso", "sobecai_corrigido_por_clube.zaga.passam5_rod"),
        "sobra_lateral": G("zero_por_extenso", "sobecai_corrigido_por_clube.lateral.passam5_rod"),
        "nulo_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.excesso.SC.bruto.nulo_mediana"),
        "nulo_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.excesso.SC.bruto.nulo_mediana"),
    },
    crit=[
        CONST("1. família (medidas da nota por setor, clube como caso) e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim"),
        KM("alguma medida com p bruto < 0,05 por clube (zaga ou lateral)", "sobecai_corrigido_por_clube", papel="p", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="p5_clube"),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube", papel="rod", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="passam5_rod"),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube", papel="q", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="bh5_clube"),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube", papel="q_folga", op="<", lim=0.025, ag="min", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="itens.q_clube"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022, e o clube não se repete de um setor para o outro"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do setor acima da sorte (p do excesso < 0,05) na zaga ou na lateral", "sobecai_corrigido_por_clube", papel="lista", op="<", lim=0.05, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="excesso.SC.bruto.p_excesso"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum), por setor, nos dois setores juntos (os dois dão o mesmo selo)",
           "fraco_se": "algum p bruto < 0,05 por clube E nenhuma firme por clube E a lista do setor no nível da sorte (zaga e lateral)",
           "partida": "resposta d do dono (14/09, noite): M4 = zaga e lateral; o ataque virou a M8. A família e a comparação foram declaradas antes; a divisão do título foi decidida depois de olhar e fica registrada",
           "saiu_em_15_09": "o desconto do valor total (passam5_liq2) e 'fraco nos três setores' (ficou falso no ataque)",
           "proibido": ["'menos do que o acaso daria'", "selo único para os quatro setores", "'em boa parte o que o elenco caro já traz' (quantidade não medida, ausência afirmada)", "'descontados o valor do elenco e o rodízio'"]},
    p=P("sobecai_corrigido_por_clube.zaga.excesso.SC.bruto.p_excesso", 0.127), ceticos=True,
    rev="reconferência 14/09: 'o perfil é, em boa parte, o que o elenco caro já traz' virou 'descontados valor e rodízio, não se viu o perfil da nota distinguir quem sobe de quem cai', igual no documento e no spec; ponte com a FIS-10; o p5_clube gravado é a contagem crua (um nome só)",
    rev15="rodada sem dinheiro (15/09): segue FRACO, mas só zaga e lateral (resposta d do dono). Só com o rodízio: zaga 3 sobram e lista 0,127; lateral 2 sobram e lista 0,151; nenhuma firme por clube. O ataque saiu para a M8 (moderado): 'fraco nos três setores' ficava falso lá",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 (`prototipo_novo.json`, ainda não gravado no projeto) · medidas da nota por setor, clube como caso, quem sobe contra quem cai (16 × 16), média do clube ponderada por minuto · **zaga**: 34 medidas, 4 com p bruto < 0,05, nenhuma firme por clube (menor q 0,23), 3 continuam só com o rodízio (velocidade de pico das 5 melhores, corridas recebidas e corridas acima de alta velocidade), lista 4 contra 1 do sorteio, p do excesso 0,127 ([7, 17, 0]) · **lateral**: 35 medidas, 4 com p bruto < 0,05, nenhuma firme (menor q 0,24), 2 continuam só com o rodízio (velocidade de pico das 5 melhores e tempo até o sprint), lista 4 contra 1, p 0,151 ([7, 17, 1]) · na conta de 14/09, com o desconto do valor, não sobrava nenhuma nos três setores · a marca da etapa 13 (sobecai_corrigido_por_clube.<setor>.excesso.SC.bruto.lista) diz 'a lista não tem mais achados do que a sorte' na zaga e na lateral · onde ver na aba: etapa 13",
))

C.append(conc(
    id="M8", tema="mercado_e_contratacao", etapa="etapa_13", selo="moderado", declarada=False,
    titulo="No ataque, as medidas físicas da nota de encaixe separam quem subiu de quem caiu",
    frase="Contando o clube como um caso, de {ano_ini} a {ano_fim}, {bruto_ataque} das {n_ataque} medidas físicas da nota no ataque separam quem subiu de quem caiu no número cru; {firmes_ataque} são firmes contando as medidas do setor ({frase_folga_ataque}), e {sobra_ataque} continuam descontado só o rodízio. É um sinal {selo}, e não passa disso: o ataque foi separado da zaga e da lateral depois de olhar os números, e aí o teto é moderado, que a lista do ataque alcança; também não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="A lista do ataque tem {bruto_ataque} achados quando a sorte daria {nulo_ataque}, e continua com mais achados do que a sorte descontado só o rodízio.",
    ressalva="Não quer dizer 'contrate atacante que corre', nem que físico no ataque faz subir. Elenco valioso tende a ter isso; o estudo não separa as duas coisas. A separação entre o ataque e a zaga e a lateral (M4) foi feita depois de olhar os números; a família e a comparação foram declaradas antes. Vai para o mesmo lado da FIS-10, que conta as medidas do catálogo por time.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos atacantes com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.p5_clube"),
        "n_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.testes"),
        "firmes_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.bh5_clube"),
        "frase_folga_ataque": D("texto", "menor q_clube do setor < 0,025: 'a mais firme com folga'; senão 'todas por pouco'", ["sobecai_corrigido_por_clube.ataque.itens"]),
        "sobra_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.passam5_rod"),
        "nulo_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.excesso.SC.bruto.nulo_mediana"),
    },
    val={"frase_folga_ataque": "todas por pouco"},
    crit=[
        CONST("1. comparação do título escrita antes de olhar (a família das medidas da nota por setor, com o clube como caso, e a comparação quem sobe contra quem cai foram declaradas antes; a divisão do título, o ataque separado da M4, foi feita depois de olhar)", False, papel="declarada", txt="não: divisão do título escolhida depois de olhar, teto moderado"),
        KM("alguma medida com p bruto < 0,05 por clube", "sobecai_corrigido_por_clube.ataque.p5_clube", papel="p", op=">", lim=0),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube.ataque.passam5_rod", papel="rod", op=">", lim=0),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube.ataque.bh5_clube", papel="q", op=">", lim=0, decide=False),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube.ataque.itens", papel="q_folga", op="<", lim=0.025, ag="min", sub="q_clube", decide=False),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022", decide=False),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma", decide=False),
        KM("4. lista do ataque acima da sorte (p do excesso < 0,05)", "sobecai_corrigido_por_clube.ataque.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("a mesma lista descontado só o rodízio (descrição)", "sobecai_corrigido_por_clube.ataque.excesso.SC.rod.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "alguma medida com p bruto < 0,05 por clube E alguma continua só com o rodízio E a lista do ataque acima da sorte (p do excesso < 0,05)",
           "teto": "moderado: a divisão do título (o ataque separado da M4) foi escolhida depois de olhar; firmeza por clube e conferência ficam descritas e não decidem, então a máquina nunca promove a M8 a forte sem decisão (conserto de 15/09)",
           "partida": "resposta d do dono (14/09, noite): o ataque sai da M4 e vira conclusão própria (declaracoes_novas.conclusao_ataque_por_clube, id M8); família e comparação declaradas antes, título partido depois de olhar",
           "ressalva": "sem desconto e sem receita (resposta b do dono); a medida da relação com o valor por item vai em sobecai_corrigido_por_clube.ataque.itens[].rho_valor (descrição, nunca teto)",
           "proibido": ["'contrate atacante que corre'", "'o ataque decide a subida'", "juntar M8 e M5 numa conclusão só (mudaria o título depois de olhar)", "'descontados valor e rodízio'"]},
    # o p que decide o selo por clube é o bruto (p5_clube conta as medidas com p_clube < 0,05); o p só com o rodízio é outro papel
    p=P("sobecai_corrigido_por_clube.ataque.itens", min(x["p_clube"] for x in resolver("sobecai_corrigido_por_clube.ataque.itens")[1] if x.get("p_clube") is not None), agregacao="min", subcampo="p_clube"), ceticos=False, nova_em="2026-09-15 (partida da M4, resposta d do dono)",
    rev="nova na rodada sem dinheiro de 15/09: era o setor ataque dentro da M4",
    rev15="nova em 15/09 (resposta d do dono): MODERADO. Firme por clube (11 medidas com q < 0,05, a menor 0,043, todas por pouco), 13 continuam só com o rodízio (menor p 0,0007), lista 13 contra 1 (p 0,010 no bruto, 0,0089 só com o rodízio); sem conferência testável. Na M4 de 14/09 o ataque aparecia com 'nada sobra', pelo desconto do valor. Conserto de 15/09: teto moderado na máquina (a divisão do título foi escolhida depois de olhar), e o p_principal passa a ser o menor p bruto por clube",
    faixa_texto="<sub>**Vale também pela faixa de pontos?** não medido (conclusão partida da M4 em 15/09).</sub>",
    rodape_texto="nova na rodada sem dinheiro de 15/09 (`prototipo_novo.json`, ainda não gravado no projeto), partida da M4 pela resposta d do dono · medidas da nota no ataque, clube como caso, quem sobe contra quem cai (16 × 16), média do clube ponderada por minuto (110 atletas de quem subiu, 140 de quem caiu) · 35 medidas, 13 com p bruto < 0,05, 11 firmes por clube (q de 0,043 para cima: todas por pouco), 13 continuam só com o rodízio (menor p 0,00072) · lista 13 contra 1 do sorteio, p do excesso 0,010 no bruto e 0,0089 só com o rodízio ([7, 17, 3], 10.000 sorteios) · as que continuam: sprints e distância em alta intensidade com a bola do adversário, tempo de giro de 90°, distância e contagem de alta intensidade, sprint (distância e contagem), corrida em alta velocidade (distância e contagem), tempo até a corrida forte depois de mudar de direção, velocidade de pico, arrancada que vira sprint e metros por minuto com a bola do adversário · a relação de cada medida com o valor do elenco vai em `itens[].rho_valor` (spn_s ρ 0,38, p 0,0005), só descrição · onde ver na aba: etapa 13",
))

C.append(conc(
    id="M5", tema="mercado_e_contratacao", etapa="etapa_13", selo="moderado", declarada=True,
    titulo="No meio-campo, o perfil físico que a nota procura continua de pé",
    frase="No meio-campo, entre quem subiu e quem caiu de {ano_ini} a {ano_fim}, {bruto_meio} das {n_meio} medidas da nota separam no número cru, {firmes_meio} são firmes contando as medidas do setor, e {n_sobra_meio} continuam descontado só o rodízio ({nomes_sobra_meio}). É um sinal {selo}: não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="Lista do meio-campo: {bruto_meio} achados no número cru, quando a sorte daria {nulo_meio}; descontado só o rodízio, a lista já não tem mais achados que a sorte, e a regra usa a lista crua.",
    ressalva="Não quer dizer 'contrate meia que arranca e gira rápido', nem que o físico só conta no meio-campo: a diferença entre setores não foi testada. Contra o meio da tabela, a arrancada dos meias é um sinal fraco (FIS-06). A zaga e a lateral estão na M4 e o ataque na M8. Não contradiz a FIS-04: lá são as medidas do catálogo contadas por time; aqui, as da nota no meio-campo, com média ponderada por minuto no clube.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos meias com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.p5_clube"),
        "n_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.testes"),
        "firmes_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.bh5_clube"),
        "n_sobra_meio": G("inteiro_por_extenso", "sobecai_corrigido_por_clube.meio.passam5_rod"),
        "nomes_sobra_meio": D("texto", "nomes simples do glossário de sobecai_corrigido_por_clube.meio.sobreviventes_rod, vírgulas e 'e'", ["sobecai_corrigido_por_clube.meio.sobreviventes_rod"]),
        "nulo_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.excesso.SC.bruto.nulo_mediana"),
    },
    val={"nomes_sobra_meio": "arrancadas que viram sprint, distância em alta intensidade e sprints com a bola do adversário, corridas para a área, e tempo de giro de 90° e de 180°"},
    crit=[
        CONST("1. família (medidas da nota por setor, clube como caso) e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim (a nota mira essa comparação)"),
        KM("alguma medida com p bruto < 0,05 por clube", "sobecai_corrigido_por_clube.meio.p5_clube", papel="p", op=">", lim=0),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube.meio.passam5_rod", papel="rod", op=">", lim=0),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube.meio.bh5_clube", papel="q", op=">", lim=0),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube.meio.itens", papel="q_folga", op="<", lim=0.025, ag="min", sub="q_clube"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista crua do meio-campo acima da sorte (p do excesso < 0,05)", "sobecai_corrigido_por_clube.meio.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("a mesma lista descontado só o rodízio (descrição)", "sobecai_corrigido_por_clube.meio.excesso.SC.rod.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "firme por clube (algum q_clube < 0,05) E alguma continua só com o rodízio E nenhuma conferência testável",
           "forte_se": "firme por clube E pelo menos uma conferência testável, todas passando (não há nenhuma)",
           "nota": "o excesso decide pela lista crua (regra da régua); só com o rodízio a lista dá 0,095, dito no número",
           "saiu_em_15_09": "os níveis liq e liq2 (valor e valor + rodízio) e o 'q das sobreviventes' (virou q_rod por item)",
           "proibido": ["'só se sustenta no meio-campo'", "juntar M5 e M4 numa vaga das cinco", "'entre elencos de valor e rodízio parecidos'"]},
    # o p que decide o selo por clube é o bruto (p5_clube conta as medidas com p_clube < 0,05); o p só com o rodízio é outro papel
    p=P("sobecai_corrigido_por_clube.meio.itens", min(x["p_clube"] for x in resolver("sobecai_corrigido_por_clube.meio.itens")[1] if x.get("p_clube") is not None), agregacao="min", subcampo="p_clube"), ceticos=True,
    rev="reconferência 14/09: caminhos com nível (excesso.SC.bruto); itens com p_liq, p_liq2 e q_liq2; declaração do teste por clube e da semente acertada com o que mediu",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Firme por clube (5 com q < 0,05, a menor 0,023) e 6 continuando só com o rodízio (menor p 0,0004), sem conferência testável. A regra decide pela lista bruta (11 contra 1, p 0,028); só com o rodízio ela dá 0,095 e isso fica escrito. Sai 'entre elencos de valor e rodízio parecidos' e 'nos outros setores não sobra nenhuma' (o ataque sobra, M8)",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="M6", tema="mercado_e_contratacao", etapa="etapa_11", selo="fraco", declarada=False,
    titulo="Quem muda de clube repete menos o quanto recebe a bola do que quem fica",
    frase="Entre os jogadores com {corte_min_tec}+ minutos em dois anos seguidos, de {par_ini} a {par_fim}, a ordem no quanto cada um recebe a bola se mantém em {rho_rec_mudou} em quem mudou de clube, contra {rho_rec_ficou} em quem ficou (um é a mesma ordem, zero é ordem nenhuma). É um sinal {selo}: olhando só esse número, o acaso produziria a diferença em {p_rec_chance}; contando os {n_metricas} números testados, já não dá para descartar a sorte. Em {metricas_sem_diferenca} não se viu diferença entre quem muda e quem fica.",
    numero="{pares_mudou} pares de quem mudou e {pares_ficou} de quem ficou, sem {ano_parcial}.",
    ressalva="Não quer dizer 'não contrate pelo passe recebido' nem 'contrate pelo duelo'. Quem muda de clube pode mudar também de posição, de papel e de liga, e o estudo não distingue isso. Passes-chave e gols esperados se repetem pouco nos dois grupos ({rho_chave_mudou} e {rho_xg_mudou} em quem mudou).",
    universo="jogadores com {corte_min_tec}+ minutos em dois anos seguidos da Série B, de {par_ini} a {par_fim}: {pares_mudou} pares de quem mudou de clube e {pares_ficou} de quem ficou; sem {ano_parcial}",
    lac={
        "corte_min_tec": N("inteiro", "etapa_11.tecnico.corte_minutos"),
        "par_ini": N("texto", "etapa_11.tecnico.pares_por_ano", "primeiro par 'A→B'"),
        "par_fim": N("texto", "etapa_11.tecnico.pares_por_ano", "último par 'A→B'"),
        "rho_rec_mudou": V("dec2", "etapa_11.tecnico.metricas[metrica=Passes recebidos/90].rho_mudou", "etapa_11.tecnico.metricas[].rho_mudou", "gravado com 2026 (0,306); sem 2026 0,293"),
        "rho_rec_ficou": V("dec2", "etapa_11.tecnico.metricas[metrica=Passes recebidos/90].rho_ficou", "etapa_11.tecnico.metricas[].rho_ficou", "gravado com 2026 (0,528); sem 2026 0,525"),
        "p_rec_chance": N("chance_em_100", "etapa_11.tecnico.metricas[].p_dif_mudou_ficou", "Passes recebidos/90"),
        "n_metricas": G("contagem_da_lista", "etapa_11.tecnico.metricas"),
        "metricas_sem_diferenca": D("texto", "métricas com p_dif_mudou_ficou >= 0,10 entre duelos, duelos aéreos e dribles, nomes simples", ["etapa_11.tecnico.metricas"]),
        "pares_mudou": V("inteiro", "etapa_11.tecnico.pares_mudou", "etapa_11.tecnico.pares_mudou", "gravado com 2026 (233); sem 2026 176"),
        "pares_ficou": V("inteiro", "etapa_11.tecnico.pares_ficou", "etapa_11.tecnico.pares_ficou", "gravado com 2026 (178); sem 2026 144"),
        "rho_chave_mudou": V("dec2", "etapa_11.tecnico.metricas[metrica=Passes chave/90].rho_mudou", "etapa_11.tecnico.metricas[].rho_mudou", "gravado com 2026 (0,193); sem 2026 0,096"),
        "rho_xg_mudou": V("dec2", "etapa_11.tecnico.metricas[metrica=Golos esperados/90].rho_mudou", "etapa_11.tecnico.metricas[].rho_mudou", "gravado com 2026 (0,223); sem 2026 0,281"),
    },
    val={"corte_min_tec": "900", "par_ini": "2022→2023", "par_fim": "2024→2025", "rho_rec_mudou": "0,29", "rho_rec_ficou": "0,53", "p_rec_chance": "2 de cada 100 tentativas",
         "metricas_sem_diferenca": "duelos, duelos aéreos e dribles", "pares_mudou": "176", "pares_ficou": "144", "rho_chave_mudou": "0,10", "rho_xg_mudou": "0,28", "selo": "fraco"},
    crit=[
        K("diferença entre quem mudou e quem ficou, Fisher z, p < 0,05", "etapa_11.tecnico.metricas[].p_dif_mudou_ficou", "0,016", True),
        K("conta das 10 métricas (q < 0,05)", "etapa_11.tecnico.metricas[].q_dif", "0,16", False),
        K("comparação declarada antes", None, "não: mudou x ficou por métrica montada depois de olhar", False, decide=False),
        K("lista acima da sorte (regra do dono)", None, "1 de 10: não", False, decide=False),
        K("sem 2026", "etapa_11.tecnico.ano_maximo", "2025", True),
    ],
    regra={"fraco_se": "p_dif < 0,05 E q_dif >= 0,05 (comparação montada depois de olhar: teto fraco sem lista acima da sorte)", "pre_requisito": "etapa_11.tecnico com ano <= 2025 (com 2026, p 0,007; sem, 0,016)",
           "proibido": ["'o número que menos acompanha'", "'se mantêm igual'", "'o que o jogador mais perde'", "'quem muda de clube muda de posição' como fato"]},
    p=P("etapa_11.tecnico.metricas[metrica=Passes recebidos/90].p_dif_mudou_ficou", 0.016), ceticos=True,
    rev="reconferência 14/09: 'quem muda de clube muda de posição' virou possibilidade; passes-chave e gols esperados com número e fonte; os rho gravados hoje incluem 2026 e não servem",
    faixa_keep=True,
    rodape_ops=[("replace", "`c9b_mala_rapido.py`, conferido em `v9_mala.py`", "passes-chave 0,096 / 0,092 e gols esperados 0,281 / 0,224, sem 2026 · `c9b_mala_rapido.py`, conferido em `v9_mala.py`")],
))
