# Tema 2: físico (FIS)
from sp6_base import *

C = []

C.append(conc(
    id="FIS-01", tema="fisico", etapa="etapa_2", selo="fraco", declarada=False,
    titulo="Quem cai tende a ser dos menos intensos do ano, mas não se viu isso continuar entre times que rodaram o elenco parecido",
    frase="Quem cai fica tipicamente em {pos_cai}º de {n_por_ano} em sprint, corrida forte e arrancada; os times do meio, em {pos_meio}º, de {ano_ini} a {ano_fim}. Dos {n_cai} que caíram, só {cai_top5} esteve entre os {k5} mais intensos do ano ({excecao_top5}) e {cai_bottom5} estavam entre os {k5} menos intensos. Quem sobe não se mostrou mais intenso que o meio da tabela.",
    numero="Sem desconto, o acaso produziria essa diferença em {p_bruto_chance}; entre times que rodaram o elenco parecido, em {p_rod_chance}. É um sinal {selo}: o índice e a comparação com o meio foram montados depois de olhar os dados, não há lista de onde saiam para comparar com a sorte, e a diferença não continua descontado o rodízio.",
    ressalva="Não quer dizer que faltou físico e por isso caiu, nem que contratar intensidade evita cair. A contagem dos mais e menos intensos é a mesma medida vista de outro jeito, não uma prova a mais.",
    universo=UNIVERSOS["fisico"],
    lac={
        "pos_cai": N("inteiro", "etapa_2.indice_intensidade.mediana_posicao", "cai"),
        "pos_meio": N("inteiro", "etapa_2.indice_intensidade.mediana_posicao", "meio"),
        "n_por_ano": G("inteiro", "etapa_1.curva_top_k.clubes_por_ano[0]"),
        "k5": N("inteiro", "etapa_2.indice_intensidade.k_extremos"),
        "cai_top5": N("inteiro", "etapa_2.indice_intensidade.cai_top_k"),
        "excecao_top5": N("texto", "etapa_2.indice_intensidade.excecoes_top_k", "'o CLUBE ANO, Nº', vírgulas e 'e'"),
        "cai_bottom5": N("inteiro", "etapa_2.indice_intensidade.cai_bottom_k"),
        "p_bruto_chance": N("chance_em_100", "etapa_2.indice_intensidade.p_bruto_CM"),
        "p_rod_chance": N("chance_em_100", "etapa_2.indice_intensidade.p_rod_CM"),
    },
    val={"pos_cai": "15", "pos_meio": "9", "k5": "5", "cai_top5": "1", "excecao_top5": "o Londrina 2023, 2º", "cai_bottom5": "8", "p_bruto_chance": "menos de 1 de cada 100 tentativas",
         "p_rod_chance": "8 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação e índice declarados antes", False, papel="declarada", txt="não: índice e 'quem cai contra o meio' montados depois de olhar"),
        KM("p bruto < 0,05 (quem cai contra o meio)", "etapa_2.indice_intensidade.p_bruto_CM", papel="p", op="<", lim=0.05, v=0.0095),
        KM("5. descontado só o rodízio (atletas rastreados), p < 0,05", "etapa_2.indice_intensidade.p_rod_CM", papel="rod", op="<", lim=0.05, v=0.077,
           txt="0,077 no rascunho da parte 1, não definitivo (o índice refeito lá dá bruto 0,013, contra 0,0095 do gravado)"),
        CONST("4. lista de onde a comparação saia, com mais achados que a sorte", False, papel="lista", txt="não há lista: índice único"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → fraco; no físico, p_rod >= 0,05 → fraco",
           "fraco_se": "p_bruto_CM < 0,05 E (p_rod_CM >= 0,05 OU comparação montada depois de olhar sem lista)", "moderado_se": "impossível: índice e comparação montados depois de olhar, sem lista declarada",
           "regra_de_teste": "só p bilateral para o leitor", "proibido": ["'é o rodízio' como explicação", "'nunca tem físico bom'", "'entre elencos de valor parecido' (o desconto do valor saiu em 15/09)"]},
    p=P("etapa_2.indice_intensidade.p_bruto_CM", 0.0095), ceticos=True,
    rev="reconferência 14/09: posições 15º e 9º conferidas (`r13_varios.py`: mediana da posição no ano 15, 9 e 7 para cai, meio e sobe); regra do dono reaplicada: sem lista e some no dinheiro, fica fraco",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor do elenco; fica só o do rodízio (0,077 no rascunho da parte 1, não definitivo até o gerador gravar `etapa_2.indice_intensidade.p_rod_CM`). Título troca 'valor e rodízio' por 'rodízio'. Selo segue FRACO (sem lista e não continua no rodízio)",
    faixa_keep=True,
    rodape_ops=[("replace", "índice = média do posto no ano em 10 colunas", "posição no ano pelo índice (1 = mais intenso): mediana 7 em quem sobe, 9 no meio, 15 em quem cai; Londrina 2023 2º; 8 rebaixados entre os 5 últimos (`r13_varios.py`) · índice = média do posto no ano em 10 colunas")],
))

C.append(conc(
    id="FIS-04", tema="fisico", etapa="etapa_3", selo="moderado", declarada=True, regime="propria: lista inteira",
    titulo="Quem sobe tem físico melhor que quem cai no número cru, e isso continua entre times que rodaram o elenco parecido",
    frase="De {ano_ini} a {ano_fim}, {n_bruto} das {n_medidas} medidas físicas separam quem sobe de quem cai no número cru, quando o acaso daria umas {esperado}, e nas duas listas (elenco e setor) isso passa do que a sorte produz. Descontado só o número de atletas rastreados, {n_rod} continuam separando, e a lista por setor ainda tem mais achados do que a sorte. É um sinal {selo}: não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="Com {n_sobe} contra {n_cai}, {frase_tamanho_16x16}.",
    ressalva="Não quer dizer que físico faz subir, nem que se contrata pelo físico: elenco valioso tende a ter isso, e o estudo não separa as duas coisas; e o desconto do rodízio pode levar junto uma parte real da diferença. Não contradiz a FIS-09: lá é quem sobe contra o meio, onde a lista fica no nível da sorte. A FIS-10, a M5 e a M8 são medidas contadas uma a uma; aqui é o conjunto das {n_medidas}.",
    tecnico="tamanho detectável {d_min}",
    universo=UNIVERSOS["fisico"],
    lac={
        "n_bruto": D("inteiro", "fisico_col_elenco.passam5_SC + fisico_col_setor.passam5_SC", ["etapa_3.por_familia.fisico_col_elenco.passam5_SC", "etapa_3.por_familia.fisico_col_setor.passam5_SC"]),
        "n_medidas": D("inteiro", "fisico_col_elenco.testes + fisico_col_setor.testes", ["etapa_3.por_familia.fisico_col_elenco.testes", "etapa_3.por_familia.fisico_col_setor.testes"]),
        "esperado": D("inteiro", "soma de excesso.SC.bruto.nulo_mediana das duas famílias físicas", ["etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.nulo_mediana", "etapa_3.por_familia.fisico_col_elenco.excesso.SC.bruto.nulo_mediana"]),
        "n_rod": D("inteiro", "fisico_col_elenco.passam5_rod_SC + fisico_col_setor.passam5_rod_SC", ["etapa_3.por_familia.fisico_col_elenco.passam5_rod_SC", "etapa_3.por_familia.fisico_col_setor.passam5_rod_SC"]),
        "d_min": G("dec2", "etapa_0.poder.d_minimo_16x16"),
    },
    val={"n_bruto": "41", "n_medidas": "160", "esperado": "7", "n_rod": "34"},
    crit=[
        CONST("1. famílias físicas e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim"),
        KM("4. lista acima da sorte no número cru, quem sobe contra quem cai, em alguma das duas listas físicas (p do excesso < 0,05)", "etapa_3.por_familia", papel="lista", op="<", lim=0.05, ag="algum",
           filtro={"tipo": "dicionario", "nome": "familia", "valores": ["fisico_col_setor", "fisico_col_elenco"]}, sub="excesso.SC.bruto.p_excesso"),
        KM("5. a mesma lista descontado só o rodízio, em alguma das duas (p do excesso < 0,05)", "etapa_3.por_familia", papel="rod", op="<", lim=0.05, ag="algum",
           filtro={"tipo": "dicionario", "nome": "familia", "valores": ["fisico_col_setor", "fisico_col_elenco"]}, sub="excesso.SC.rod.p_excesso"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
    ],
    regra_propria=[("moderado", {0: True, 1: True, 2: True, 3: False}), ("fraco", {1: True, 2: False}), ("sem_sinal", {1: False})],
    regra={"regua": "régua final de 15/09, regra própria da lista inteira: a conclusão é sobre a lista, não sobre uma linha",
           "moderado_se": "lista declarada com p_excesso SC bruto < 0,05 em alguma família física E a mesma lista com p_excesso SC rod < 0,05 E nenhuma conferência testável",
           "fraco_se": "excesso no bruto E sem excesso descontado só o rodízio", "sem_sinal_se": "sem excesso nem no bruto",
           "obrigatorio": "dizer que o desconto do rodízio pode apagar sinal real; ressalva sem desconto e sem receita (elenco valioso tende a ter isso; o estudo não separa as duas coisas)",
           "proibido": ["'menos do que o acaso daria'", "abrir o título pela conta já descontada", "'entre elencos de valor parecido' (o desconto do valor saiu em 15/09)"]},
    p=P("etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso", 0.0104), ceticos=True,
    rev="reconferência 14/09: caminho do esperado passa a ser excesso.SC.bruto.nulo_mediana (um nome só); ressalva também explica a FIS-10, que virou moderada",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só porque o desconto do valor levava quase tudo (sobravam 4, e 2 com valor e rodízio). Descontado só o rodízio sobram 34 das 41, e a lista por setor segue com mais achados que a sorte (27 contra 6, p 0,0108). Sem conferência testável: moderado. A ressalva do elenco valioso entra sem desconto e sem receita (resposta b do dono); a medida por coluna (`etapa_2.andam_com_o_valor`) ainda não está gravada",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 (`prototipo_novo.json`, dado ainda não gravado no projeto): quem sobe contra quem cai, contagem bruta das duas listas físicas 14 (elenco, p do excesso 0,0099) e 27 (setor, 0,0104), sorteio típico 1 e 6; descontado só o posto de atletas rastreados (`fis_atletas` no elenco, `fis_<setor>_atletas` no setor) 7 (elenco, 0,077) e 27 (setor, 0,0108) · na conta de 14/09, com o desconto do valor, sobravam 4 e, com valor e rodízio, 2 (`r4_saida.json`): quem derrubava o físico era o dinheiro, não o rodízio (`m1_rodizio_catalogo.py`, parte 1) · quem sobe contra o meio: 9 contra 6 (setor, p 0,33) e 0 contra 1 (elenco, p 1,0), FIS-09 · onde ver na aba: etapa 3",
))

C.append(conc(
    id="FIS-05", tema="fisico", etapa="etapa_2", selo="sem_sinal", declarada=True,
    titulo="Não se viu quem sobe correr mais",
    frase="Na distância total por jogo, de {ano_ini} a {ano_fim}, os três grupos ficam praticamente iguais: {dist_sobe} metros em quem sobe, {dist_meio} no meio e {dist_cai} em quem cai. E {mais_correu_caiu}, o time que mais correu no ano, caiu.",
    numero="Uma diferença como a de quem sobe para o meio, o acaso produziria em {p_sm_chance}.",
    ressalva="Não quer dizer que volume não importa: o estudo só veria uma diferença grande contra o meio, ou muito grande contra quem cai.",
    tecnico="tamanho detectável {d_min_sm} ({n_sobe} contra {n_meio}) e {d_min_sc} ({n_sobe} contra {n_cai})",
    universo=UNIVERSOS["fisico"],
    lac={
        "dist_sobe": G("milhar", "etapa_2.linhas[indicador=fis_distance_p90].m_sobe"),
        "dist_meio": G("milhar", "etapa_2.linhas[indicador=fis_distance_p90].m_meio"),
        "dist_cai": G("milhar", "etapa_2.linhas[indicador=fis_distance_p90].m_cai"),
        "mais_correu_caiu": N("texto", "etapa_2.por_clube", "rebaixados com posto 1 de fis_distance_p90 no ano: 'o CLUBE de ANO'"),
        "p_sm_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_distance_p90].p_bruto_SM"),
        "d_min_sm": G("dec2", "etapa_0.poder.d_minimo_16x48"),
        "d_min_sc": G("dec2", "etapa_0.poder.d_minimo_16x16"),
    },
    val={"mais_correu_caiu": "o CSA de 2022"},
    crit=[
        K("quem sobe contra o meio, p >= 0,10", "etapa_2.linhas[indicador=fis_distance_p90].p_bruto_SM", "0,54", True),
        K("5. descontado só o rodízio, p >= 0,10", "etapa_2.linhas[indicador=fis_distance_p90].p_rod_SM", "0,59", True),
    ],
    regra={"sem_sinal_se": "p_bruto_SM >= 0,10 E p_rod_SM >= 0,10", "proibido": ["'correr mais não separa ninguém' como fato", "'volume depende do plano de jogo'", "'não use corre muito para contratar'"]},
    p=P("etapa_2.linhas[indicador=fis_distance_p90].p_bruto_SM", 0.54068), ceticos=True, rev="reconferência 14/09: universo e critérios; tamanho detectável sem número digitado no molde", rev15="rodada sem dinheiro (15/09): segue SEM SINAL. O desconto conjunto dá lugar ao do rodízio (p 0,59)", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="FIS-06", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="O meio-campo de quem sobe faz mais arrancadas que viram sprint",
    frase="{v_sobe} por jogo, contra {v_meio} no meio da tabela e {v_cai} em quem cai, de {ano_ini} a {ano_fim}. A diferença continua entre times que rodaram o elenco parecido. É um sinal {selo}: foram testadas {n_familia_fisico_setor} medidas físicas por setor, e o número das que separaram é o que a sorte produz; esta pode ser uma delas.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer 'contrate meia que arranca e você sobe'. Em {ano_contra} o sinal não apareceu, e não houve como conferir por outro caminho. Contra quem cai, a arrancada dos meias continua de pé contada por clube (M5).",
    universo=UNIVERSOS["fisico"],
    lac={
        "v_sobe": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_sobe"),
        "v_meio": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_meio"),
        "v_cai": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_cai"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
        "ano_contra": N("texto", "etapa_2.linhas[].media_por_ano", "fis_meio_expl_accel_sprint_p90: anos com resíduo de sobe menor que o de meio"),
    },
    val={"ano_contra": "2024"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados do meio-campo), p < 0,05", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "declarada E p_bruto_SM < 0,05 E p_rod_SM < 0,05 E (q_SM < 0,05 OU lista do físico por setor SM com p_excesso < 0,05)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM no nível da sorte))",
           "forte_se": "q_SM < 0,05 E p_rod_SM < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "proibido": ["'a melhor pista física'", "'não há físico por jogo'", "'não é marca do clube'", "'orçamento'", "'entre times de valor parecido'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_bruto_SM", 0.00468), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu do molde; caminho do excesso com nível (excesso.SM.bruto)",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor e a frase do clube no ano seguinte; o físico é conferido só com o rodízio (p 0,0046). Selo segue FRACO: q 0,58 e a lista quem sobe contra o meio no nível da sorte (9 contra 6, p 0,33)",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="FIS-07", tema="fisico", etapa="etapa_11", selo="forte", declarada=True,
    titulo="O físico do jogador se repete de um ano para o outro, também em quem troca de clube",
    frase="Comparando cada atleta com os do mesmo setor, a ordem se mantém em {rho_setor}, numa escala em que um é a mesma ordem e zero é ordem nenhuma, e fica entre {menor_par_setor} e {maior_par_setor} nos {n_pares_anos} pares de anos. Em quem mudou de clube, {rho_setor_mudou}; em quem ficou, {rho_setor_ficou}. É um sinal {selo} de que o número é do atleta: em cada par de anos, cada uma das {n_metricas} medidas declaradas se repete além do acaso, no setor e também na conta declarada antes, com a liga inteira.",
    numero="Em cada par de anos e em cada uma das medidas, o acaso produziria essa repetição em {p_max_chance}. Olhando a liga inteira, sem separar setor, a ordem fica em {rho}; essa conta responde a outra pergunta e mistura a diferença entre posições, então não se põe ao lado do técnico.",
    ressalva="Não é um sinal de que o atleta vai render. Não quer dizer 'contrate pelo físico', nem que físico bom faz subir: não se viu a nota física prever minutos nem permanência de quem chegou (M2), nem o físico, no conjunto, separar quem sobe do meio da tabela (FIS-09). Também não dá para afirmar que quem muda de clube repete menos: a diferença ({dif_ficou_mudou}, intervalo de {ic_dif}) cabe no acaso. Só entra quem jogou {corte_jogos}+ partidas na Série B nos dois anos: quem subiu para a A ou caiu para a C fica de fora.",
    universo="{pares} pares de atletas ligados por nome e data de nascimento, de {par_ini} a {par_fim}, com {corte_jogos}+ jogos rastreados na Série B nos dois anos ({pares_mudou} mudaram de clube, {pares_ficou} ficaram); físico do SkillCorner, sem {ano_parcial}",
    lac={
        "rho_setor": N("dec2", "etapa_11.fisico.por_setor.rho_mediano"),
        "menor_par_setor": D("dec2", "menor rho de por_setor.rho_mediano_por_par_de_anos", ["etapa_11.fisico.por_setor.rho_mediano_por_par_de_anos"]),
        "maior_par_setor": D("dec2", "maior rho de por_setor.rho_mediano_por_par_de_anos", ["etapa_11.fisico.por_setor.rho_mediano_por_par_de_anos"]),
        "n_pares_anos": D("contagem_da_lista", "len(por_setor.rho_mediano_por_par_de_anos)", ["etapa_11.fisico.por_setor.rho_mediano_por_par_de_anos"]),
        "rho_setor_mudou": N("dec2", "etapa_11.fisico.por_setor.rho_mudou"),
        "rho_setor_ficou": N("dec2", "etapa_11.fisico.por_setor.rho_ficou"),
        "n_metricas": D("inteiro", "número de métricas declaradas da etapa 11 (lista fixa de 10)", []),
        "p_max_chance": N("chance_em_1000", "etapa_11.fisico.por_setor.p_max"),
        "rho": V("dec2", "etapa_11.fisico.rho_mediano", "etapa_11.fisico.rho_mediano", "o gravado hoje (0,833) liga o atleta só pelo nome e inclui 20 pares de homônimos; com a chave nome + nascimento dá 0,861"),
        "dif_ficou_mudou": N("texto", "etapa_11.fisico.por_setor.dif_ficou_menos_mudou", "dec2 com sinal '+' ou '−'"),
        "ic_dif": N("texto", "etapa_11.fisico.por_setor.ic95_dif", "'−0,03 a +0,14'"),
        "corte_jogos": N("inteiro", "etapa_11.fisico.corte_jogos"),
        "pares": V("inteiro", "etapa_11.fisico.pares", "etapa_11.fisico.pares", "499 hoje (com homônimos); 479 com a chave nome + nascimento"),
        "par_ini": N("texto", "etapa_11.fisico.por_setor.rho_mediano_por_par_de_anos", "primeiro par 'A→B'"),
        "par_fim": N("texto", "etapa_11.fisico.por_setor.rho_mediano_por_par_de_anos", "último par 'A→B'"),
        "pares_mudou": N("inteiro", "etapa_11.fisico.por_setor.n_mudou"),
        "pares_ficou": N("inteiro", "etapa_11.fisico.por_setor.n_ficou"),
    },
    val={"rho_setor": "0,64", "menor_par_setor": "0,61", "maior_par_setor": "0,66", "n_pares_anos": "3", "rho_setor_mudou": "0,63", "rho_setor_ficou": "0,68", "n_metricas": "10",
         "p_max_chance": "menos de 1 de cada 1.000 tentativas", "rho": "0,86", "dif_ficou_mudou": "+0,05", "ic_dif": "−0,03 a +0,14", "corte_jogos": "8", "pares": "479",
         "par_ini": "2022→2023", "par_fim": "2024→2025", "pares_mudou": "295", "pares_ficou": "184", "selo": "forte"},
    crit=[
        K("teste de cada par de anos (régua do setor): Spearman de cada uma das 10 medidas declaradas, p < 0,05 em todo par", "etapa_11.fisico.por_setor.p_max", "maior p nas 30 contas 1,5 × 10⁻¹²", True),
        K("o mesmo na régua declarada antes (posto no ano, liga inteira)", "etapa_11.fisico.p_max", "maior p nas 30 contas 9,5 × 10⁻²⁶", True),
        K("atleta ligado por nome e nascimento (sem homônimos)", "etapa_11.fisico.chave_do_atleta", "479 pares", True),
        K("tamanho (descrição, não decide): mediana e intervalo", "etapa_11.fisico.por_setor.ic95", "0,64 (0,60 a 0,68); pares 0,61 a 0,66", True, decide=False),
    ],
    regra={"regua": "regua.repeticao_do_atleta",
           "forte_se": "por_setor.p_max < 0,05 (o maior p do teste de Spearman das 10 métricas declaradas em cada par de anos) E fisico.p_max < 0,05 na régua declarada antes (posto no ano) E chave do atleta nome + nascimento",
           "moderado_se": "p < 0,05 em algum par e não em todos",
           "sem_sinal_se": "nenhum par com p < 0,05",
           "tamanho": "a mediana, o intervalo e o corte de 0,5 só descrevem o tamanho (decisão 3 do dono, 14/09); não decidem o selo",
           "diferenca_mudou_ficou": "nao_da_para_afirmar enquanto ic95_dif cruzar zero; a frase não diz 'quem mudou repete menos'",
           "chave_do_atleta": "chave_nome(short_name) + '|' + birthdate",
           "universo_do_posto": "posto dentro de ano e setor, tirado depois do corte de 8 jogos",
           "ano_maximo": 2025,
           "medido_14_09": {"fonte": "r9_fis07_universos.py e r12_fis07_pares.py", "pares": 479, "setor": 0.64, "ic95": [0.60, 0.68], "por_par": {"2022→2023": {"rho": 0.609, "p_max_10": 3.3e-15}, "2023→2024": {"rho": 0.653, "p_max_10": 1.5e-12}, "2024→2025": {"rho": 0.659, "p_max_10": 9.1e-15}},
                            "mudou": 0.63, "ficou": 0.68, "dif": 0.05, "ic95_dif": [-0.03, 0.14], "ano": 0.86, "ano_p_max_10": 9.5e-26, "posicao": 0.58, "so_nome": {"pares": 499, "setor": 0.61, "mudou": 0.58, "ficou": 0.68, "ano": 0.83}},
           "proibido": ["'para contratar, o físico do ano anterior é uma boa pista'", "'quem mudou repete menos' enquanto o intervalo cruzar zero", "pôr o rho só por ano ao lado do técnico", "ligar atleta só pelo nome", "usar o corte de 0,5 como critério do selo"]},
    p=P("etapa_11.fisico.p_max", 9.5e-26), ceticos=True,
    rev15="rodada sem dinheiro (15/09): segue FORTE (repetição do atleta, regra própria). Só sai a constante do dinheiro",
    rev="reconferência 14/09 (decisão 3 do dono): o selo forte apoia-se no teste de cada par de anos (maior p das 30 contas 9,5 × 10⁻²⁶ na régua declarada antes, o posto no ano; 1,5 × 10⁻¹² no setor); o corte de 0,5 virou só descrição do tamanho. Conserto final 14/09: p_principal = etapa_11.fisico.p_max (a régua declarada); a do setor, escolhida depois, fica como a conta mais dura que não rebaixa",
    faixa_keep=True,
    rodape_ops=[("replace", "selo pela régua de repetição do atleta: mediana, intervalo inteiro e todo par de anos acima de 0,5 no setor e também na régua declarada antes (ano); cada par com p < 0,001",
                 "**selo pela decisão 3 do dono (14/09): o teste de cada par de anos** — Spearman de cada uma das 10 métricas em cada par, na régua do setor: maior p 3,3 × 10⁻¹⁵ (2022→2023), 1,5 × 10⁻¹² (2023→2024), 9,1 × 10⁻¹⁵ (2024→2025); na régua declarada antes (ano): maior p 9,5 × 10⁻²⁶ (`r12_fis07_pares.py`, `r12_saida.json`); menor ρ de uma métrica num par: 0,53 (setor) e 0,72 (ano) · o corte de 0,5 (mediana, intervalo e pares acima dele) ficou só como descrição do tamanho, porque foi escrito depois de ver a FIS-07")],
))

C.append(conc(
    id="FIS-08", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="A zaga de quem sobe corre menos que a do meio da tabela",
    frase="Uns {dif_metros} metros a menos por jogo, por zagueiro, de {ano_ini} a {ano_fim}. A diferença continua entre times que rodaram o elenco parecido. É um sinal {selo}: entre {n_familia_fisico_setor} medidas físicas por setor, o número das que separam é o que a sorte produz, e só {sobe_com_zaga} dos {n_prom} que subiram tinham zagueiros rastreados em número suficiente.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer 'contrate zagueiro que corre pouco', nem que correr menos ajuda a subir: pode ser só um time menos atacado. As contas de distância da zaga são um achado só, não vários.",
    universo=UNIVERSOS["fisico"],
    lac={
        "dif_metros": D("inteiro", "m_meio - m_sobe de fis_zaga_distance_p90, arredondado a 50", ["etapa_2.linhas[indicador=fis_zaga_distance_p90].m_meio", "etapa_2.linhas[indicador=fis_zaga_distance_p90].m_sobe"]),
        "sobe_com_zaga": N("inteiro", "etapa_2.linhas[].n_sobe", "fis_zaga_distance_p90"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
    },
    val={"dif_metros": "150", "sobe_com_zaga": "12"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados da zaga), p < 0,05", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_zaga_distance_p90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_zaga_distance_p90].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM do físico por setor no nível da sorte))",
           "marca": "distance, m_per_min e tip da zaga contam como uma medida só", "proibido": ["'orçamento'", "'entre times de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_zaga_distance_p90].p_bruto_SM", 0.02292), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu; lacuna da sensibilidade sem corte removida (não estava no molde)",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor; só o rodízio (p 0,021). Selo segue FRACO: q 0,58 e lista no nível da sorte (p 0,33)",
    faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="FIS-09", tema="fisico", etapa="etapa_3", selo="sem_sinal", declarada=True,
    titulo="Físico no conjunto: não se viu quem sobe diferente do meio da tabela",
    frase="De {ano_ini} a {ano_fim}, não se viu nenhuma medida física sozinha separar quem sobe do meio com segurança. No catálogo de {n_medidas} medidas declaradas, o número das que separam é o que a sorte produz: {n_passam_setor} das {n_setor} por setor, contra {esperado_setor} do sorteio, e {n_passam_elenco} das {n_elenco} do elenco, contra {esperado_elenco}. Com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="Uma bateria maior da conferência anterior, com outros recortes, achou mais do que a sorte; ela vai para o mesmo lado, mas não é a conta declarada, e o selo segue a declarada, como na J10.",
    ressalva="Não quer dizer nem que o físico explica a subida, nem que não explica. As duas contas ainda precisam ser refeitas lado a lado, no mesmo sorteio.",
    universo=UNIVERSOS["fisico"],
    lac={
        "n_medidas": D("inteiro", "fisico_col_elenco.testes + fisico_col_setor.testes", ["etapa_3.por_familia.fisico_col_elenco.testes", "etapa_3.por_familia.fisico_col_setor.testes"]),
        "n_passam_setor": G("inteiro", "etapa_3.por_familia.fisico_col_setor.passam5_SM"),
        "n_setor": G("inteiro", "etapa_3.por_familia.fisico_col_setor.testes"),
        "esperado_setor": N("inteiro", "etapa_3.por_familia[].excesso.SM.bruto.nulo_mediana", "fisico_col_setor"),
        "n_passam_elenco": G("nenhuma_se_zero", "etapa_3.por_familia.fisico_col_elenco.passam5_SM"),
        "n_elenco": G("inteiro", "etapa_3.por_familia.fisico_col_elenco.testes"),
        "esperado_elenco": N("inteiro", "etapa_3.por_familia[].excesso.SM.bruto.nulo_mediana", "fisico_col_elenco"),
    },
    val={"n_medidas": "160", "esperado_setor": "6", "esperado_elenco": "1"},
    crit=[
        K("conta declarada: lista do físico por setor sem excesso (p do excesso >= 0,10)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", "9 contra 6, p 0,33", True),
        K("conta declarada: lista do físico do elenco sem excesso", "etapa_3.por_familia.fisico_col_elenco.excesso.SM.bruto.p_excesso", "0 contra 1, p 1,0", True),
        K("outra conta, não declarada (bateria de 332 da conferência): mesmo lado", None, "56 contra 15, p 0,019 (CONFERENCIA.md §2.4)", None, decide=False),
    ],
    regra={"sem_sinal_se": "p_excesso SM bruto >= 0,10 nas duas famílias físicas declaradas", "outra_conta": "bateria de 332 (CONFERENCIA §2.4): mesmo lado, não declarada; citada, não decide (critério da J10)",
           "nao_da_para_afirmar_se": "a reconciliação no mesmo nulo der lados opostos", "proibido": ["'o físico não separa'", "'nenhuma medida sozinha separa' (ausência afirmada)", "nao_da_para_afirmar por contas no mesmo lado"]},
    p=P("etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", 0.33), ceticos=True,
    rev="reconferência 14/09: 'nenhuma medida sozinha separa' virou 'não se viu nenhuma medida sozinha separar'; números da bateria de 332 saíram do molde (não vêm do gerador) e ficam no rodapé", faixa_keep=True, rodape_ops=[],
))

C.append(conc(
    id="FIS-10", tema="fisico", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="O ataque de quem sobe faz mais corridas em alta velocidade que o de quem cai; contra o meio não se viu diferença, com uma medida na zona cinzenta",
    frase="De {ano_ini} a {ano_fim}, {n_bloco_sc} das {n_bloco} medidas físicas do ataque separam quem sobe de quem cai no número cru, todas para o mesmo lado, e {n_bloco_rod} delas continuam entre times que rodaram o elenco parecido. Nas corridas em alta velocidade por jogo ({hsr_sobe} contra {hsr_cai}), a medida do título, é um sinal {selo}: não resiste à conta das {n_familia_fisico_setor} medidas físicas por setor, mas essa lista, na comparação quem sobe contra quem cai, tem mais achados do que a sorte produz.",
    numero="Olhando cada medida sozinha, o acaso produziria as diferenças em {faixa_p_chance}, conforme a medida; nas corridas em alta velocidade, descontado só o rodízio, em {p_rod_chance}. Contra o meio da tabela não se viu diferença, com uma medida na zona cinzenta ({nome_sm_limite}: {p_sm_limite_chance}).",
    ressalva="Não quer dizer que ataque que corre faz subir, nem que correr no ataque é o piso para não cair. Quem cai roda mais atacantes ({atac_cai} contra {atac_sobe}), e o desconto do rodízio pode levar junto uma parte real da diferença; não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}. Vai para o mesmo lado da M8, que conta por clube as medidas da nota de encaixe no ataque; o selo daqui segue a conta do catálogo declarado.",
    universo=UNIVERSOS["fisico"],
    lac={
        "n_bloco_sc": N("inteiro", "etapa_2.fis10_bloco.n_p_bruto_SC_abaixo_005"),
        "n_bloco": N("inteiro", "etapa_2.fis10_bloco.n"),
        "n_bloco_rod": D("inteiro", "linhas fis_ataque_* do catálogo com p_bruto_SC < 0,05 e p_rod_SC < 0,05", ["etapa_2.linhas"]),
        "hsr_sobe": G("dec1", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].m_sobe"),
        "hsr_cai": G("dec1", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].m_cai"),
        "faixa_p_chance": N("texto", "etapa_2.fis10_bloco", "p_bruto_SC_min e p_bruto_SC_max das linhas com p < 0,05, cada ponta por chance_em_100: 'menos de 1 a M de cada 100 tentativas'"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_rod_SC"),
        "atac_cai": G("dec1", "etapa_1.controle_n_atletas.por_setor[setor=ataque].media_cai"),
        "atac_sobe": G("dec1", "etapa_1.controle_n_atletas.por_setor[setor=ataque].media_sobe"),
        "nome_sm_limite": N("texto", "etapa_2.fis10_bloco.p_bruto_SM_min_indicador", "nome simples do glossário da linha com o menor p_bruto_SM do bloco"),
        "p_sm_limite_chance": N("chance_em_100", "etapa_2.fis10_bloco.p_bruto_SM_min"),
    },
    val={"n_bloco_sc": "12", "n_bloco": "32", "n_bloco_rod": "10", "faixa_p_chance": "menos de 1 a 4 de cada 100 tentativas", "nome_sm_limite": "corridas para a área", "p_sm_limite_chance": "5 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados do ataque), p < 0,05", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_rod_SC", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (físico por setor, quem sobe contra quem cai, p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SC < 0,05 E p_rod_SC < 0,05 E q_SC >= 0,05 E etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso < 0,05 (ou q_SC < 0,05 sem conferência testável)",
           "fraco_se": "p_bruto_SC < 0,05 E (p_rod_SC >= 0,05 OU (q_SC >= 0,05 E p_excesso SC bruto >= 0,05))",
           "forte_se": "q_SC < 0,05 E p_rod_SC < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "bloco": "etapa_2.fis10_bloco = as 32 linhas fis_ataque_* do catálogo (o setor inteiro, sem escolher colunas)",
           "outra_conta": "M8 (por clube, medidas da nota): mesmo lado; o selo segue o catálogo declarado",
           "obrigatorio": "o bloco é um achado só; dizer quantas medidas passam no cru e quantas descontado só o rodízio",
           "proibido": ["'corre mais rápido' (não é a pergunta do título)", "'no limite' fora do selo (vocabulário único: só no selo da zona cinzenta)", "'contra o meio não se viu' sem a medida na zona cinzenta (corridas para a área, 0,053)",
                        "'logo abaixo do corte'", "'a lista some nos descontos'", "'entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_bruto_SC", 0.00351), ceticos=True,
    rev="reconferência 14/09: fraco → moderado. Aplicada a regra do excesso que a FIS-06, a FIS-08 e a FIS-11 já tinham: as corridas em alta velocidade do ataque passam nos dois descontos (0,042 e 0,049), não passam na conta das 128 (q 0,097), e a lista do físico por setor na comparação quem sobe contra quem cai tem 27 achados contra 6 (p 0,010). O bloco são as 32 linhas do ataque, e 12 passam no cru (não 8)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem o desconto do valor, 'logo abaixo do corte', 'a lista some nos descontos' e a frase 'nada sobra no ataque' (a M4 foi partida e o ataque virou a M8, moderada). Descontado só o rodízio: p 0,0049; das 12 do bloco que separam no cru, 10 continuam; q 0,097; lista quem sobe contra quem cai 27 contra 6 (p 0,0104)",
    faixa_keep=True,
    rodape_texto="**rodada sem dinheiro de 15/09** (`prototipo_novo.json`, ainda não gravado no projeto) · bloco = as 32 linhas `fis_ataque_*` do catálogo; 12 com p bruto sobe x cai < 0,05 (de 0,0035 a 0,040), e 10 delas com p < 0,05 descontado só o posto de `fis_ataque_atletas` (ficam de fora `fis_ataque_psv99_top5`, 0,17, e as corridas para a área, 0,087) · `fis_ataque_hsr_count_p90` 58,5 / 56,6 / 53,9: p 0,0035, só rodízio 0,0049, q 0,097 nas 128 · lista do físico por setor, sobe x cai: 27 contra 6, p do excesso 0,0104 no bruto e 0,0108 só com o rodízio · sobe x meio nas 12, p de 0,053 (corridas para a área, na zona cinzenta) a 0,46 · na conta de 14/09 o selo passava pelo desconto do valor (0,042) e de valor e rodízio (0,049); saiu da régua · onde ver na aba: etapa 2",
))

C.append(conc(
    id="FIS-11", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="Os laterais de quem sobe atacam mais o espaço sem bola",
    frase="{v_sobe} corridas para espaço perigoso a cada meia hora com a bola do time, contra {v_meio} no meio da tabela, de {ano_ini} a {ano_fim}. Continua entre times que rodaram o elenco parecido e apareceu em {anos_ok} dos {n_anos} anos. É um sinal {selo}: entre {n_familia_fisico_setor} medidas físicas por setor, o número das que separam é o que a sorte produz.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer que o lateral é fisicamente melhor, nem 'contrate lateral que ataca o espaço': a medida é contada com a bola do próprio time e parece descrever o jeito de jogar (isso não foi medido).",
    universo=UNIVERSOS["fisico"],
    lac={
        "v_sobe": G("dec1", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].m_sobe"),
        "v_meio": G("dec1", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].m_meio"),
        "anos_ok": N("inteiro", "etapa_2.linhas[].media_por_ano", "fis_lateral_runs_dangerous_p30tip: anos com resíduo médio de sobe > meio"),
        "n_anos": G("contagem_da_lista", "etapa_1.curva_top_k.anos"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
    },
    val={"anos_ok": "4"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados da lateral), p < 0,05", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM do físico por setor no nível da sorte))",
           "marca": "medida condicionada à posse: descreve plano", "proibido": ["'orçamento'", "'entre times de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_bruto_SM", 0.01335), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu; caminho do excesso com nível",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor; só o rodízio (p 0,014). Selo segue FRACO: q 0,58 e lista no nível da sorte (p 0,33)",
    faixa_keep=True, rodape_ops=[],
))

