C.append(conc(
    id="A1", tema="anos_antigos", etapa="etapa_8", selo="fraco", declarada=False,
    titulo="Ocupar o campo e a área do adversário separou quem sobe nos dois períodos",
    frase="O eixo de território separou quem sobe do meio em {periodo_recente} e de novo, com os cortes congelados, em {periodo_antigo}; entradas na área e toques na área também. É um sinal {selo}: a família dos dois eixos (território e rota) foi escolhida depois de olhar; contando os dois eixos, já não dá para descartar a sorte, e não há lista de onde ela saia para comparar com a sorte.",
    numero="Em {periodo_antigo}, o acaso produziria a diferença do território em {p_antigo_chance}; em {periodo_recente}, em {p_recente_chance}.",
    ressalva="Não quer dizer que ocupar o campo adversário é caminho de subida: na Série B inteira, elenco valioso tende a ocupar mais o campo adversário (J10), e o estudo não separa as duas coisas; em {periodo_antigo} não há valor de mercado.",
    universo=UNIVERSOS["periodos"],
    lac={
        "p_antigo_chance": G("chance_em_1000", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2018-2021.TERRITORIO.p_SM"),
        "p_recente_chance": G("chance_em_100", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2022-2025.TERRITORIO.p_SM"),
    },
    crit=[
        CONST("1. família do eixo declarada antes", False, papel="declarada", txt="não: a família dos 2 eixos da tipologia (território e rota) foi escolhida depois de olhar (decisão do coordenador, 14/09)"),
        KM("território, quem sobe contra o meio, p < 0,05 em 2022-2025", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2022-2025.TERRITORIO.p_SM", papel="p", op="<", lim=0.05),
        CONST("4. lista de onde a família saia, com mais achados que a sorte", False, papel="lista", txt="não há lista própria; a de outra família (técnico do time) não se usa: seria garimpo"),
        KM("contando os 2 eixos, q de BH < 0,05 (descrição)", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2022-2025", op="<", lim=0.05, ag="bh",
           filtro={"tipo": "dicionario", "nome": "eixo", "valores": ["TERRITORIO", "ROTA"]}, sub="p_SM", decide=False),
        KM("conferência (descrição): 2018-2021, território, p < 0,05", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2018-2021.TERRITORIO.p_SM", op="<", lim=0.05, decide=False),
        KM("conferência (descrição): 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2018-2021.TERRITORIO.d_SM", op=">", lim=0, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): família escolhida depois de olhar, sem lista → teto fraco",
           "familia": "os 2 eixos da tipologia (declaracoes_novas.familia_A1), escolhida depois de olhar e registrada assim",
           "se_fosse_teste_unico": "seria forte (2018-2021 p 0,003); não é: a família é a dos 2 eixos",
           "saiu_em_15_09": "o critério 'componentes do eixo depois do desconto do dinheiro' e, do título, '— mas pode ser o dinheiro'",
           "proibido": ["'o que o orçamento compra'", "'em boa parte'", "ρ na frase de reunião", "usar a lista do técnico do time para dar excesso à A1"]},
    p=P("teste_cego_2018_2021.json eixos_como_marcador_de_acesso.2022-2025.TERRITORIO.p_SM", 0.0282), ceticos=False,
    rev="reconferência 14/09: 'orçamento' saiu do molde; períodos por lacuna",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o desconto do dinheiro (critério e título). A família é a dos 2 eixos (decisão do coordenador), escolhida depois de olhar: q 0,056, sem lista → fraco. Como teste único seria forte (2018-2021 p 0,003), e isso fica registrado. Entra a ressalva sem desconto",
    faixa_keep=True, rodape_ops=[],
))
