C.append(conc(
    id="A2", tema="anos_antigos", etapa="etapa_8", selo="moderado", declarada=True,
    titulo="O que separou quem sobe em {periodo_recente} apontou para o mesmo lado em {periodo_antigo}",
    frase="Dos {n_ind} números de jogo com selo que existem nos dois períodos, {mesmo_sinal} foram para o mesmo lado, e os que separavam mais num período tendiam a separar mais no outro. É um sinal {selo}: é um teste só, declarado antes, e não há outro caminho para conferir.",
    numero="O acaso produziria essa concordância em {p_conc_chance}.",
    ressalva="Não quer dizer que cada número replicou: só {replicam} dos {n_ind} ficaram, sozinhos, abaixo do limite em {periodo_antigo}. Elenco valioso tende a ter vários desses números; o estudo não separa as duas coisas, e em {periodo_antigo} não há valor de mercado.",
    universo=UNIVERSOS["periodos"],
    lac={
        "n_ind": D("inteiro", "denominador de porta_concordancia.mesmo_sinal_SM ('12/12' → 12)", ["teste_cego_2018_2021.json porta_concordancia.mesmo_sinal_SM"]),
        "mesmo_sinal": G("numerador", "teste_cego_2018_2021.json porta_concordancia.mesmo_sinal_SM"),
        "p_conc_chance": G("chance_em_100", "teste_cego_2018_2021.json porta_concordancia.p"),
        "replicam": G("inteiro", "teste_cego_2018_2021.json porta_concordancia.replicam_p05_SM"),
    },
    val={"n_ind": "12"},
    crit=[
        CONST("1. teste declarado antes: concordância entre os períodos", True, papel="declarada", txt="sim"),
        KM("concordância entre os períodos, p < 0,05", "teste_cego_2018_2021.json porta_concordancia.p", papel="p", op="<", lim=0.05),
        KM("2. firme: teste único declarado, q = p < 0,05", "teste_cego_2018_2021.json porta_concordancia.p", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "teste_cego_2018_2021.json porta_concordancia.p", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: a concordância já é a comparação entre os dois períodos; não há terceiro período nem versão por jogo"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): teste único declarado e firme, sem conferência testável → moderado",
           "moderado_se": "porta_concordancia.p < 0,05 sem conferência testável",
           "ressalva": "sem desconto e sem receita (resposta b do dono); na parte 1, 7 dos 12 indicadores andavam com o valor do elenco; a medida por coluna vai para etapa_2.andam_com_o_valor",
           "saiu_em_15_09": "o critério 'todos os 12 continuam depois do desconto do dinheiro' (era o único motivo do fraco)",
           "proibido": ["exceção de régua para concordância crua", "'os 12 números de jogo que existem nos dois períodos' sem 'com selo' (o técnico do time tem 31)", "'a concordância pode ser o elenco caro' como fato"]},
    p=P("teste_cego_2018_2021.json porta_concordancia.p", 0.0202), ceticos=False,
    rev="reconferência 14/09: n_morrem lê a lista de teste_cego porta.novo[].ind cruzada com etapa_2.linhas[].p_liq_SM; períodos por lacuna",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só porque 7 dos 12 números não passavam no desconto do valor. Pela régua final: teste único declarado, p 0,020 (firme, q = p), sem outra conferência → moderado. Entra a ressalva sem desconto e sem receita (resposta b do dono)",
    faixa_keep=True, rodape_ops=[],
))
