C.append(conc(
    id="A4", tema="anos_antigos", etapa="etapa_0", selo="fraco", declarada=False,
    titulo="O mando de campo pesou mais em {periodo_recente} do que em {periodo_antigo}",
    frase="Os mandantes fizeram {pct_recente}% dos pontos em {periodo_recente}, contra {pct_antigo}% em {periodo_antigo}. É um sinal {selo}: a comparação entre os dois períodos foi notada depois de olhar os dados (o critério declarado antes era outro: se o ano sem torcida sairia da faixa dos outros), não há lista de onde ela saia para comparar com a sorte, e com {n_anos_lado} anos de cada lado não há como repetir.",
    numero="Tomando o ano como unidade ({n_anos_lado} contra {n_anos_lado}), o acaso produziria essa diferença em {p_bloco_chance}.",
    ressalva="Não quer dizer que se sabe por que mudou, nem que o mando continua subindo. Qualquer conta em número cru que dependa de jogar em casa não pode juntar os dois períodos; as contas do estudo usam a posição no ranking do ano, o que neutraliza isso.",
    universo="os jogos da Série B de {periodo_antigo} e de {periodo_recente}, com o ano como unidade ({n_anos_lado} anos de cada lado); {ano_parcial} fica fora de toda conta",
    lac={
        "pct_recente": N("dec1", "etapa_0.mando.media_2022_2025"),
        "pct_antigo": N("dec1", "etapa_0.mando.media_2018_2021"),
        "n_anos_lado": N("inteiro", "etapa_0.mando.n_anos_por_lado"),
        "p_bloco_chance": N("chance_em_100", "etapa_0.mando.p_bloco_por_ano"),
    },
    val={"pct_recente": "64,5", "pct_antigo": "59,3", "n_anos_lado": "4", "p_bloco_chance": "3 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação declarada antes", False, papel="declarada", txt="não: o critério declarado antes era o de 2020"),
        KM("t de Welch com o ano como unidade, p < 0,05", "etapa_0.mando.p_bloco_por_ano", papel="p", op="<", lim=0.05, v=0.027),
        CONST("4. lista acima da sorte (regra do dono)", False, papel="lista", txt="não há lista"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "p_bloco_por_ano < 0,05 E comparação notada depois de olhar sem lista", "sem_sinal_se": "p_bloco_por_ano >= 0,10", "teste": "t de Welch, ano como unidade (não Student)",
           "saiu_em_15_09": "o 'desconto não se aplica' do critério da regra do dono"},
    p=P("etapa_0.mando.p_bloco_por_ano", 0.0269), ceticos=True,
    rev="reconferência 14/09: regra do dono reaplicada (sem lista): segue fraco; o destino do p passa a ser etapa_0.mando no prototipo.json, não o teste cego congelado",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o desconto do critério da regra do dono; a regra_maquina ganha a linha 'escolhida depois sem lista → fraco'",
    faixa_keep=True,
    rodape_ops=[("replace", "pela regra da comparação escolhida depois de olhar ·", "pela regra da comparação escolhida depois de olhar; na reconferência segue FRACO pela decisão 1 do dono (não há lista de onde a comparação entre períodos saia) ·"),
                ("replace", "o p com o ano como unidade não está gravado (`regime_veredito.p_bloco_por_ano` ausente): a A4 fica fora da tela e fora das cinco até o gerador gravar",
                 "o p com o ano como unidade vai para `etapa_0.mando.p_bloco_por_ano` no `prototipo.json` (o teste cego é congelado e não recebe escrita); até o gerador gravar, a A4 fica fora da tela e fora das cinco · vitória do mandante 42,9% (1.519 jogos) x 48,5% (1.518), só descrição")],
))
