C.append(conc(
    id="DIN-03", tema="dinheiro_e_elenco", etapa="etapa_1", selo="fraco", declarada=False,
    titulo="Do lado de baixo, o valor do elenco também pesa — menos, e não se viu isso em todo ano",
    frase="Entre os {k_quartil} elencos mais valiosos de cada ano, de {ano_ini} a {ano_fim}, {cai_q4} caiu pelo Transfermarkt e caiu {cai_q4_wyscout} pelo valor do Wyscout ({exemplo_wyscout}); a sorte produziria tão poucos em {p_q4_chance} e em {p_q4_wy_chance}. Quem caiu tinha elenco mais barato que o time do meio da tabela em {auc_cm_100}. É um sinal {selo}: a comparação quem cai contra o meio foi escolhida depois de olhar os números, e não há uma lista de onde ela saia para comparar com a sorte, então pela regra do dono não passa de fraco. Além disso, em {ano_sem_sinal_cai} não se viu o valor distinguir rebaixado de meio de tabela, e não há como conferir antes de {ano_ini}.",
    numero="Por ano, esse acerto foi de {auc_cm_por_ano} de cada 100 pares.",
    ressalva="Não quer dizer que elenco caro não cai, nem que elenco top {k_quartil} nunca cai: pelo valor do Wyscout, {exemplo_wyscout}, caiu, e os rebaixados mais caros por essa fonte aparecem nos postos {postos_cai_wyscout}.",
    universo="{n_clube_temporadas} clube-temporadas da Série B de {ano_ini} a {ano_fim} ({n_sobe} subiram, {n_meio} ficaram no meio, {n_cai} caíram), com valor de mercado do Transfermarkt e, como segunda fonte, do Wyscout; {ano_parcial} fica fora de toda conta",
    lac={
        "k_quartil": D("inteiro", "etapa_1.quartis[quartil=4].n / n_anos", ["etapa_1.quartis", "etapa_1.curva_top_k.anos"]),
        "cai_q4": N("inteiro_por_extenso_se_zero", "etapa_1.quartis[].cairam", "quartil 4"),
        "cai_q4_wyscout": N("inteiro", "etapa_1.sensibilidade_fonte_valor.rebaixados_no_top_k"),
        "exemplo_wyscout": N("texto", "etapa_1.sensibilidade_fonte_valor.nomes", "'o CLUBE ANO, Nº'"),
        "p_q4_chance": N("chance_em_100", "etapa_1.curva_top_k_rebaixados.p_quartil"),
        "p_q4_wy_chance": N("chance_em_100", "etapa_1.sensibilidade_fonte_valor.p_quartil"),
        "auc_cm_100": N("pares_em_100", "etapa_1.auc_posto_de_valor.meio_x_cai"),
        "ano_sem_sinal_cai": D("texto", "anos com meio_x_cai_por_ano[].auc <= 0,5, vírgulas", ["etapa_1.auc_posto_de_valor.meio_x_cai_por_ano"]),
        "auc_cm_por_ano": N("texto", "etapa_1.auc_posto_de_valor.meio_x_cai_por_ano", "inteiro(100 × auc) por ano, ' / '"),
        "postos_cai_wyscout": N("texto", "etapa_1.sensibilidade_fonte_valor.postos_rebaixados_valor_total", "os três menores, vírgulas e 'e'"),
    },
    val={"k_quartil": "5", "cai_q4": "nenhum", "cai_q4_wyscout": "1", "exemplo_wyscout": "o Amazonas 2025, 5º", "p_q4_chance": "menos de 1 de cada 100 tentativas",
         "p_q4_wy_chance": "5 de cada 100 tentativas", "auc_cm_100": "75 de cada 100 pares", "ano_sem_sinal_cai": "2022", "auc_cm_por_ano": "50 / 90 / 75 / 83", "postos_cai_wyscout": "5, 6 e 6"},
    crit=[
        CONST("1. comparação declarada antes", False, papel="declarada", txt="não: quem cai contra o meio foi escolhida depois de olhar"),
        KM("p bilateral < 0,05 (quem cai contra o meio, posição de valor no ano)", "etapa_1.auc_posto_de_valor.p_meio_x_cai", papel="p", op="<", lim=0.05, v=0.003),
        CONST("4. lista da comparação com mais achados que a sorte (p do excesso < 0,05)", False, papel="lista", txt="não há lista: é um teste só"),
        KM("nenhum rebaixado no top 5 pelo Transfermarkt, sorteio < 0,05 (descrição)", "etapa_1.curva_top_k_rebaixados.p_quartil", op="<", lim=0.05, v=0.006, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "p_meio_x_cai < 0,05 E comparação escolhida depois de olhar sem lista declarada",
           "moderado_se": "impossível sem uma lista declarada de onde a comparação saia (a regra do dono pede a lista DELA acima da sorte)",
           "sem_sinal_se": "p_meio_x_cai >= 0,10",
           "proibido": ["'nunca cai'", "ancorar a frase no corte do 6º posto", "'o Guarani em 7º desmente top 5' (quem desmente é o 5º pelo Wyscout)"]},
    p=P("etapa_1.auc_posto_de_valor.p_meio_x_cai", 0.003), ceticos=True,
    rev="reconferência 14/09: moderado → fraco pela regra do dono (comparação escolhida depois de olhar só chega a moderado com lista acima da sorte E desconto do dinheiro; aqui não há lista); '1 e 5 de cada 100' escrito por inteiro; exemplo trocado para o Amazonas 2025",
    rev15="rodada sem dinheiro (15/09): segue FRACO, sem mudança de conteúdo. Sai a constante 'desconto do dinheiro: não se aplica' e, da regra do dono, o 'E desconto do dinheiro'",
    faixa_keep=True,
    rodape_ops=[("replace", "recalculado em `selos_a_coletivo.py`, conferido", "recalculado em `selos_a_coletivo.py`, conferido · **selo: FRACO na reconferência de 14/09 (antes MODERADO)**: quem cai contra o meio é comparação escolhida depois de olhar e não sai de lista nenhuma, então a regra do dono (a lista dela acima da sorte) não tem como ser cumprida")],
))
