C.append(conc(
    id="DIN-01", tema="dinheiro_e_elenco", etapa="etapa_1", selo="forte", declarada=True,
    titulo="O valor do elenco separa quem sobe, e é um dos sinais fortes do estudo (a DIN-02 é o mesmo sinal visto por outro corte)",
    frase="Quem sobe costuma ter um dos elencos mais valiosos do ano: {prom_top8} dos {n_prom} que subiram estavam entre os {k8} mais caros, {fracao_simples}. Somando os {n_anos} anos, entre os {k_quartil} elencos mais caros de cada temporada ({n_q4} no total), {sub_q4} subiram; entre os {k_quartil} mais baratos, subiu {sub_q1} e caíram {cai_q1}.",
    numero="Comparando a posição de cada time no ranking de valor do seu ano, o time que subiu tinha elenco mais caro que o que não subiu em {auc_sr_100}; contra quem caiu, em {auc_sc_100}.",
    ressalva="Não quer dizer que montar o elenco mais valioso faz subir: elenco valioso vem com torcida, estrutura e camisa, e o estudo não distingue uma coisa da outra. Estar entre os mais caros não bastou: dos {clubes_top8} elencos que eram top {k8} do seu ano, {top8_nao_subiram} não subiram ({exemplo_top1_nao_subiu}). Nem que fora do top {k8} não se sobe: {prom_fora_top8} dos {n_prom} subiram assim. Qual indicador separa mais nunca foi testado contra os outros. Em {ano_parcial}, com {rodadas_parcial} rodadas, o grupo de acesso de hoje aponta para o mesmo lado, mas só vale no fim do campeonato.",
    tecnico="acerto de pares {auc_sr} (intervalo de 95% de {ic_lo} a {ic_hi}); por ano {auc_por_ano}; deixando um ano de fora {loso}",
    extra={"descricao_em_euros": "Para ter um dos {k4} elencos mais valiosos da Série B era preciso um elenco avaliado entre {eur_k4_min} e {eur_k4_max} milhões de euros, conforme o ano; para estar entre os {k8}, entre {eur_k8_min} e {eur_k8_max} milhões. Essa régua sobe: o elenco típico da liga foi de {eur_mediana_primeiro} para {eur_mediana_ultimo} milhões de {ano_ini} a {ano_fim}, então o valor em euros de um ano não vale para o outro — o que conta é a posição no ranking do ano. Dos {n_bloco_1_4} elencos que eram top {k4} do ano, {sub_bloco_1_4} subiram e {cai_bloco_1_4} caiu; dos {n_bloco_5_8} entre o {k5}º e o {k8}º, subiram {sub_bloco_5_8} e caíram {cai_bloco_5_8}. E a posição de valor não decide sozinha: contando os times a até duas posições de valor de cada um que subiu, {vizinhos_2_por_sobe} não subiram para cada um que subiu (a até uma posição, {vizinhos_1_por_sobe}). Valor de mercado não é quanto se gastou."},
    universo=UNIVERSOS["clube_valor"],
    lac={
        "prom_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].promovidos_acumulados"),
        "k8": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.k"),
        "k4": G("inteiro", "etapa_1.curva_top_k.curva[k=4].k"),
        "fracao_simples": D("texto", "prom_top8/n_prom reduzida a 'N em cada M' quando M <= 5", ["prom_top8", "n_prom"]),
        "n_anos": G("contagem_da_lista", "etapa_1.curva_top_k.anos"),
        "k_quartil": D("inteiro", "etapa_1.quartis[quartil=4].n / n_anos", ["etapa_1.quartis", "n_anos"]),
        "n_q4": G("inteiro", "etapa_1.quartis[quartil=4].n"),
        "sub_q4": G("inteiro", "etapa_1.quartis[quartil=4].subiram"),
        "sub_q1": G("inteiro", "etapa_1.quartis[quartil=1].subiram"),
        "cai_q1": N("inteiro", "etapa_1.quartis[].cairam", "quartil 1"),
        "auc_sr_100": G("pares_em_100", "etapa_1.auc_posto_de_valor.sobe_x_resto"),
        "auc_sc_100": G("pares_em_100", "etapa_1.auc_posto_de_valor.sobe_x_cai"),
        "clubes_top8": G("inteiro", "etapa_1.curva_top_k.curva[k=8].clubes_no_top_k"),
        "top8_nao_subiram": D("inteiro", "clubes_no_top_k - promovidos_acumulados em curva[k=8]", ["etapa_1.curva_top_k.curva"]),
        "exemplo_top1_nao_subiu": N("texto", "etapa_1.top4_de_valor.por_ano[].posicao_final", "o posto 1 que não subiu: 'o mais caro de ANO, o CLUBE, terminou em Nº'"),
        "prom_fora_top8": D("inteiro", "promovidos com posto_valor > k8", ["etapa_1.curva_top_k.promovidos"]),
        "rodadas_parcial": G("inteiro", "etapa_1.fora_da_amostra_2026.J"),
        "auc_sr": G("dec2", "etapa_1.auc_posto_de_valor.sobe_x_resto"),
        "ic_lo": N("dec2", "etapa_1.auc_posto_de_valor.ic95", "[0]"),
        "ic_hi": N("dec2", "etapa_1.auc_posto_de_valor.ic95", "[1]"),
        "auc_por_ano": N("texto", "etapa_1.auc_posto_de_valor.por_ano", "auc_sobe_x_resto por ano, dec2 separados por ' / '"),
        "loso": G("dec2", "etapa_1.auc_posto_de_valor.loso_sobe_x_resto"),
        "eur_k4_min": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=4, menor ano"),
        "eur_k4_max": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=4, maior ano"),
        "eur_k8_min": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=8, menor ano"),
        "eur_k8_max": N("milhoes_inteiro", "etapa_1.curva_top_k.valor_do_posto_k_por_ano", "k=8, maior ano"),
        "eur_mediana_primeiro": N("milhoes_dec1", "etapa_1.valor_mediano_da_liga_por_ano", "primeiro ano"),
        "eur_mediana_ultimo": N("milhoes_dec1", "etapa_1.valor_mediano_da_liga_por_ano", "último ano"),
        "n_bloco_1_4": N("inteiro", "etapa_1.blocos_de_posto", "posto 1-4: n"),
        "sub_bloco_1_4": N("inteiro", "etapa_1.blocos_de_posto", "posto 1-4: subiram"),
        "cai_bloco_1_4": N("inteiro_por_extenso_se_zero", "etapa_1.blocos_de_posto", "posto 1-4: cairam"),
        "n_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: n"),
        "k5": N("inteiro", "etapa_1.blocos_de_posto", "primeiro posto do bloco 5-8"),
        "sub_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: subiram"),
        "cai_bloco_5_8": N("inteiro", "etapa_1.blocos_de_posto", "posto 5-8: cairam"),
        "vizinhos_2_por_sobe": N("dec1", "etapa_1.vizinhos_de_valor", "ate=2: por_promovido"),
        "vizinhos_1_por_sobe": N("dec1", "etapa_1.vizinhos_de_valor", "ate=1: por_promovido"),
    },
    val={"fracao_simples": "3 em cada 4", "k_quartil": "5", "cai_q1": "8", "top8_nao_subiram": "20", "exemplo_top1_nao_subiu": "o mais caro de 2023, o Ceará, terminou em 11º",
         "prom_fora_top8": "4", "ic_lo": "0,70", "ic_hi": "0,94", "auc_por_ano": "1,00 / 0,72 / 0,84 / 0,75",
         "eur_k4_min": "18", "eur_k4_max": "25", "eur_k8_min": "14", "eur_k8_max": "20", "eur_mediana_primeiro": "12,5", "eur_mediana_ultimo": "18,0",
         "n_bloco_1_4": "16", "sub_bloco_1_4": "10", "cai_bloco_1_4": "nenhum", "n_bloco_5_8": "16", "k5": "5", "sub_bloco_5_8": "2", "cai_bloco_5_8": "2",
         "vizinhos_2_por_sobe": "2,5", "vizinhos_1_por_sobe": "1,3"},
    crit=[
        CONST("1. teste declarado antes (baseline do valor do elenco): quem sobe contra o meio na posição de valor do ano", True, papel="declarada", txt="sim"),
        KM("p bilateral < 0,05", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="p", op="<", lim=0.05),
        KM("2. firme: teste único declarado, q = p < 0,05", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: cada ano sozinho, acerto de pares acima de 0,5", "etapa_1.auc_posto_de_valor.por_ano", papel="conf", op=">", lim=0.5, ag="todos", sub="auc_sobe_x_resto", v=[1.0, 0.72, 0.84, 0.75]),
        KM("3. conferência: deixando um ano de fora, acerto acima de 0,5", "etapa_1.auc_posto_de_valor.loso_sobe_x_resto", papel="conf", op=">", lim=0.5),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: cada ano sozinho e deixando um ano de fora"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum; o teste é por ano, então valem 'cada ano sozinho' e 'deixando um ano de fora')",
           "forte_se": "p_sobe_x_meio < 0,05 (teste único, q = p) E todo auc_posto_de_valor.por_ano[].auc_sobe_x_resto > 0,5 E loso_sobe_x_resto > 0,5",
           "moderado_se": "p_sobe_x_meio < 0,05 E alguma das duas conferências falha",
           "saiu_em_15_09": "o controle da cobertura do valor (p_valor_descontada_cobertura) e a constante 'o desconto do dinheiro não se aplica'",
           "proibido": ["'o que MAIS separa' sem teste de ordem", "contar 2026 como repetição", "'gasto', 'gastar', 'custa', 'orçamento' para valor de mercado", "'quase sempre'", "'o sinal mais sólido'", "'um dos três sinais fortes' (DIN-01 e DIN-02 são o mesmo sinal)", "'descontado quanto do elenco o Transfermarkt avalia' (controle da cobertura saiu em 15/09)"],
           "descricao_em_euros": "sem teste próprio: herda o selo da DIN-01 (não existe sexto rótulo)"},
    p=P("etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio", 0.000491), ceticos=True,
    rev="reconferência 14/09: título sem 'três sinais fortes' (DIN-01 e DIN-02 são o mesmo sinal), 'grupo de acesso' no lugar de G4, universo e critérios escritos; o p de quem sobe contra o meio já estava gravado em valor_por_setor.setores[total]",
    rev15="rodada sem dinheiro (15/09): segue FORTE. Sai o controle da cobertura do valor (sem preço = valor baixo, decisão do dono de 14/09) e a frase 'descontado quanto do elenco o Transfermarkt avalia'; teste declarado p 0,0005 (teste único: q = p), acerto acima de 0,5 em todo ano e 0,81 deixando um ano de fora. Fica fora das cinco até o gerador gravar `etapa_1.auc_posto_de_valor.por_ano`",
    faixa_keep=True,
    rodape_ops=[("replace", " · descontada a cobertura p 0,005, AUC 0,78", " · a cobertura do valor (quanto do elenco tem preço) fica descrita na etapa 1 e deixou de ser controle em 15/09"),
                ("append", " · o p de quem sobe contra o meio já está gravado em `etapa_1.valor_por_setor.setores[setor=total].p_sobe_x_meio` (0,00049); faltam gravar `auc_posto_de_valor.ic95` e `.por_ano`")],
))
