C.append(conc(
    id="DIN-04", tema="dinheiro_e_elenco", etapa="etapa_1", selo="sem_sinal", declarada=True, regime="propria: sem sinal",
    titulo="Não se viu a defesa de quem sobe valer mais do que a parte do elenco que ela ocupa",
    frase="Contando por jogador, a defesa de quem sobe tem um índice de {idx_def_sobe} (a fatia do valor dividida pela fatia de jogadores; um é valor na proporção da gente), contra {idx_def_meio} no meio da tabela, de {ano_ini} a {ano_fim}. Não se viu diferença: o acaso produziria algo assim em {p_idx_chance}, e com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="Em euros, a defesa de quem sobe fica com {pct_def_sobe}% do valor do elenco, contra {pct_def_meio}% no meio (olhando só a defesa, o acaso produziria isso em {p_bruto_chance}; contando os {n_setores} setores, já não dá para descartar a sorte), e ela tem {jog_def_sobe}% dos jogadores, contra {jog_def_meio}%.",
    ressalva="Não quer dizer 'invista na defesa para subir', nem que o ataque de quem sobe vale menos: vale mais em euros, só ocupa uma fatia menor de um bolo maior. Varia muito: {exemplo_min_max}. {sobe_abaixo_meio} dos {n_prom} que subiram tinham fatia em euros abaixo do time típico do meio.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "idx_def_sobe": G("dec2", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].indice_mediano_sobe"),
        "idx_def_meio": G("dec2", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].indice_mediano_meio"),
        "p_idx_chance": G("chance_em_100", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto"),
        "pct_def_sobe": G("pct_inteiro", "etapa_1.valor_por_setor.setores[setor=defesa].pct_do_elenco_mediano_sobe"),
        "pct_def_meio": G("pct_inteiro", "etapa_1.valor_por_setor.setores[setor=defesa].pct_do_elenco_mediano_meio"),
        "n_setores": G("inteiro", "etapa_1.valor_por_setor.particao.testes"),
        "p_bruto_chance": G("chance_em_100", "etapa_1.valor_por_setor.particao.setores[setor=defesa].p_bruto"),
        "jog_def_sobe": G("pct_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].pct_dos_jogadores_mediano_sobe"),
        "jog_def_meio": G("pct_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].pct_dos_jogadores_mediano_meio"),
        "exemplo_min_max": N("texto", "etapa_1.valor_por_setor.por_clube", "no último ano, o promovido de menor e o de maior pct_defesa: 'em ANO subiram X com N% na defesa e Y com M%'"),
        "sobe_abaixo_meio": N("inteiro", "etapa_1.valor_por_setor.por_clube", "promovidos com pct_defesa abaixo da mediana do meio"),
    },
    val={"exemplo_min_max": "em 2025 subiram o Coritiba com 22% na defesa e a Chapecoense com 44%", "sobe_abaixo_meio": "5"},
    crit=[
        KM("pergunta do título, por jogador: índice da defesa, quem sobe contra o meio, p >= 0,10", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto", papel="p", op=">=", lim=0.10),
        KM("contando os 4 setores, por jogador (q < 0,05; descrição)", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].q_bh", op="<", lim=0.05, decide=False),
        KM("fatia em euros, p < 0,05 (descrição: o título lê por jogador, decisão do coordenador de 14/09)", "etapa_1.valor_por_setor.particao.setores[setor=defesa].p_bruto", op="<", lim=0.05, decide=False),
        KM("fatia em euros, contando os 4 setores (q < 0,05; descrição)", "etapa_1.valor_por_setor.particao.setores[setor=defesa].q_bh", op="<", lim=0.05, decide=False),
    ],
    regra_propria=[("sem_sinal", {0: True})],
    regra={"regua": "régua final de 15/09, sem sinal: p >= 0,10 na pergunta do título",
           "familia": "etapa_1.valor_por_setor.ponderado_por_jogador.particao (4 setores, BH), a mesma leitura por jogador da decisão da etapa 1",
           "sem_sinal_se": "ponderado_por_jogador.particao.setores[defesa].p_bruto >= 0,10",
           "descreve": "a fatia em euros (valor_por_setor.particao.setores[defesa]) fica descrita: p < 0,05 olhando só a defesa e q >= 0,05 nos 4 setores",
           "saiu_em_15_09": "o desconto do valor total (p_liquido_do_valor_total)",
           "proibido": ["tratar q_bh como chance de acaso", "'gasta'", "'invista na defesa'", "'é a defesa ter mais gente' como fato (a diferença de gente não foi testada)"]},
    p=P("etapa_1.valor_por_setor.ponderado_por_jogador.particao.setores[setor=defesa].p_bruto", 0.26), ceticos=True,
    rev="reconferência 14/09: universo, critérios e anos na frase",
    rev15="rodada sem dinheiro (15/09): FRACO → SEM SINAL. Relida por jogador (decisão do coordenador, a mesma da etapa 1): o índice da defesa (fatia do valor ÷ fatia de jogadores) dá p 0,26 e q 0,94, 'não se viu'. A fatia em euros (p 0,036, q 0,144) fica descrita no número. Sai o desconto do valor total. Título novo, pela pergunta por jogador",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 · leitura por jogador (`etapa_1.valor_por_setor.ponderado_por_jogador`, declarada antes de medir em 14/09, sem desconto pelo valor do elenco): índice da defesa (fatia do valor ÷ fatia de jogadores) mediano 0,97 em quem sobe, 0,86 no meio e 0,89 em quem cai; posto no ano, Mann-Whitney sobe x meio p 0,26, q BH nos 4 setores 0,94 · fatia em euros (`valor_por_setor.particao`): medianas 33,9 / 27,4 / 27,6, p 0,036, q 0,144 · fatia de jogadores da defesa 33,1% contra 31,7% · por ano sobe/meio na fatia em euros 28,6/25,6 · 30,6/28,2 · 41,2/29,7 · 33,9/21,9 · na conta de 14/09 o selo fraco vinha também do desconto do valor total (p 0,20), que saiu da régua · onde ver na aba: etapa 1 · faixa de pontos: não medido",
))
