C.append(conc(
    id="DIN-05", tema="dinheiro_e_elenco", etapa="etapa_1", selo="sem_sinal", declarada=True, regime="propria: sem sinal",
    titulo="Setor por setor, não se viu o valor dizer algo além do valor do elenco inteiro",
    frase="Contando por jogador, não se viu nenhum dos {n_setores} setores de quem sobe com uma parte do valor diferente da parte de gente que ocupa, de {ano_ini} a {ano_fim}: no setor mais perto do limite, {setor_menor_p}, o acaso produziria a diferença em {p_menor_chance}. Com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    numero="O valor por jogador de quem sobe é maior na defesa ({eur_j_def_sobe} mil euros contra {eur_j_def_meio} no meio da tabela) e no ataque ({eur_j_ata_sobe} contra {eur_j_ata_meio}), no mesmo lado da DIN-01, sem selo próprio. Contra todos os outros times, o valor da defesa acerta {auc_def}, o do meio-campo {auc_meio}, o do ataque {auc_ataque} e o do elenco inteiro {auc_total} de cada 100 pares.",
    ressalva="Não quer dizer 'invista na defesa', nem que quem sobe acerta num setor específico, nem que o setor e o elenco inteiro dizem a mesma coisa: o estudo não tem tamanho para ordenar os dois (DIN-06).",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "n_setores": G("inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.testes"),
        "setor_menor_p": G("texto", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.setor"),
        "p_menor_chance": G("chance_em_100", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto"),
        "eur_j_def_sobe": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].eur_por_jogador_mediano_sobe"),
        "eur_j_def_meio": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].eur_por_jogador_mediano_meio"),
        "eur_j_ata_sobe": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].eur_por_jogador_mediano_sobe"),
        "eur_j_ata_meio": G("milhares_inteiro", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].eur_por_jogador_mediano_meio"),
        "auc_def": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=defesa].auc_sobe_x_resto"),
        "auc_meio": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=meio].auc_sobe_x_resto"),
        "auc_ataque": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=ataque].auc_sobe_x_resto"),
        "auc_total": G("pares_numero", "etapa_1.valor_por_setor.setores[setor=total].auc_sobe_x_resto"),
    },
    crit=[
        KM("pergunta do título, por jogador: menor p entre os 4 setores (índice do setor), p >= 0,10", "etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto", papel="p", op=">=", lim=0.10),
        KM("valor por jogador maior na defesa, contando os 4 setores (q < 0,05; descrição sem selo próprio)", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=defesa].q_bh_sobe_x_meio", op="<", lim=0.05, decide=False),
        KM("valor por jogador maior no ataque, contando os 4 setores (q < 0,05; descrição sem selo próprio)", "etapa_1.valor_por_setor.ponderado_por_jogador.setores[setor=ataque].q_bh_sobe_x_meio", op="<", lim=0.05, decide=False),
    ],
    regra_propria=[("sem_sinal", {0: True})],
    regra={"regua": "régua final de 15/09, sem sinal: p >= 0,10 na pergunta do título",
           "pergunta": "o setor diz algo além do valor do elenco? — lida pela partição por jogador (declaracoes_novas.din04_din05_por_jogador)",
           "sem_sinal_se": "ponderado_por_jogador.particao.menor_p.p_bruto >= 0,10",
           "descreve": "o valor por jogador maior na defesa e no ataque (q 0,0024) vai no mesmo lado da DIN-01 e não vira selo próprio: não contar o mesmo achado duas vezes nem sugerir 'invista na defesa'",
           "proibido": ["pôr no mesmo número AUC sobe x resto e sobe x meio", "'custa'", "'o setor não diz nada que o total não diga' (a DIN-06 não deixa ordenar)", "'é o mesmo dinheiro' e 'é o valor do elenco inteiro visto por setor' (equivalência afirmada como fato)", "'invista na defesa'"]},
    p=P("etapa_1.valor_por_setor.ponderado_por_jogador.particao.menor_p.p_bruto", 0.26), ceticos=True,
    rev="reconferência 14/09: ressalva e número sem afirmar equivalência que a DIN-06 não deixa afirmar; q derivado dos p gravados. Conserto final 14/09: o título ('é o mesmo dinheiro') e a frase ('é o valor do elenco inteiro visto por setor') ainda afirmavam a equivalência; viraram 'não se viu'",
    rev15="rodada sem dinheiro (15/09): FRACO → SEM SINAL. A pergunta do título ('algo além do valor do elenco') passa a ser lida pela partição por jogador (decisão do coordenador): menor p 0,26 nos 4 setores, 'não se viu'. O valor por jogador maior na defesa e no ataque (q 0,0024) fica como descrição no mesmo lado da DIN-01, sem selo próprio. O critério antigo lia a DIN-04 fraca por causa do desconto, que saiu",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 · partição por jogador (`etapa_1.valor_por_setor.ponderado_por_jogador.particao`): índice do setor (fatia do valor ÷ fatia de jogadores), Mann-Whitney sobe x meio no posto do ano, p goleiro 0,87 · defesa 0,26 · meio-campo 0,99 · ataque 0,47; q BH 0,99 / 0,94 / 0,99 / 0,94 · valor por jogador (`ponderado_por_jogador.setores`), medianas sobe / meio em mil euros: goleiro 170 / 109, defesa 428 / 250, meio-campo 396 / 261, ataque 513 / 285; q BH sobe x meio 0,19 / 0,0024 / 0,051 / 0,0024 · valor mediano do setor sobe / meio: defesa 7,9 / 3,9 mi €; meio-campo 5,8 / 4,7; ataque 7,2 / 4,8 · AUC sobe x resto goleiro / defesa / meio / ataque 0,64 / 0,84 / 0,75 / 0,78 · `etapa_1.valor_por_setor.setores` · onde ver na aba: etapa 1 · faixa de pontos: não medido",
))
