C.append(conc(
    id="ELE-07", tema="dinheiro_e_elenco", etapa="etapa_2", selo="fraco", declarada=False,
    titulo="Manter a base e trazer menos reforços: diferença pequena, com {n_sobe_base} times que subiram",
    frase="De {ano_ini_base} a {ano_fim}, entre os {n_base} clubes que já estavam na Série B no ano anterior ({n_sobe_base} subiram, {n_meio_base} ficaram no meio, {n_cai_base} caíram), quem subiu manteve {ficou_sobe}% do elenco do ano anterior, contra {ficou_meio}% no meio da tabela; quem caiu trouxe {novos_cai} jogadores novos no ano, contra {novos_sobe} em quem subiu. É um sinal {selo}: as duas medidas foram montadas depois de olhar, nenhuma das {n_testes_base} comparações passa na conta dos muitos testes, e uma lista de duas medidas não tem como ficar acima da sorte.",
    numero="Parte que ficou, quem sobe contra o meio: o acaso produziria a diferença em {p_ficou_chance}. Novos, quem sobe contra quem cai: em {p_novos_chance}.",
    ressalva="Não quer dizer 'mantenha a base e você sobe', nem 'reformular faz cair'. A contagem de novos é do ano inteiro e inclui quem chegou no meio da temporada: time que está perdendo contrata mais, então pode ser consequência. Para quem chega da Série A ou da C isso não foi medido: o dado não existe.",
    universo="{n_base} clubes de {ano_ini_base} a {ano_fim} que já estavam na Série B no ano anterior ({n_sobe_base} subiram, {n_meio_base} ficaram no meio, {n_cai_base} caíram); {ano_parcial} fica fora de toda conta",
    lac={
        "n_sobe_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_sobe"),
        "ano_ini_base": N("ano", "etapa_2.elenco_base.anos", "[0]"),
        "n_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n"),
        "n_meio_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_meio"),
        "n_cai_base": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: n_cai"),
        "ficou_sobe": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: mediana_sobe"),
        "ficou_meio": N("inteiro", "etapa_2.elenco_base.linhas", "pctFicou: mediana_meio"),
        "novos_cai": N("inteiro", "etapa_2.elenco_base.linhas", "novos: mediana_cai"),
        "novos_sobe": N("inteiro", "etapa_2.elenco_base.linhas", "novos: mediana_sobe"),
        "n_testes_base": N("inteiro", "etapa_2.elenco_base.bh_testes"),
        "p_ficou_chance": N("chance_em_100", "etapa_2.elenco_base.linhas", "pctFicou: p_bruto_SM"),
        "p_novos_chance": N("chance_em_100", "etapa_2.elenco_base.linhas", "novos: p_bruto_SC"),
    },
    val={"n_sobe_base": "6", "ano_ini_base": "2023", "n_base": "36", "n_meio_base": "22", "n_cai_base": "8", "ficou_sobe": "44", "ficou_meio": "31", "novos_cai": "42", "novos_sobe": "30", "n_testes_base": "6",
         "p_ficou_chance": "4 de cada 100 tentativas", "p_novos_chance": "3 de cada 100 tentativas"},
    crit=[
        CONST("1. comparações declaradas antes", False, papel="declarada", txt="não: as duas medidas e as comparações foram montadas depois de olhar"),
        KM("p bruto < 0,05 em alguma das duas (parte que ficou, quem sobe contra o meio; novos, quem sobe contra quem cai)", "etapa_2.elenco_base.linhas", papel="p", op="<", lim=0.05, ag="algum", sub=["p_bruto_SM", "p_bruto_SC"],
           v={"pctFicou": 0.0416, "novos": 0.028}, txt="parte que ficou 0,042; novos 0,028"),
        CONST("4. lista acima da sorte (regra do dono)", False, papel="lista", txt="não dá: duas medidas não formam lista"),
        KM("conta dos 6 testes (q < 0,05; descrição)", "etapa_2.elenco_base.linhas", op="<", lim=0.05, ag="algum", sub=["q_SM", "q_SC", "q_CM"], v=0.083, txt="menor q 0,083", decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "algum p bruto < 0,05 E comparação montada depois de olhar sem lista acima da sorte", "sem_sinal_se": "todo p bruto >= 0,10",
           "familia": "elenco_base (2 colunas × comparações SM, SC, CM = 6 testes de BH), fora do catálogo e fora das 293",
           "saiu_em_15_09": "os p descontados do valor do elenco (0,045 a 0,089 conforme a conta; não decidiam o selo)",
           "proibido": ["'resiste ao dinheiro'", "'não vale para quem chega da A ou da C' (não medido)"]},
    p=P("etapa_2.elenco_base.linhas[indicador=pctFicou].p_bruto_SM", 0.0416), ceticos=True,
    rev="reconferência 14/09: o desconto pela conta da casa (posto do ano sobre o percentil de valor) dá 0,045 e não 0,050; o 0,050 e o 0,089 vêm de outras duas contas (`v578.py`); o selo segue fraco pela regra da comparação montada depois de olhar e pelos 6 testes",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Saem os p descontados do valor do elenco da frase e dos critérios; decide a regra da comparação escolhida depois de olhar (sem lista)",
    faixa_keep=True,
    rodape_ops=[
        ("replace", "descontado o dinheiro 0,050 (resíduo do posto) a 0,089 (resíduo do valor cru)", "na conta de 14/09, descontado o valor do elenco: 0,045 pela conta da casa, 0,050 e 0,089 por outras duas (`c78_colocacao_base.py`, `r13_varios.py`, `v578.py`); saiu da régua em 15/09 e não decidia o selo"),
        ("replace", "nenhuma das 6 comparações passa no BH", "nenhuma das 6 comparações (2 colunas × quem sobe contra o meio, quem sobe contra quem cai, quem cai contra o meio) passa no BH: menor q 0,083 (`r13_varios.py`)"),
        ("replace", "sobe x cai Welch 0,014, Mann-Whitney 0,024, descontado o dinheiro 0,055 a 0,096", "sobe x cai Welch 0,014, Mann-Whitney 0,024, posto 0,028")],
))
