C.append(conc(
    id="ELE-01", tema="dinheiro_e_elenco", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem cai roda muito mais gente",
    frase="Quem cai usa muito mais jogadores no ano: {usados_cai} em média, contra {usados_sobe} em quem sobe e {usados_meio} no meio da tabela, de {ano_ini} a {ano_fim}; o rastreamento físico conta a mesma história por outra fonte ({fis_cai} jogadores com minutos medidos, contra {fis_sobe} e {fis_meio}). É um sinal {selo}: na comparação declarada antes, quem cai contra quem sobe, a sorte produziria essa diferença em {p_sc_chance}; contando os {n_familia_elenco} números do elenco, {frase_q_sc}; mas não houve como conferir por outro caminho, porque não há escalação por rodada nem essa coluna em {periodo_antigo}.",
    numero="Contra o meio da tabela a diferença também aparece (o acaso a produziria em {p_cm_chance}); essa comparação foi escolhida depois de olhar, mas a lista do elenco nela tem mais achados do que a sorte, então pela regra do dono também seria moderada. Entre quem sobe e o meio não se viu diferença; com {n_sobe} contra {n_meio}, {frase_tamanho}.",
    ressalva="Não quer dizer que rodar muito faz cair nem que elenco curto faz subir: time que está perdendo pode trocar de técnico e contratar no meio do ano, e o estudo não tem esse dado nem escalação por rodada para distinguir uma coisa da outra. As duas contagens andam juntas, então não são duas confirmações.",
    universo=UNIVERSOS["clube"],
    lac={
        "usados_cai": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_cai"),
        "usados_sobe": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_sobe"),
        "usados_meio": G("inteiro", "etapa_2.linhas[indicador=atletas_usados].m_meio"),
        "fis_cai": G("dec1", "etapa_1.controle_n_atletas.media_cai"),
        "fis_sobe": G("dec1", "etapa_1.controle_n_atletas.media_sobe"),
        "fis_meio": G("dec1", "etapa_1.controle_n_atletas.media_meio"),
        "p_sc_chance": G("chance_em_1000", "etapa_2.linhas[indicador=atletas_usados].p_bruto_SC"),
        "frase_q_sc": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=atletas_usados].q_SC"]),
        "p_cm_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CM", "atletas_usados"),
    },
    val={"frase_q_sc": "é firme", "p_cm_chance": "1 de cada 1.000 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=atletas_usados].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=atletas_usados].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=atletas_usados].q_SC", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem escalação por rodada (1º turno) e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra quem cai, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem cai contra o meio (escolhida depois; descrição): lista do elenco acima da sorte", "etapa_3.por_familia.elenco.excesso.CM.bruto.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "comparacao_da_frase": "SC (sobe x cai), declarada no catálogo",
           "forte_se": "q_SC < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "moderado_se": "q_SC < 0,05 sem conferência testável, OU q_SC >= 0,05 com a lista do elenco SC acima da sorte", "fraco_se": "q_SC >= 0,05 E lista no nível da sorte", "sem_sinal_se": "p_bruto_SC >= 0,10",
           "parte_CM": "escolhida depois de olhar; pela regra do dono chegaria a moderado (lista do elenco CM 5 contra 0, p 0,0067); não muda o selo",
           "proibido": ["'quase certamente é consequência'", "'e não é o valor do elenco'", "'time que perde troca de técnico' como fato", "'continua entre times de valor parecido'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=atletas_usados].p_bruto_SC", 0.00019), ceticos=True,
    rev="reconferência 14/09: parte quem cai contra o meio reavaliada pela regra do dono (lista CM do elenco 5 contra 0, p 0,006; descontado 0,002): também moderada, sem efeito no selo",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre times de valor parecido' e 'não se viu o mesmo clube repetir'. Motivo do moderado: firme (q 0,0005) sem conferência testável; sem essa cláusula a máquina daria forte",
    faixa_keep=True,
    rodape_ops=[("replace", "cai x meio (escolhida depois de olhar, só descrição): Welch no posto p 0,001 (Mann-Whitney 0,0003), descontado o valor p 0,002, q 0,006 (líquido 0,011)",
                 "cai x meio (escolhida depois de olhar): Welch no posto p 0,001 (Mann-Whitney 0,0003), q 0,006; a lista do elenco nessa comparação tem 5 achados contra 0 do sorteio (p do excesso 0,006 em `r4_saida.json`, 0,0067 no dado novo), então pela regra do dono também seria moderada — não muda o selo")],
))
