C.append(conc(
    id="ELE-06", tema="dinheiro_e_elenco", etapa="etapa_6", selo="sem_sinal", declarada=False, regime="propria: contas da mesma pergunta",
    titulo="Não se viu a colocação de um ano repetir no ano seguinte, no limite",
    frase="Entre os clubes que ficaram na Série B ({n_pares_pos} pares de anos seguidos), dos {n_5_8} que terminaram entre o {faixa_a_ini}º e o {faixa_a_fim}º, {sub_5_8} subiram e {cai_5_8} caíram no ano seguinte; dos {n_13_16} entre o {faixa_b_ini}º e o {faixa_b_fim}º, {sub_13_16} subiram e {cai_13_16} caíram. Não se viu a posição de um ano andar com a do seguinte: o acaso produziria a relação em {p_posicao_chance}, no limite. Ela apareceu nos pares que começam de {per1} e não se viu nos que começam de {per2}.",
    numero="O aproveitamento vai para o mesmo lado e passa do corte ({p_aprov_chance}). As duas contas vão para o mesmo lado, nenhuma foi declarada antes de olhar e os dois períodos discordam: vale o selo mais fraco, sem sinal.",
    ressalva="Não quer dizer que a campanha anterior não conta: quem terminou embaixo caiu mais ({cai_13_16} contra {cai_5_8}), só que, com {n_13_16} contra {n_5_8}, não se viu diferença além do acaso. Quem subiu ou caiu sai da Série B e não entra na conta.",
    universo="{n_pares_pos} pares de anos seguidos de clubes que ficaram na Série B, de {t_ini}→{t_ini1} a {t_fim}→{t_fim1} (das {n_antigo} clube-temporadas de {periodo_antigo} e das {n_clube_temporadas} de {ano_ini} a {ano_fim}); {ano_parcial} fica fora de toda conta",
    lac={
        "n_pares_pos": N("inteiro", "etapa_6.colocacao.n_pares"),
        "n_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "n_5_8"),
        "faixa_a_ini": D("inteiro", "bloco declarado em declaracoes_novas.colocacao_t_t1 (5-8): início", []),
        "faixa_a_fim": D("inteiro", "bloco declarado (5-8): fim", []),
        "sub_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "sub_5_8"),
        "cai_5_8": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "cai_5_8"),
        "n_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "n_13_16"),
        "faixa_b_ini": D("inteiro", "bloco declarado (13-16): início", []),
        "faixa_b_fim": D("inteiro", "bloco declarado (13-16): fim", []),
        "sub_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "sub_13_16"),
        "cai_13_16": N("inteiro", "etapa_6.colocacao.por_faixa_de_posicao", "cai_13_16"),
        "p_posicao_chance": N("chance_em_100", "etapa_6.colocacao.p_posicao"),
        "per1": N("texto", "etapa_6.colocacao.por_periodo", "t[0] 'A a B' do primeiro período"),
        "per2": N("texto", "etapa_6.colocacao.por_periodo", "t[1] 'A a B' do segundo período"),
        "p_aprov_chance": N("chance_em_100", "etapa_6.colocacao.p_aproveitamento"),
        "t_ini": D("ano", "primeiro ano t dos pares", ["etapa_6.colocacao.por_periodo"]),
        "t_ini1": D("ano", "t_ini + 1", ["t_ini"]),
        "t_fim": D("ano", "último ano t dos pares", ["etapa_6.colocacao.por_periodo"]),
        "t_fim1": D("ano", "t_fim + 1", ["t_fim"]),
    },
    val={"n_pares_pos": "84", "n_5_8": "28", "faixa_a_ini": "5", "faixa_a_fim": "8", "sub_5_8": "6", "cai_5_8": "6", "n_13_16": "28", "faixa_b_ini": "13", "faixa_b_fim": "16", "sub_13_16": "2", "cai_13_16": "11",
         "p_posicao_chance": "6 de cada 100 tentativas", "per1": "2018 a 2020", "per2": "2021 a 2024", "p_aprov_chance": "2 de cada 100 tentativas",
         "t_ini": "2018", "t_ini1": "2019", "t_fim": "2024", "t_fim1": "2025"},
    crit=[
        KM("conta do título: posição em t contra t+1, p < 0,05", "etapa_6.colocacao.p_posicao", papel="p", op="<", lim=0.05, v=0.0642, txt="0,064 (zona cinzenta)"),
        KM("outra conta da mesma pergunta: aproveitamento em t contra t+1, p < 0,05", "etapa_6.colocacao.p_aproveitamento", papel="outra", op="<", lim=0.05, v=0.025),
        CONST("1. alguma das duas contas declarada antes", False, papel="declarada", txt="não"),
        KM("os dois períodos concordam (posição com p < 0,05 nos dois)", "etapa_6.colocacao.por_periodo", papel="conf", op="<", lim=0.05, ag="todos", sub="p_posicao", v=[0.025, 0.60], txt="2018-2020 p 0,025; 2021-2024 p 0,60"),
    ],
    regra_propria=[("sem_sinal", {0: False, 1: True, 2: False, 3: False})],
    regra={"regua": "régua final de 15/09, regra própria das contas da mesma pergunta (o assunto é a repetição do clube: fica, com selo)",
           "sem_sinal_se": "p_posicao >= 0,05 (zona cinzenta, conta do título) E o aproveitamento passa E nenhuma das duas foi declarada antes E os períodos discordam: vale o selo mais fraco entre fraco (aproveitamento, escolhida depois e sem lista) e sem sinal (posição)",
           "fraco_se": "a conta declarada antes der fraco (não há conta declarada antes)",
           "saiu_em_15_09": "o aproveitamento descontado o valor nos 36 pares (não decidia o selo) e a frase do valor do elenco que se repete",
           "proibido": ["'ajuda pouco' (causa)", "'não separa isso do acaso'", "'e não de 2021 a 2025' (p 0,60: 'não se viu')", "ρ na frase de reunião", "'some quando se desconta o dinheiro'"]},
    p=P("etapa_6.colocacao.p_posicao", 0.0642), ceticos=True,
    rev="reconferência 14/09: fraco → sem sinal. O aproveitamento descontado o dinheiro some (parcial 0,24, p 0,16, nos 36 pares; resíduo do valor nas 80 temporadas, ρ 0,10, p 0,55); a posição, conta do título, fica no limite (0,064); nenhuma das duas foi declarada antes e vale a mais fraca",
    rev15="rodada sem dinheiro (15/09): segue SEM SINAL. O assunto é a repetição da colocação do clube, então a conclusão fica com o selo. Saem o aproveitamento descontado o valor e a frase 'o valor do elenco se repete com força'; decide a regra das contas da mesma pergunta (posição 0,064, aproveitamento 0,025, nenhuma declarada, períodos discordam)",
    faixa_keep=True,
    rodape_ops=[("replace", "selo pela zona cinzenta, com sinal no aproveitamento e períodos que discordam", "**selo: SEM SINAL** (reconferência de 14/09, antes FRACO) · a posição é a conta do título e fica no limite; o aproveitamento passa; nenhuma das duas foi declarada antes e os períodos discordam: vale a mais fraca · na conta de 14/09 entrava também o aproveitamento descontado o valor nos 36 pares (0,16, `cf_num/v_ele06.py`); saiu da régua em 15/09 e não mudava o selo")],
))
