C.append(conc(
    id="ELE-03", tema="dinheiro_e_elenco", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe dá mais minutos a estrangeiros",
    frase="{est_sobe}% dos minutos, contra {est_meio}% no meio da tabela, de {ano_ini} a {ano_fim}. É um sinal {selo}: contando os {n_familia_elenco} números do elenco, {frase_q}, e não houve como conferir por outro caminho: não há essa coluna em {periodo_antigo} nem versão por jogo.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que estrangeiro ajuda nem que atrapalha. Elenco valioso tende a dar mais minutos a estrangeiro; o estudo não separa as duas coisas. Varia muito de ano para ano: {ano_contra}, e {sobe_zero} dos {n_prom} que subiram não deram minuto nenhum a estrangeiro.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "est_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=min_estrangeiros].m_sobe"),
        "est_meio": G("pct_inteiro", "etapa_2.linhas[indicador=min_estrangeiros].m_meio"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM"),
        "frase_q": D("texto", "q_SM < 0,025: 'é firme'; 0,025 <= q_SM < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=min_estrangeiros].q_SM"]),
        "ano_contra": N("texto", "etapa_2.linhas[].media_por_ano", "min_estrangeiros: anos com média de sobe abaixo da de meio, 'em ANO quem subiu usou menos que o meio (X% contra Y%)'"),
        "sobe_zero": N("inteiro", "etapa_2.por_clube", "promovidos com min_estrangeiros = 0"),
    },
    val={"frase_q": "é firme por pouco", "ano_contra": "em 2023 quem subiu usou menos que o meio (0,5% contra 1,2%)", "sobe_zero": "3"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=min_estrangeiros].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=min_estrangeiros].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem versão por jogo e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra o meio, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável",
           "ressalva": "sem desconto e sem receita (resposta b do dono): 'elenco valioso tende a dar mais minutos a estrangeiro; o estudo não separa as duas coisas' — medido na parte 1: ρ +0,36 com o posto de valor; a medida por coluna vai para etapa_2.andam_com_o_valor",
           "saiu_em_15_09": "o critério 'desconto do dinheiro' (porta C) e, do título, '— mas estrangeiro anda junto com elenco caro' como desconto",
           "proibido": ["'a média é puxada por poucos clubes'", "'orçamento'", "'comparando times de valor de elenco parecido'", "'contrate estrangeiro'"]},
    p=P("etapa_2.linhas[indicador=min_estrangeiros].p_bruto_SM", 0.00826), ceticos=True,
    rev="reconferência 14/09: universo e critérios",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só pelo desconto do valor (p líquido 0,076). Pela régua final: firme por pouco (p 0,008, q 0,038) sem conferência testável. Sai do título '— mas estrangeiro anda junto com elenco caro'; entra a ressalva sem desconto e sem receita (resposta b do dono)",
    faixa_keep=True, rodape_ops=[("append", " · rodada sem dinheiro de 15/09: na parte 1, o posto de minutos de estrangeiros anda com o posto de valor do elenco (ρ +0,36); é o que a ressalva descreve, sem descontar")],
))
