C.append(conc(
    id="ELE-02", tema="dinheiro_e_elenco", etapa="etapa_10", selo="moderado", declarada=True,
    titulo="Quem sobe repete mais o time-base — e isto não é critério de contratação",
    frase="O XI mais usado de quem sobe joga {share_sobe}% dos minutos, contra {share_meio}% no meio da tabela e {share_cai}% em quem cai, de {ano_ini} a {ano_fim}; {sobe_acima} dos {n_prom} que subiram ficaram acima do time típico do meio. É um sinal {selo}: contando os {n_familia_elenco} números do elenco, {frase_q}, e não houve como conferir por outro caminho, porque não há escalação por rodada.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que escalar sempre os mesmos onze faz subir: o estudo não tem escalação por rodada para testar a direção, e a etapa {etapa_redescrito} marca o número como consequência do resultado; a especificação proíbe usá-lo para contratar. A concentração de minutos diz a mesma coisa com outra conta, e não é segunda confirmação.",
    universo=UNIVERSOS["clube"],
    lac={
        "share_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_sobe"),
        "share_meio": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_meio"),
        "share_cai": G("pct_inteiro", "etapa_2.linhas[indicador=share_11].m_cai"),
        "sobe_acima": N("inteiro", "etapa_2.por_clube", "promovidos com share_11 acima da mediana do meio"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=share_11].p_bruto_SM"),
        "frase_q": D("texto", "q_SM < 0,025: 'é firme'; 0,025 <= q_SM < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=share_11].q_SM"]),
        "etapa_redescrito": D("inteiro", "número de etapa_10.titulo_chave", ["etapa_10.titulo_chave"]),
    },
    val={"sobe_acima": "12", "frase_q": "é firme por pouco", "etapa_redescrito": "10"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=share_11].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=share_11].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=share_11].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem escalação por rodada (etapa_7.nao_testaveis) e sem a coluna em 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do elenco, quem sobe contra o meio, acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.elenco.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável (firme por pouco com nenhuma conferência também é moderado)",
           "nao_sobe_para_forte_porque": "o teste do primeiro turno é impossível (etapa_7.nao_testaveis) e a coluna não existe em 2018-2021: nenhuma conferência testável",
           "marca_obrigatoria": "consequência do resultado (etapa_10, lista fixa do ranking_gaps), nunca critério de encaixe",
           "fronteira_da_lista": "a lista do elenco SM está na fronteira (p do excesso 0,0502 no dado novo): não se afirma excesso, e o selo não depende disso",
           "proibido": ["'não se viu o mesmo clube repetir, então não pode ser usado como traço' (o ano seguinte saiu dos critérios em 15/09)", "'continua entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=share_11].p_bruto_SM", 0.00452), ceticos=True,
    rev="reconferência 14/09: ressalva do spec igual à do documento ('não se viu o mesmo clube repetir, então não pode ser usado como traço')",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'não se viu o mesmo clube repetir o padrão no ano seguinte'; o motivo passa a ser 'firme por pouco (q 0,038) sem conferência testável'. A marca de consequência (etapa 10) continua",
    faixa_keep=True, rodape_ops=[],
))
