C.append(conc(
    id="FIS-11", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="Os laterais de quem sobe atacam mais o espaço sem bola",
    frase="{v_sobe} corridas para espaço perigoso a cada meia hora com a bola do time, contra {v_meio} no meio da tabela, de {ano_ini} a {ano_fim}. Continua entre times que rodaram o elenco parecido e apareceu em {anos_ok} dos {n_anos} anos. É um sinal {selo}: entre {n_familia_fisico_setor} medidas físicas por setor, o número das que separam é o que a sorte produz.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer que o lateral é fisicamente melhor, nem 'contrate lateral que ataca o espaço': a medida é contada com a bola do próprio time e parece descrever o jeito de jogar (isso não foi medido).",
    universo=UNIVERSOS["fisico"],
    lac={
        "v_sobe": G("dec1", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].m_sobe"),
        "v_meio": G("dec1", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].m_meio"),
        "anos_ok": N("inteiro", "etapa_2.linhas[].media_por_ano", "fis_lateral_runs_dangerous_p30tip: anos com resíduo médio de sobe > meio"),
        "n_anos": G("contagem_da_lista", "etapa_1.curva_top_k.anos"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
    },
    val={"anos_ok": "4"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados da lateral), p < 0,05", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM do físico por setor no nível da sorte))",
           "marca": "medida condicionada à posse: descreve plano", "proibido": ["'orçamento'", "'entre times de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_lateral_runs_dangerous_p30tip].p_bruto_SM", 0.01335), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu; caminho do excesso com nível",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor; só o rodízio (p 0,014). Selo segue FRACO: q 0,58 e lista no nível da sorte (p 0,33)",
    faixa_keep=True, rodape_ops=[],
))
