C.append(conc(
    id="FIS-08", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="A zaga de quem sobe corre menos que a do meio da tabela",
    frase="Uns {dif_metros} metros a menos por jogo, por zagueiro, de {ano_ini} a {ano_fim}. A diferença continua entre times que rodaram o elenco parecido. É um sinal {selo}: entre {n_familia_fisico_setor} medidas físicas por setor, o número das que separam é o que a sorte produz, e só {sobe_com_zaga} dos {n_prom} que subiram tinham zagueiros rastreados em número suficiente.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer 'contrate zagueiro que corre pouco', nem que correr menos ajuda a subir: pode ser só um time menos atacado. As contas de distância da zaga são um achado só, não vários.",
    universo=UNIVERSOS["fisico"],
    lac={
        "dif_metros": D("inteiro", "m_meio - m_sobe de fis_zaga_distance_p90, arredondado a 50", ["etapa_2.linhas[indicador=fis_zaga_distance_p90].m_meio", "etapa_2.linhas[indicador=fis_zaga_distance_p90].m_sobe"]),
        "sobe_com_zaga": N("inteiro", "etapa_2.linhas[].n_sobe", "fis_zaga_distance_p90"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
    },
    val={"dif_metros": "150", "sobe_com_zaga": "12"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados da zaga), p < 0,05", "etapa_2.linhas[indicador=fis_zaga_distance_p90].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_zaga_distance_p90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_zaga_distance_p90].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM do físico por setor no nível da sorte))",
           "marca": "distance, m_per_min e tip da zaga contam como uma medida só", "proibido": ["'orçamento'", "'entre times de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_zaga_distance_p90].p_bruto_SM", 0.02292), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu; lacuna da sensibilidade sem corte removida (não estava no molde)",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor; só o rodízio (p 0,021). Selo segue FRACO: q 0,58 e lista no nível da sorte (p 0,33)",
    faixa_keep=True, rodape_ops=[],
))
