C.append(conc(
    id="FIS-10", tema="fisico", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="O ataque de quem sobe faz mais corridas em alta velocidade que o de quem cai; contra o meio não se viu diferença, com uma medida no limite",
    frase="De {ano_ini} a {ano_fim}, {n_bloco_sc} das {n_bloco} medidas físicas do ataque separam quem sobe de quem cai no número cru, todas para o mesmo lado, e {n_bloco_rod} delas continuam entre times que rodaram o elenco parecido. Nas corridas em alta velocidade por jogo ({hsr_sobe} contra {hsr_cai}), a medida do título, é um sinal {selo}: não resiste à conta das {n_familia_fisico_setor} medidas físicas por setor, mas essa lista, na comparação quem sobe contra quem cai, tem mais achados do que a sorte produz.",
    numero="Olhando cada medida sozinha, o acaso produziria as diferenças em {faixa_p_chance}, conforme a medida; nas corridas em alta velocidade, descontado só o rodízio, em {p_rod_chance}. Contra o meio da tabela não se viu diferença, com uma medida no limite ({nome_sm_limite}: {p_sm_limite_chance}).",
    ressalva="Não quer dizer que ataque que corre faz subir, nem que correr no ataque é o piso para não cair. Quem cai roda mais atacantes ({atac_cai} contra {atac_sobe}), e o desconto do rodízio pode levar junto uma parte real da diferença; não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}. Vai para o mesmo lado da M8, que conta por clube as medidas da nota de encaixe no ataque; o selo daqui segue a conta do catálogo declarado.",
    universo=UNIVERSOS["fisico"],
    lac={
        "n_bloco_sc": N("inteiro", "etapa_2.fis10_bloco.n_p_bruto_SC_abaixo_005"),
        "n_bloco": N("inteiro", "etapa_2.fis10_bloco.n"),
        "n_bloco_rod": D("inteiro", "linhas fis_ataque_* do catálogo com p_bruto_SC < 0,05 e p_rod_SC < 0,05", ["etapa_2.linhas"]),
        "hsr_sobe": G("dec1", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].m_sobe"),
        "hsr_cai": G("dec1", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].m_cai"),
        "faixa_p_chance": N("texto", "etapa_2.fis10_bloco", "p_bruto_SC_min e p_bruto_SC_max das linhas com p < 0,05, cada ponta por chance_em_100: 'menos de 1 a M de cada 100 tentativas'"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_rod_SC"),
        "atac_cai": G("dec1", "etapa_1.controle_n_atletas.por_setor[setor=ataque].media_cai"),
        "atac_sobe": G("dec1", "etapa_1.controle_n_atletas.por_setor[setor=ataque].media_sobe"),
        "nome_sm_limite": N("texto", "etapa_2.fis10_bloco.p_bruto_SM_min_indicador", "nome simples do glossário da linha com o menor p_bruto_SM do bloco"),
        "p_sm_limite_chance": N("chance_em_100", "etapa_2.fis10_bloco.p_bruto_SM_min"),
    },
    val={"n_bloco_sc": "12", "n_bloco": "32", "n_bloco_rod": "10", "faixa_p_chance": "menos de 1 a 4 de cada 100 tentativas", "nome_sm_limite": "corridas para a área", "p_sm_limite_chance": "5 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados do ataque), p < 0,05", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_rod_SC", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (físico por setor, quem sobe contra quem cai, p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SC < 0,05 E p_rod_SC < 0,05 E q_SC >= 0,05 E etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso < 0,05 (ou q_SC < 0,05 sem conferência testável)",
           "fraco_se": "p_bruto_SC < 0,05 E (p_rod_SC >= 0,05 OU (q_SC >= 0,05 E p_excesso SC bruto >= 0,05))",
           "forte_se": "q_SC < 0,05 E p_rod_SC < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "bloco": "etapa_2.fis10_bloco = as 32 linhas fis_ataque_* do catálogo (o setor inteiro, sem escolher colunas)",
           "outra_conta": "M8 (por clube, medidas da nota): mesmo lado; o selo segue o catálogo declarado",
           "obrigatorio": "o bloco é um achado só; dizer quantas medidas passam no cru e quantas descontado só o rodízio",
           "proibido": ["'corre mais rápido' (não é a pergunta do título)", "'no limite' para p < 0,05 (é o nome da zona cinzenta)", "'contra o meio não se viu' sem a medida no limite (corridas para a área, 0,053)",
                        "'logo abaixo do corte'", "'a lista some nos descontos'", "'entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=fis_ataque_hsr_count_p90].p_bruto_SC", 0.00351), ceticos=True,
    rev="reconferência 14/09: fraco → moderado. Aplicada a regra do excesso que a FIS-06, a FIS-08 e a FIS-11 já tinham: as corridas em alta velocidade do ataque passam nos dois descontos (0,042 e 0,049), não passam na conta das 128 (q 0,097), e a lista do físico por setor na comparação quem sobe contra quem cai tem 27 achados contra 6 (p 0,010). O bloco são as 32 linhas do ataque, e 12 passam no cru (não 8)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem o desconto do valor, 'logo abaixo do corte', 'a lista some nos descontos' e a frase 'nada sobra no ataque' (a M4 foi partida e o ataque virou a M8, moderada). Descontado só o rodízio: p 0,0049; das 12 do bloco que separam no cru, 10 continuam; q 0,097; lista quem sobe contra quem cai 27 contra 6 (p 0,0104)",
    faixa_keep=True,
    rodape_texto="**rodada sem dinheiro de 15/09** (`prototipo_novo.json`, ainda não gravado no projeto) · bloco = as 32 linhas `fis_ataque_*` do catálogo; 12 com p bruto sobe x cai < 0,05 (de 0,0035 a 0,040), e 10 delas com p < 0,05 descontado só o posto de `fis_ataque_atletas` (ficam de fora `fis_ataque_psv99_top5`, 0,17, e as corridas para a área, 0,087) · `fis_ataque_hsr_count_p90` 58,5 / 56,6 / 53,9: p 0,0035, só rodízio 0,0049, q 0,097 nas 128 · lista do físico por setor, sobe x cai: 27 contra 6, p do excesso 0,0104 no bruto e 0,0108 só com o rodízio · sobe x meio nas 12, p de 0,053 (corridas para a área, no limite) a 0,46 · na conta de 14/09 o selo passava pelo desconto do valor (0,042) e de valor e rodízio (0,049); saiu da régua · onde ver na aba: etapa 2",
))
