C.append(conc(
    id="FIS-06", tema="fisico", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="O meio-campo de quem sobe faz mais arrancadas que viram sprint",
    frase="{v_sobe} por jogo, contra {v_meio} no meio da tabela e {v_cai} em quem cai, de {ano_ini} a {ano_fim}. A diferença continua entre times que rodaram o elenco parecido. É um sinal {selo}: foram testadas {n_familia_fisico_setor} medidas físicas por setor, e o número das que separaram é o que a sorte produz; esta pode ser uma delas.",
    numero="Descontado só o rodízio, o acaso produziria a diferença em {p_rod_chance}; a lista inteira tem {obs_familia} achados, contra {nulo_familia} num sorteio típico.",
    ressalva="Não quer dizer 'contrate meia que arranca e você sobe'. Em {ano_contra} o sinal não apareceu, e não houve como conferir por outro caminho. Contra quem cai, a arrancada dos meias continua de pé contada por clube (M5).",
    universo=UNIVERSOS["fisico"],
    lac={
        "v_sobe": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_sobe"),
        "v_meio": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_meio"),
        "v_cai": G("dec2", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].m_cai"),
        "p_rod_chance": G("chance_em_100", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_rod_SM"),
        "obs_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.observado"),
        "nulo_familia": G("inteiro", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.nulo_mediana"),
        "ano_contra": N("texto", "etapa_2.linhas[].media_por_ano", "fis_meio_expl_accel_sprint_p90: anos com resíduo de sobe menor que o de meio"),
    },
    val={"ano_contra": "2024"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("5. descontado só o rodízio (atletas rastreados do meio-campo), p < 0,05", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_rod_SM", papel="rod", op="<", lim=0.05),
        KM("2. firme: conta das 128 medidas por setor (q < 0,05)", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("4. lista inteira acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.fisico_col_setor.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "declarada E p_bruto_SM < 0,05 E p_rod_SM < 0,05 E (q_SM < 0,05 OU lista do físico por setor SM com p_excesso < 0,05)",
           "fraco_se": "p_bruto_SM < 0,05 E (p_rod_SM >= 0,05 OU (q_SM >= 0,05 E lista SM no nível da sorte))",
           "forte_se": "q_SM < 0,05 E p_rod_SM < 0,05 E pelo menos uma conferência testável, todas passando (aqui não há nenhuma)",
           "proibido": ["'a melhor pista física'", "'não há físico por jogo'", "'não é marca do clube'", "'orçamento'", "'entre times de valor parecido'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=fis_meio_expl_accel_sprint_p90].p_bruto_SM", 0.00468), ceticos=True,
    rev="reconferência 14/09: 'orçamento' saiu do molde; caminho do excesso com nível (excesso.SM.bruto)",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor e a frase do clube no ano seguinte; o físico é conferido só com o rodízio (p 0,0046). Selo segue FRACO: q 0,58 e a lista quem sobe contra o meio no nível da sorte (9 contra 6, p 0,33)",
    faixa_keep=True, rodape_ops=[],
))
