C.append(conc(
    id="FIS-04", tema="fisico", etapa="etapa_3", selo="moderado", declarada=True, regime="propria: lista inteira",
    titulo="Quem sobe tem físico melhor que quem cai no número cru, e isso continua entre times que rodaram o elenco parecido",
    frase="De {ano_ini} a {ano_fim}, {n_bruto} das {n_medidas} medidas físicas separam quem sobe de quem cai no número cru, quando o acaso daria umas {esperado}, e nas duas listas (elenco e setor) isso passa do que a sorte produz. Descontado só o número de atletas rastreados, {n_rod} continuam separando, e a lista por setor ainda tem mais achados do que a sorte. É um sinal {selo}: não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="Com {n_sobe} contra {n_cai}, {frase_tamanho_16x16}.",
    ressalva="Não quer dizer que físico faz subir, nem que se contrata pelo físico: elenco valioso tende a ter isso, e o estudo não separa as duas coisas; e o desconto do rodízio pode levar junto uma parte real da diferença. Não contradiz a FIS-09: lá é quem sobe contra o meio, onde a lista fica no nível da sorte. A FIS-10, a M5 e a M8 são medidas contadas uma a uma; aqui é o conjunto das {n_medidas}.",
    tecnico="tamanho detectável {d_min}",
    universo=UNIVERSOS["fisico"],
    lac={
        "n_bruto": D("inteiro", "fisico_col_elenco.passam5_SC + fisico_col_setor.passam5_SC", ["etapa_3.por_familia.fisico_col_elenco.passam5_SC", "etapa_3.por_familia.fisico_col_setor.passam5_SC"]),
        "n_medidas": D("inteiro", "fisico_col_elenco.testes + fisico_col_setor.testes", ["etapa_3.por_familia.fisico_col_elenco.testes", "etapa_3.por_familia.fisico_col_setor.testes"]),
        "esperado": D("inteiro", "soma de excesso.SC.bruto.nulo_mediana das duas famílias físicas", ["etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.nulo_mediana", "etapa_3.por_familia.fisico_col_elenco.excesso.SC.bruto.nulo_mediana"]),
        "n_rod": D("inteiro", "fisico_col_elenco.passam5_rod_SC + fisico_col_setor.passam5_rod_SC", ["etapa_3.por_familia.fisico_col_elenco.passam5_rod_SC", "etapa_3.por_familia.fisico_col_setor.passam5_rod_SC"]),
        "d_min": G("dec2", "etapa_0.poder.d_minimo_16x16"),
    },
    val={"n_bruto": "41", "n_medidas": "160", "esperado": "7", "n_rod": "34"},
    crit=[
        CONST("1. famílias físicas e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim"),
        KM("4. lista acima da sorte no número cru, quem sobe contra quem cai, em alguma das duas listas físicas (p do excesso < 0,05)", "etapa_3.por_familia", papel="lista", op="<", lim=0.05, ag="algum",
           filtro={"tipo": "dicionario", "nome": "familia", "valores": ["fisico_col_setor", "fisico_col_elenco"]}, sub="excesso.SC.bruto.p_excesso"),
        KM("5. a mesma lista descontado só o rodízio, em alguma das duas (p do excesso < 0,05)", "etapa_3.por_familia", papel="rod", op="<", lim=0.05, ag="algum",
           filtro={"tipo": "dicionario", "nome": "familia", "valores": ["fisico_col_setor", "fisico_col_elenco"]}, sub="excesso.SC.rod.p_excesso"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
    ],
    regra_propria=[("moderado", {0: True, 1: True, 2: True, 3: False}), ("fraco", {1: True, 2: False}), ("sem_sinal", {1: False})],
    regra={"regua": "régua final de 15/09, regra própria da lista inteira: a conclusão é sobre a lista, não sobre uma linha",
           "moderado_se": "lista declarada com p_excesso SC bruto < 0,05 em alguma família física E a mesma lista com p_excesso SC rod < 0,05 E nenhuma conferência testável",
           "fraco_se": "excesso no bruto E sem excesso descontado só o rodízio", "sem_sinal_se": "sem excesso nem no bruto",
           "obrigatorio": "dizer que o desconto do rodízio pode apagar sinal real; ressalva sem desconto e sem receita (elenco valioso tende a ter isso; o estudo não separa as duas coisas)",
           "proibido": ["'menos do que o acaso daria'", "abrir o título pela conta já descontada", "'entre elencos de valor parecido' (o desconto do valor saiu em 15/09)"]},
    p=P("etapa_3.por_familia.fisico_col_setor.excesso.SC.bruto.p_excesso", 0.0104), ceticos=True,
    rev="reconferência 14/09: caminho do esperado passa a ser excesso.SC.bruto.nulo_mediana (um nome só); ressalva também explica a FIS-10, que virou moderada",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só porque o desconto do valor levava quase tudo (sobravam 4, e 2 com valor e rodízio). Descontado só o rodízio sobram 34 das 41, e a lista por setor segue com mais achados que a sorte (27 contra 6, p 0,0108). Sem conferência testável: moderado. A ressalva do elenco valioso entra sem desconto e sem receita (resposta b do dono); a medida por coluna (`etapa_2.andam_com_o_valor`) ainda não está gravada",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 (`prototipo_novo.json`, dado ainda não gravado no projeto): quem sobe contra quem cai, contagem bruta das duas listas físicas 14 (elenco, p do excesso 0,0099) e 27 (setor, 0,0104), sorteio típico 1 e 6; descontado só o posto de atletas rastreados (`fis_atletas` no elenco, `fis_<setor>_atletas` no setor) 7 (elenco, 0,077) e 27 (setor, 0,0108) · na conta de 14/09, com o desconto do valor, sobravam 4 e, com valor e rodízio, 2 (`r4_saida.json`): quem derrubava o físico era o dinheiro, não o rodízio (`m1_rodizio_catalogo.py`, parte 1) · quem sobe contra o meio: 9 contra 6 (setor, p 0,33) e 0 contra 1 (elenco, p 1,0), FIS-09 · onde ver na aba: etapa 3",
))
