C.append(conc(
    id="FIS-01", tema="fisico", etapa="etapa_2", selo="fraco", declarada=False,
    titulo="Quem cai tende a ser dos menos intensos do ano, mas não se viu isso continuar entre times que rodaram o elenco parecido",
    frase="Quem cai fica tipicamente em {pos_cai}º de {n_por_ano} em sprint, corrida forte e arrancada; os times do meio, em {pos_meio}º, de {ano_ini} a {ano_fim}. Dos {n_cai} que caíram, só {cai_top5} esteve entre os {k5} mais intensos do ano ({excecao_top5}) e {cai_bottom5} estavam entre os {k5} menos intensos. Quem sobe não se mostrou mais intenso que o meio da tabela.",
    numero="Sem desconto, o acaso produziria essa diferença em {p_bruto_chance}; entre times que rodaram o elenco parecido, em {p_rod_chance}. É um sinal {selo}: o índice e a comparação com o meio foram montados depois de olhar os dados, não há lista de onde saiam para comparar com a sorte, e a diferença não continua descontado o rodízio.",
    ressalva="Não quer dizer que faltou físico e por isso caiu, nem que contratar intensidade evita cair. A contagem dos mais e menos intensos é a mesma medida vista de outro jeito, não uma prova a mais.",
    universo=UNIVERSOS["fisico"],
    lac={
        "pos_cai": N("inteiro", "etapa_2.indice_intensidade.mediana_posicao", "cai"),
        "pos_meio": N("inteiro", "etapa_2.indice_intensidade.mediana_posicao", "meio"),
        "n_por_ano": G("inteiro", "etapa_1.curva_top_k.clubes_por_ano[0]"),
        "k5": N("inteiro", "etapa_2.indice_intensidade.k_extremos"),
        "cai_top5": N("inteiro", "etapa_2.indice_intensidade.cai_top_k"),
        "excecao_top5": N("texto", "etapa_2.indice_intensidade.excecoes_top_k", "'o CLUBE ANO, Nº', vírgulas e 'e'"),
        "cai_bottom5": N("inteiro", "etapa_2.indice_intensidade.cai_bottom_k"),
        "p_bruto_chance": N("chance_em_100", "etapa_2.indice_intensidade.p_bruto_CM"),
        "p_rod_chance": N("chance_em_100", "etapa_2.indice_intensidade.p_rod_CM"),
    },
    val={"pos_cai": "15", "pos_meio": "9", "k5": "5", "cai_top5": "1", "excecao_top5": "o Londrina 2023, 2º", "cai_bottom5": "8", "p_bruto_chance": "menos de 1 de cada 100 tentativas",
         "p_rod_chance": "8 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação e índice declarados antes", False, papel="declarada", txt="não: índice e 'quem cai contra o meio' montados depois de olhar"),
        KM("p bruto < 0,05 (quem cai contra o meio)", "etapa_2.indice_intensidade.p_bruto_CM", papel="p", op="<", lim=0.05, v=0.0095),
        KM("5. descontado só o rodízio (atletas rastreados), p < 0,05", "etapa_2.indice_intensidade.p_rod_CM", papel="rod", op="<", lim=0.05, v=0.077,
           txt="0,077 no rascunho da parte 1, não definitivo (o índice refeito lá dá bruto 0,013, contra 0,0095 do gravado)"),
        CONST("4. lista de onde a comparação saia, com mais achados que a sorte", False, papel="lista", txt="não há lista: índice único"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → fraco; no físico, p_rod >= 0,05 → fraco",
           "fraco_se": "p_bruto_CM < 0,05 E (p_rod_CM >= 0,05 OU comparação montada depois de olhar sem lista)", "moderado_se": "impossível: índice e comparação montados depois de olhar, sem lista declarada",
           "regra_de_teste": "só p bilateral para o leitor", "proibido": ["'é o rodízio' como explicação", "'nunca tem físico bom'", "'entre elencos de valor parecido' (o desconto do valor saiu em 15/09)"]},
    p=P("etapa_2.indice_intensidade.p_bruto_CM", 0.0095), ceticos=True,
    rev="reconferência 14/09: posições 15º e 9º conferidas (`r13_varios.py`: mediana da posição no ano 15, 9 e 7 para cai, meio e sobe); regra do dono reaplicada: sem lista e some no dinheiro, fica fraco",
    rev15="rodada sem dinheiro (15/09): sai o desconto do valor do elenco; fica só o do rodízio (0,077 no rascunho da parte 1, não definitivo até o gerador gravar `etapa_2.indice_intensidade.p_rod_CM`). Título troca 'valor e rodízio' por 'rodízio'. Selo segue FRACO (sem lista e não continua no rodízio)",
    faixa_keep=True,
    rodape_ops=[("replace", "índice = média do posto no ano em 10 colunas", "posição no ano pelo índice (1 = mais intenso): mediana 7 em quem sobe, 9 no meio, 15 em quem cai; Londrina 2023 2º; 8 rebaixados entre os 5 últimos (`r13_varios.py`) · índice = média do posto no ano em 10 colunas")],
))
