C.append(conc(
    id="J1", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe finaliza de mais perto do gol",
    frase="{m_sobe} metros em média, contra {m_meio} no meio da tabela e {m_cai} em quem cai, de {ano_ini} a {ano_fim}; {sobe_perto} dos {n_prom} que subiram chutaram de mais perto que a metade da liga no seu ano. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo testados, e o número do primeiro turno acompanha os pontos do segundo mesmo entre times com pontos parecidos (contando os {n_testados_e7} números do primeiro turno, isso pode ser sorte).",
    numero="Pegando um time que subiu e um do meio, o que subiu chuta de mais perto em {auc_100}. Em {periodo_antigo} foi para o mesmo lado, mas no limite: o acaso produziria aquilo em {p_antigo_chance}; é essa conferência que falta para o selo forte.",
    ressalva="Não quer dizer 'mande chutar de perto', nem 'trabalhe a chegada à área e o time sobe'. Quem toca mais na área chuta de mais perto, mas, comparando times com as mesmas entradas e toques na área, quem sobe continua chutando de mais perto; o estudo não mediu de onde vem a diferença.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_meio"),
        "m_cai": G("dec1", "etapa_2.linhas[indicador=dist_remate].m_cai"),
        "sobe_perto": N("inteiro", "etapa_2.por_clube", "promovidos com dist_remate abaixo da mediana do próprio ano"),
        "auc_100": D("pares_em_100", "1 - etapa_2.linhas[indicador=dist_remate].auc_SM (sinal -1)", ["etapa_2.linhas[indicador=dist_remate].auc_SM"]),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].p_SM"),
    },
    val={"sobe_perto": "14", "auc_100": "81 de cada 100 pares"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=dist_remate].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=dist_remate].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=dist_remate].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=dist_remate].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=dist_remate].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: chuta de mais perto)", "teste_cego_2018_2021.json porta.velho[ind=dist_remate].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "forte_se": "q_SM < 0,05 E as duas conferências testáveis passam (1º turno com p parcial < 0,05 no lado declarado; 2018-2021 com p < 0,05 no mesmo lado)",
           "moderado_se": "q_SM < 0,05 E alguma conferência falha (as conferências discordam → o mais fraco)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno passa a valer pelo p parcial (não pelo q dos 28)",
           "proibido": ["'o único sinal de jogo que passa em tudo'", "'o mais firme'", "'é consequência de chegar bem à área'", "'o sinal mais sólido'", "'continua entre elencos de valor parecido'", "'o mesmo clube tende a repetir'"]},
    p=P("etapa_2.linhas[indicador=dist_remate].p_bruto_SM", 3e-05), ceticos=True, rev="reconferência 14/09: universo e critérios; a falha de 2018-2021 está gravada no teste cego",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'o mesmo clube tende a repetir'; firme (q 0,0008); conferências: 1º turno passa pelo p (0,0022, lado declarado) e 2018-2021 falha (0,079): discordam, vale a mais fraca",
    faixa_keep=True, rodape_ops=[],
))
