C.append(conc(
    id="J13", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe cede chutes com menos chance de gol",
    frase="{xgr_sobe} de gol esperado por chute cedido, contra {xgr_meio} no meio da tabela e {xgr_cai} em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: contando os {n_familia_tecnico_col} números de jogo testados já não dá para descartar a sorte, mas a lista inteira tem mais achados do que a sorte produz; em {periodo_antigo} foi para o mesmo lado sem força para confirmar.",
    numero="Olhando só o gol esperado por chute, o acaso produziria a diferença em {p_chance}; em {periodo_antigo}, em {p_antigo_chance}. No total de chances cedidas, quem sobe cede bem menos que quem cai ({xg_sobe} contra {xg_cai} gol esperado por jogo), e isso é firme contando os {n_familia_tecnico_col} números; contra o meio, o total cedido pode ser sorte olhando os {n_familia_tecnico_col}, mas a mesma lista tem mais achados do que a sorte.",
    ressalva="Não quer dizer 'defenda longe da área e você sobe': gol esperado por chute mede a qualidade da chance (de onde, de cabeça, sob pressão), e ceder pouco pode vir de ter mais a bola ou de estar ganhando. Em {periodo_antigo} não se viu diferença entre quem caiu e o resto da liga no gol esperado cedido.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "xgr_sobe": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_sobe"),
        "xgr_meio": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_meio"),
        "xgr_cai": G("dec3", "etapa_2.linhas[indicador=xg_por_remate_contra].m_cai"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM"),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].p_SM"),
        "xg_sobe": G("dec2", "etapa_2.linhas[indicador=xg_contra].m_sobe"),
        "xg_cai": G("dec2", "etapa_2.linhas[indicador=xg_contra].m_cai"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=xg_por_remate_contra].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=xg_por_remate_contra].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: cede menos)", "teste_cego_2018_2021.json porta.velho[ind=xg_por_remate_contra].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: 2018-2021 (sem versão por jogo, o 1º turno não é testável)"),
        CONST("há uma conferência testável só", True, papel="uma_conf", txt="sim: só 2018-2021"),
        KM("4. lista inteira do técnico do time acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso < 0,05",
           "total_cedido": "xg_contra, só descrição: quem sobe contra quem cai q_SC 0,0017 (firme); quem sobe contra o meio p 0,049, q 0,21 (pode ser sorte), com a lista do técnico do time acima da sorte",
           "saiu_em_15_09": "o desconto do dinheiro, o mesmo clube no ano seguinte e os selos do total cedido montados com o desconto",
           "proibido": ["'deixa o adversário chutar de onde é mais difícil'", "'em 2018-2021 quem caiu cedia o mesmo'", "'não é traço de clube' como fato", "'entre quem caiu e o meio' para o número de quem cai contra o resto", "'some quando se comparam elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=xg_por_remate_contra].p_bruto_SM", 0.01038), ceticos=True,
    rev="reconferência 14/09: o p de 2018-2021 já está gravado no teste cego (0,1134); 'entre quem caiu e o meio' virou 'o resto da liga' (p 0,68); frase do traço no molde da ELE-02",
    rev15="rodada sem dinheiro (15/09): segue MODERADO (q 0,080; lista do técnico do time 7 contra 1, p 0,037). Saem 'continua de pé entre times de elenco de valor parecido', 'não se viu o mesmo clube repetir' e os dois selos do total cedido que dependiam do desconto (o total contra o meio era fraco só pelo dinheiro); o total cedido fica descrito com o vocabulário da sorte",
    faixa_keep=True, rodape_ops=[],
))
