C.append(conc(
    id="J15", tema="jogo_e_padroes", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="A posse de quem sobe é maior, no limite do acaso",
    frase="{posse_sobe}% contra {posse_meio}% no meio da tabela, de {ano_ini} a {ano_fim}, no limite do acaso. É um sinal {selo}: contra o meio fica no limite, e contra quem cai a diferença aparece.",
    numero="Na Série B inteira, elenco mais valioso tem mais a bola e pressiona mais alto: as duas coisas andam com o valor do elenco.",
    ressalva="Não quer dizer que ter a bola faz subir: elenco valioso tende a ter mais a bola, e o estudo não separa as duas coisas.",
    universo=UNIVERSOS["clube_valor"],
    lac={
        "posse_sobe": G("pct_inteiro", "etapa_2.linhas[indicador=posse].m_sobe"),
        "posse_meio": G("pct_inteiro", "etapa_2.linhas[indicador=posse].m_meio"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05 (quem sobe contra o meio)", "etapa_2.linhas[indicador=posse].p_bruto_SM", papel="p", op="<", lim=0.05, txt="0,056 (zona cinzenta)"),
        KM("zona cinzenta: p < 0,10", "etapa_2.linhas[indicador=posse].p_bruto_SM", papel="zona", op="<", lim=0.10),
        KM("sinal bruto em outra comparação da mesma linha (quem sobe contra quem cai), p < 0,05", "etapa_2.linhas[indicador=posse].p_bruto_SC", papel="outra", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=posse].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=posse].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=posse].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=posse].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=posse].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=posse].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): zona cinzenta com p < 0,05 em outra comparação da mesma linha → fraco",
           "fraco_se": "0,05 <= p_bruto_SM < 0,10 E p_bruto_SC < 0,05",
           "ressalva": "sem desconto e sem receita: 'elenco valioso tende a ter mais a bola; o estudo não separa as duas coisas'",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC) como critério; do título, 'mas anda com o valor do elenco' como desconto",
           "proibido": ["'tenha a bola'", "ρ na frase de reunião"]},
    p=P("etapa_2.linhas[indicador=posse].p_bruto_SM", 0.05612), ceticos=True, rev="reconferência 14/09: correlações com o valor no rodapé, não na frase",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o critério do desconto do dinheiro; decide a zona cinzenta de quem sobe contra o meio (0,056) com p 0,008 em quem sobe contra quem cai. Título sem o desconto; a relação com o valor fica como ressalva sem desconto",
    faixa_keep=True, rodape_ops=[],
))
