C.append(conc(
    id="J16", tema="jogo_e_padroes", etapa="etapa_8", selo="fraco", declarada=False,
    titulo="Os {n_fora} que subiram com elenco fora do top {k8} ocuparam menos o campo adversário",
    frase="Os {n_fora} que subiram sem estar entre os {k8} elencos mais valiosos ({nomes_fora}) ocuparam menos o campo adversário que a metade dos {n_prom} que subiram: {estilos_fora}. É um sinal {selo}: são {n_fora} times, a linha foi escolhida depois de olhar, não há lista de onde ela saia para comparar com a sorte, e {colado_na_linha} ficou colado nela.",
    numero="{n_fora_abaixo} de {n_fora} abaixo da mediana: o acaso produziria isso em {p_hiper_chance}.",
    ressalva="Não quer dizer que time barato tem que jogar reativo para subir, nem que ocupar o campo adversário exige dinheiro: nos mesmos dois estilos, {n_caros_mesmos_estilos} dos que subiram tinham elenco entre os {k5} mais caros. O grupo dono do jogo está na J10.",
    universo=UNIVERSOS["tipologia"],
    lac={
        "n_fora": N("inteiro", "etapa_8.tipologia.fora_do_top_k.n_fora"),
        "k8": G("inteiro", "etapa_1.curva_top_k.palpite_do_dono.k"),
        "nomes_fora": N("texto", "etapa_8.tipologia.fora_do_top_k.nomes", "'Clube Ano', vírgulas e 'e'"),
        "estilos_fora": N("texto", "etapa_8.tipologia.fora_do_top_k.estilos", "contagem por grupo em palavras: 'dois foram controladores pacientes e dois reativos de bola direta'"),
        "colado_na_linha": N("texto", "etapa_8.tipologia.fora_do_top_k.colado_na_linha", "'o CLUBE ANO' com |território - corte| < 1"),
        "n_fora_abaixo": N("inteiro", "etapa_8.tipologia.fora_do_top_k.abaixo_da_mediana"),
        "p_hiper_chance": N("chance_em_100", "etapa_8.tipologia.fora_do_top_k.p_hipergeometrico"),
        "n_caros_mesmos_estilos": N("inteiro", "etapa_8.tipologia.fora_do_top_k.caros_nos_mesmos_estilos"),
        "k5": D("inteiro", "tamanho do quartil de cima por ano (etapa_1.quartis[quartil=4].n / n_anos)", ["etapa_1.quartis"]),
    },
    val={"n_fora": "4", "nomes_fora": "Vitória 2023, Mirassol 2024, Criciúma 2023 e Chapecoense 2025", "estilos_fora": "dois foram controladores pacientes e dois reativos de bola direta",
         "colado_na_linha": "o Vitória 2023", "n_fora_abaixo": "4", "p_hiper_chance": "4 de cada 100 tentativas", "n_caros_mesmos_estilos": "4", "k5": "5"},
    crit=[
        CONST("1. linha declarada antes", False, papel="declarada", txt="não: a linha (fora do top 8) foi escolhida depois de olhar"),
        KM("4 de 4 abaixo da mediana, hipergeométrica, p < 0,05", "etapa_8.tipologia.fora_do_top_k.p_hipergeometrico", papel="p", op="<", lim=0.05, v=0.038),
        CONST("4. lista acima da sorte (regra do dono)", False, papel="lista", txt="não há lista"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): linha escolhida depois de olhar, sem lista → teto fraco",
           "fraco_se": "p hipergeométrico < 0,05 E linha escolhida depois de olhar sem lista", "moderado_se": "impossível: linha escolhida depois, sem lista",
           "saiu_em_15_09": "'comparando elencos de valor parecido, 3 dos 4 mudam de lado' (trocam_no_dinheiro)",
           "proibido": ["repetir a exceção do G1 (J10)", "'estilo de quem não tem dinheiro'"]},
    p=P("etapa_8.tipologia.fora_do_top_k.p_hipergeometrico", 0.038), ceticos=True, rev="reconferência 14/09: regra do dono reaplicada (sem lista, some no dinheiro): segue fraco",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Sai o critério 'trocam de lado descontado o dinheiro' e a frase correspondente; decide a regra da linha escolhida depois, sem lista",
    faixa_keep=True, rodape_ops=[],
))
