C.append(conc(
    id="J17", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem cai usou mais formações diferentes que quem sobe de {ano_ini} a {ano_fim}",
    frase="De {ano_ini} a {ano_fim}, quem caiu usou {form_cai} formações diferentes na temporada (mediana), contra {form_sobe} em quem subiu e {form_meio} no meio da tabela. É um sinal {selo}: na comparação declarada antes, quem sobe contra quem cai, o acaso produziria a diferença em {p_sc_chance}; contando os {n_familia_elenco} números do elenco, {frase_q}; e em {periodo_antigo} quem caiu também usou mais formações que quem subiu ({p_sc_antigo_chance}). Firme por pouco e conferida por um caminho só, fica moderado.",
    numero="Contra o meio da tabela a diferença também aparece ({p_cm_chance}; em {periodo_antigo}, {p_cm_antigo_chance}), mas essa comparação foi escolhida depois de olhar e fica só descrita: o título continua sendo o da comparação declarada.",
    ressalva="Não quer dizer que mudar pouco o desenho evita cair. Trocar de técnico ou de time no meio do ano pode mudar a formação; o estudo não tem o técnico nem a data da troca (J12). O número de formações anda com o número de jogadores usados (ELE-01). Elenco valioso tende a ter isso; o estudo não separa as duas coisas. A fidelidade à formação principal tem duas contas: pela declarada não se viu diferença; pela do gerador, quem cai é menos fiel que quem sobe, mas o selo segue a declarada.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "form_cai": N("dec1", "etapa_2.linhas[].mediana_cai", "formacoes"),
        "form_meio": N("dec1", "etapa_2.linhas[].mediana_meio", "formacoes"),
        "form_sobe": N("dec1", "etapa_2.linhas[].mediana_sobe", "formacoes"),
        "p_sc_chance": G("chance_em_100", "etapa_2.linhas[indicador=formacoes].p_bruto_SC"),
        "frase_q": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=formacoes].q_SC"]),
        "p_sc_antigo_chance": N("chance_em_100", "etapa_2.linhas[].antigo_SC", "formacoes: p"),
        "p_cm_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CM", "formacoes"),
        "p_cm_antigo_chance": N("chance_em_100", "etapa_2.linhas[].antigo_CM", "formacoes: p"),
    },
    val={"form_cai": "8,5", "form_meio": "6,5", "form_sobe": "6,5", "frase_q": "é firme por pouco", "p_sc_antigo_chance": "3 de cada 100 tentativas", "p_cm_chance": "3 de cada 1.000 tentativas",
         "p_cm_antigo_chance": "14 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação do título declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05 (quem sobe contra quem cai)", "etapa_2.linhas[indicador=formacoes].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 10 números do elenco (q < 0,05)", "etapa_2.linhas[indicador=formacoes].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025); entre 0,025 e 0,05 é firme por pouco", "etapa_2.linhas[indicador=formacoes].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: 2018-2021, quem sobe contra quem cai, p < 0,05 no mesmo lado (medianas 5,0 / 5,5 / 6,0)", "etapa_2.linhas[indicador=formacoes].antigo_SC", papel="conf", op="<", lim=0.05, sub="p", v=0.025),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: 2018-2021 (formação sem versão por jogo na etapa 7)"),
        CONST("há uma conferência testável só", True, papel="uma_conf", txt="sim: só 2018-2021"),
        KM("4. lista do elenco, quem sobe contra quem cai, acima da sorte", "etapa_3.por_familia.elenco.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem cai contra o meio (escolhida depois de olhar; só descrição, não vai para o título): lista do elenco acima da sorte", "etapa_3.por_familia.elenco.excesso.CM.bruto.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum), com a regra geral da resposta a do dono: firme por pouco (0,025 <= q < 0,05) com uma conferência só = moderado",
           "comparacao_da_frase": "SC declarada (linha do catálogo, família elenco)",
           "moderado_se": "q_SC < 0,05 E (alguma conferência falha OU firme por pouco com uma conferência só OU nenhuma conferência testável)",
           "forte_se": "q_SC < 0,05 E pelo menos uma conferência testável, todas passando, E não firme por pouco com uma conferência só",
           "parte_CM": "escolhida depois de olhar; descrita ao lado com o próprio resultado (lista do elenco 5 contra 0, p 0,0067); não vai para o título",
           "fonte": "coluna formacoes do painel = proxy sistemas_distintos do gerador nas 80 temporadas (conferido pelo cético); a linha JÁ existe no catálogo (família elenco)",
           "ressalva": "sem desconto e sem receita (resposta b do dono); a medida por coluna vai para etapa_2.andam_com_o_valor",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC 0,125, era o único motivo do fraco) e o mesmo clube no ano seguinte",
           "proibido": ["'mude pouco a formação'", "'trocar de técnico muda o desenho' como fato", "'menos fiel' sem as duas contas", "'as medidas de formação não têm a conta dos muitos testes' (estão na família do elenco)", "título pela comparação quem cai contra o meio (escolhida depois)", "'some entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=formacoes].p_bruto_SC", 0.02428), ceticos=True, nova_em="2026-09-14 (conserto)",
    rev="conserto final 14/09: moderado → fraco. Na reconferência o título tinha sido trocado da comparação declarada (quem sobe contra quem cai) para quem cai contra o meio, a única das duas que passa no dinheiro (0,009 contra 0,125), e o selo subia pela troca. A decisão 1 do dono vale para a comparação que a conclusão já tinha no título; o título volta à declarada e quem cai contra o meio fica descrita ao lado",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. O desconto do valor (p 0,125) era o único motivo do fraco. Pela régua final seria forte (firme, q 0,0447, e 2018-2021 passa, p 0,025), mas é firme por pouco e com uma conferência só: MODERADO pela regra geral da resposta a do dono. Título sem '— mas isso some entre elencos de valor parecido'; entra a ressalva sem desconto",
    faixa_keep=True,
    rodape_texto="nova na rodada de conserto de 14/09 (era sinal sem selo dentro da J11); reconferida pelo cético de números em 14/09 · `formacoes` do painel (`dados/serieb_clube_temporada.csv` e `_2018_2021.csv`), idêntica ao proxy `sistemas_distintos` do gerador nas 80 temporadas (6,88 / 6,69 / 8,06) · a coluna está na família declarada do elenco (10), linha gravada em `etapa_2.linhas[formacoes]` · **selo: MODERADO na rodada sem dinheiro de 15/09** (antes FRACO, só pelo desconto do valor, p 0,125): firme por pouco (q 0,0447) e com uma conferência só (2018-2021) · 2022-2025, medianas sobe / meio / cai 6,5 / 6,5 / 8,5 · **sobe x cai (declarada, a do título):** Mann-Whitney 0,033, Welch no posto 0,024, q 0,045 (10) · **cai x meio (escolhida depois, só descrição):** Welch no posto p 0,0025; lista do elenco cai x meio 5 contra 0 (atletas usados, XI mais usado, concentração de minutos, núcleo de 300+ minutos e formações), p do excesso 0,006 (`r4_saida.json`; 0,0067 no dado novo) · sobe x meio 0,61 · 2018-2021, medianas 5,0 / 5,5 / 6,0: sobe x cai 0,025 (Mann-Whitney 0,020), refeito no CSV, ainda não gravado (`etapa_2.linhas[formacoes].antigo_SC`); cai x meio no posto 0,14 (Mann-Whitney 0,11) · fidelidade: `fidelidade_media` do gerador 87,0 / 85,4 / 83,6, sobe x cai p 0,016; `formPrincipalPct` do painel (a declarada) sobe x cai 0,29 (2022-25) e 0,12 (2018-21) → segue a declarada (`cf_num/v_j17.py`) · onde ver na aba: etapa 2 e etapa 15",
))
