C.append(conc(
    id="J19", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe pressiona mais alto que quem cai",
    frase="De {ano_ini} a {ano_fim}, quem sobe deixou o adversário trocar {ppda_sobe} passes por ação defensiva, contra {ppda_cai} em quem cai (menos passes é pressão mais alta). É um sinal {selo}: na comparação declarada antes, quem sobe contra quem cai, contando os {n_familia_tecnico_col} números de jogo, {frase_q}; mas não se viu o primeiro turno prever o segundo, e em {periodo_antigo} não se viu diferença entre quem subiu e quem caiu (o acaso produziria aquilo em {p_antigo_sc_chance}).",
    numero="Olhando só este número, o acaso produziria a diferença em {p_sc_chance}. Contra o meio da tabela não se viu diferença (J14).",
    ressalva="Não quer dizer que pressionar alto faz subir, nem que evita cair. Elenco valioso tende a pressionar mais alto (J15); o estudo não separa as duas coisas.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "ppda_sobe": G("dec1", "etapa_2.linhas[indicador=ppda].m_sobe"),
        "ppda_cai": G("dec1", "etapa_2.linhas[indicador=ppda].m_cai"),
        "frase_q": D("texto", "q_SC < 0,025: 'é firme'; 0,025 <= q_SC < 0,05: 'é firme por pouco'; senão 'já não dá para descartar a sorte'", ["etapa_2.linhas[indicador=ppda].q_SC"]),
        "p_sc_chance": G("chance_em_1000", "etapa_2.linhas[indicador=ppda].p_bruto_SC"),
        "p_antigo_sc_chance": N("chance_em_100", "etapa_2.linhas[].antigo_SC", "ppda: p"),
    },
    val={"frase_q": "é firme", "p_antigo_sc_chance": "87 de cada 100 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra quem cai", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ppda].p_bruto_SC", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=ppda].q_SC", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ppda].q_SC", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=ppda].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=ppda].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra quem cai, p < 0,05 no mesmo lado", "etapa_2.linhas[indicador=ppda].antigo_SC", papel="conf", op="<", lim=0.05, sub="p", v=0.87),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra quem cai, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SC < 0,05 E as conferências testáveis falham (1º turno p 0,31; 2018-2021 p 0,87)",
           "ressalva": "sem desconto e sem receita (resposta b do dono): 'elenco valioso tende a pressionar mais alto; o estudo não separa as duas coisas' — medido: ppda anda com o valor do elenco (ρ −0,55, `etapa_2.estilo_x_valor`)",
           "saiu_em_15_09": "o desconto do dinheiro (p_liq_SC 0,83) e o mesmo clube no ano seguinte; do título, '— mas isso some entre elencos de valor parecido'",
           "proibido": ["'pressione alto'", "'PPDA' sem traduzir na frase", "'some entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=ppda].p_bruto_SC", 0.00194), ceticos=False, nova_em="2026-09-14 (reconferência)",
    rev="nova na reconferência de 14/09: era um número sem selo no rodapé da J14 (PPDA sobe x cai p 0,0019, q 0,009, descontado 0,83)",
    rev15="rodada sem dinheiro (15/09): FRACO → MODERADO. Era fraco só pelo desconto do valor (0,83). Pela régua final: firme em quem sobe contra quem cai (q 0,0086); o 1º turno (0,31) e 2018-2021 (0,87) falham. Ressalva obrigatória sem desconto: elenco valioso tende a pressionar mais alto; o estudo não separa as duas coisas",
    faixa_texto="**Vale também pela faixa de pontos?** (provisório): na faixa baixa x média, PPDA p 0,029 (2022-25) e 0,88 em 2018-21 (lido da J14).",
    rodape_texto="nova na reconferência de 14/09 (era número sem selo no rodapé da J14), sem cético próprio · `ppda` média 9,83 / 10,15 / 11,11 passes do adversário por ação defensiva (menor = pressão mais alta) · sobe x cai d no posto, p 0,0019, q 0,0086 (31) (`etapa_2.linhas[ppda].{p_bruto_SC, q_SC}`, gravados) · sobe x meio p 0,60 (J14) · 1º → 2º turno parcial −0,12 (p 0,31) · 2018-2021 sobe x cai p 0,87, médias 9,4 / 9,6 / 9,4 (`r13_varios.py`) · valor do elenco x pressão, 80 temporadas: ρ 0,55 (J15), é o que a ressalva descreve, sem descontar · na conta de 14/09 o selo fraco vinha do desconto do valor (p 0,83), que saiu da régua em 15/09 · onde ver na aba: etapa 2",
))
