C.append(conc(
    id="J2", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe acerta mais chutes no gol",
    frase="{m_sobe}% dos chutes no alvo, contra {m_meio}% no meio da tabela e {m_cai}% em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo, e o número do primeiro turno acompanha os pontos do segundo (contando os {n_testados_e7} números do primeiro turno, isso pode ser sorte).",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}. Em {periodo_antigo} não se viu diferença contra o meio (o acaso produziria aquilo em {p_antigo_chance}); quem subiu ainda ficou acima de quem caiu (em {p_antigo_sc_chance}).",
    ressalva="Não quer dizer que pontaria é traço do elenco que se contrata: pode ser forma da temporada, e a conferência em {periodo_antigo} contra o meio falhou.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_meio"),
        "m_cai": G("dec1", "etapa_2.linhas[indicador=remates_baliza_pct].m_cai"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM"),
        "p_antigo_chance": G("chance_em_100", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SM"),
        "p_antigo_sc_chance": G("chance_em_1000", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SC"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=remates_baliza_pct].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=remates_baliza_pct].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=remates_baliza_pct].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=remates_baliza_pct].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=remates_baliza_pct].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 E alguma conferência testável falha (aqui 2018-2021 contra o meio)",
           "regra_de_desempate": "conferências que discordam: o selo mais fraco",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno e 2018-2021 passam a decidir",
           "proibido": ["'o 1º turno ajuda a prever o 2º' sem a ressalva dos 28", "'em 2018-2021 o sinal apareceu fraco demais' (p 0,25: 'não se viu')", "'não se viu o mesmo clube repetir a pontaria'"]},
    p=P("etapa_2.linhas[indicador=remates_baliza_pct].p_bruto_SM", 0.00013), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números (tudo reproduziu); '2018-2021 apareceu fraco demais' virou 'não se viu diferença contra o meio', com quem sobe acima de quem cai",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre elencos de valor parecido' e 'não se viu o mesmo clube repetir a pontaria'; firme (q 0,002); 1º turno passa (p 0,030) e 2018-2021 falha (0,25): o 1º turno e 2018-2021 passam a decidir. A ressalva não cita mais a etapa 10: `remates_baliza_pct` saiu da lista de lá (é porta A no catálogo novo)",
    faixa_keep=True,
    rodape_ops=[("replace", "2018-2021 d 0,35, p 0,25", "2018-2021 sobe x meio d 0,35, p 0,25, q 0,33 nos 31; sobe x cai p 0,0009 · reconferido pelo cético de 14/09")],
))
