C.append(conc(
    id="J3", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe faz menos faltas",
    frase="{m_sobe} faltas por jogo, contra {m_meio} no meio da tabela, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_col} números de jogo, mas não se viu o primeiro turno prever o segundo, e em {periodo_antigo} foi para o mesmo lado sem força para confirmar.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}. Não se viu que seja por ter mais a bola: posse e faltas quase não andam juntas, e comparando times com a mesma posse o acaso produziria a diferença em {p_desc_posse_chance}.",
    ressalva="Não quer dizer 'faça menos falta para subir', nem 'tenha a bola para fazer menos falta'. O estudo não sabe por que quem sobe faz menos falta.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=faltas].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=faltas].m_meio"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=faltas].p_bruto_SM"),
        "p_desc_posse_chance": N("chance_em_1000", "etapa_2.linhas[].p_SM_descontada_posse", "faltas"),
    },
    val={"p_desc_posse_chance": "3 de cada 1.000 tentativas"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=faltas].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=faltas].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=faltas].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=faltas].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=faltas].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=faltas].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d negativo: menos faltas)", "teste_cego_2018_2021.json porta.velho[ind=faltas].d_SM", papel="conf", op="<", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista do técnico do time, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 E as conferências testáveis falham (1º turno p 0,90; 2018-2021 p 0,12)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; o 1º turno e 2018-2021 passam a decidir",
           "proibido": ["'time que tem a bola faz menos falta'", "correlação na frase de reunião", "'resiste ao dinheiro'"]},
    p=P("etapa_2.linhas[indicador=faltas].p_bruto_SM", 0.00169), ceticos=True, rev="reconferência 14/09: correlação posse × faltas saiu da frase (fica no rodapé)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'resiste ao dinheiro' e 'não se viu o mesmo clube repetir'; firme (q 0,017); o 1º turno (0,90) e 2018-2021 (0,12) falham e passam a decidir",
    faixa_keep=True, rodape_ops=[],
))
