C.append(conc(
    id="J4", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Quem sobe ganha mais duelos — e isso também apareceu em {periodo_antigo}",
    frase="Na posição no ranking de duelos ganhos do ano, de {ano_ini} a {ano_fim}, quem sobe fica bem acima do meio (em porcentagem a diferença é pequena: {m_sobe} contra {m_meio}), e em {periodo_antigo} apareceu com força. É um sinal {selo}: não resiste à conta dos {n_familia_tecnico_col} números de jogo, mas a lista inteira do técnico do time tem mais achados do que a sorte produz.",
    numero="Em {periodo_antigo}, o acaso produziria a diferença em {p_antigo_chance}. Não se viu o número do primeiro turno acompanhar os pontos do segundo (o acaso daria aquilo em {p_turno_chance}).",
    ressalva="Não quer dizer que duelo ganho faz subir. Em {periodo_antigo} não há valor de mercado: lá o resultado é cru. Quem cai não se distinguiu dos outros em duelo em nenhum dos dois períodos.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "m_sobe": G("dec1", "etapa_2.linhas[indicador=duelos_pct].m_sobe"),
        "m_meio": G("dec1", "etapa_2.linhas[indicador=duelos_pct].m_meio"),
        "p_antigo_chance": G("chance_em_1000", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].p_SM"),
        "p_turno_chance": G("chance_em_100", "etapa_2.linhas[indicador=duelos_pct].p_1T_2T"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=duelos_pct].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 31 números de jogo (q < 0,05)", "etapa_2.linhas[indicador=duelos_pct].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=duelos_pct].q_SM", papel="q_folga", op="<", lim=0.025),
        KM("3. conferência: o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=duelos_pct].p_parcial", papel="conf", op="<", lim=0.05),
        KM("3. conferência: o 1º turno prevê o 2º no lado declarado", "etapa_7.linhas[indicador=duelos_pct].sinal_certo", papel="conf", op="==", lim=True),
        KM("3. conferência: 2018-2021, quem sobe contra o meio, p < 0,05", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].p_SM", papel="conf", op="<", lim=0.05),
        KM("3. conferência: 2018-2021 no mesmo lado (d positivo)", "teste_cego_2018_2021.json porta.velho[ind=duelos_pct].d_SM", papel="conf", op=">", lim=0),
        CONST("há conferência testável", True, papel="ha_conf", txt="sim: o 1º turno e 2018-2021"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: são duas"),
        KM("4. lista inteira do técnico do time acima da sorte (p do excesso < 0,05)", "etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E etapa_3.por_familia.tecnico_col.excesso.SM.bruto.p_excesso < 0,05",
           "fraco_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E lista no nível da sorte",
           "nota": "a conferência de 2018-2021 que passa não substitui a falha na conta dos testes (as conferências só decidem entre forte e moderado)",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte"},
    p=P("etapa_2.linhas[indicador=duelos_pct].p_bruto_SM", 0.0208), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números; acrescentado que o primeiro turno não acompanha o segundo (p 0,90, gravado)",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'continua entre times de valor de elenco parecido' e 'não se viu o mesmo clube repetir'; q 0,13 e a lista do técnico do time tem mais achados que a sorte (7 contra 1, p 0,037)",
    faixa_keep=True,
    rodape_ops=[("replace", "ρ de repetição 0,05", "1º → 2º turno parcial 0,015 (p 0,90, `etapa_2.linhas[duelos_pct].p_1T_2T`) · reconferido pelo cético de 14/09 (lista 7 contra 1, p 0,037 noutra semente)")],
))
