C.append(conc(
    id="J5", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=False,
    titulo="Quem cai ganhou uma parte menor dos duelos aéreos de {ano_ini} a {ano_fim}; em {periodo_antigo} não se repetiu",
    frase="De {ano_ini} a {ano_fim}, {cai_metade_baixo} dos {n_cai} que caíram ficaram na metade de baixo do ano em duelo aéreo ganho, e {cai_5_piores} entre os {k_extremos} piores. Contra todos os outros times, o acaso produziria a diferença em {p_cr_chance}. É um sinal {selo} de {ano_ini} a {ano_fim}: a comparação quem cai contra o resto foi escolhida depois da pergunta do dono, mas a lista dos {n_familia_tecnico_col} números de jogo nessa comparação tem mais achados do que a sorte, que é o que a regra do dono pede para uma comparação escolhida depois.",
    numero="Em {periodo_antigo} não se repetiu: só {cai_metade_baixo_antigo} dos {n_cai_antigo} que caíram estavam na metade de baixo, e {n_cai_melhores_antigo} deles entre os {k_extremos} melhores do ano ({exemplos_antigo}).",
    ressalva="Não quer dizer que zagueiro bom no alto evita queda, nem que o duelo aéreo passou a pesar mais de um período para o outro: a diferença entre os dois períodos pode ser sorte ({p_diferenca_chance}). Não se viu o primeiro turno prever o segundo. Na comparação declarada antes, quem sobe contra quem cai, a diferença aparece ({p_sc_chance}). Nos zagueiros (atletas com {corte_min_ind}+ minutos) aparece o mesmo lado, mas é um sinal {selo_zagueiros}: a lista do técnico individual nessa comparação não tem mais achados que a sorte, e são poucos zagueiros por time.",
    universo=UNIVERSOS["clube_antigo"],
    lac={
        "cai_metade_baixo": N("inteiro", "etapa_2.linhas[].cai_metade_baixo", "duelos_aereos_pct"),
        "cai_5_piores": N("inteiro", "etapa_2.linhas[].cai_entre_5_piores", "duelos_aereos_pct"),
        "k_extremos": D("inteiro", "k_extremos declarado (5)", []),
        "p_cr_chance": N("chance_em_1000", "etapa_2.linhas[].p_bruto_CR", "duelos_aereos_pct"),
        "cai_metade_baixo_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: cai_metade_baixo"),
        "n_cai_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: n_cai"),
        "n_cai_melhores_antigo": N("inteiro", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: len(cai_entre_5_melhores)"),
        "exemplos_antigo": N("texto", "etapa_2.linhas[].antigo_CR", "duelos_aereos_pct: cai_entre_5_melhores, 'CLUBE ANO, Nº', vírgulas e 'e'"),
        "p_diferenca_chance": N("chance_em_100", "etapa_2.linhas[].diferenca_entre_periodos_CR", "duelos_aereos_pct: p"),
        "p_sc_chance": G("chance_em_100", "etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_SC"),
        "selo_zagueiros": D("selo_minusculo", "regra do selo aplicada a ti_zaga_duelos_aereos_ganhos, comparação CR, lista tecnico_ind (p_excesso CR bruto)", ["etapa_2.linhas[indicador=ti_zaga_duelos_aereos_ganhos]", "etapa_3.por_familia.tecnico_ind.excesso.CR.bruto.p_excesso"]),
    },
    val={"cai_metade_baixo": "14", "cai_5_piores": "8", "k_extremos": "5", "p_cr_chance": "3 de cada 1.000 tentativas",
         "cai_metade_baixo_antigo": "9", "n_cai_antigo": "16", "n_cai_melhores_antigo": "2", "exemplos_antigo": "Remo 2021, 1º, e Criciúma 2019, 3º", "p_diferenca_chance": "11 de cada 100 tentativas",
         "selo_zagueiros": "fraco"},
    crit=[
        CONST("1. comparação do título declarada antes", False, papel="declarada", txt="não: quem cai contra o resto foi escolhida depois da pergunta do dono"),
        KM("p bruto < 0,05 (quem cai contra o resto)", "etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_CR", papel="p", op="<", lim=0.05, v=0.0034),
        KM("4. lista da comparação acima da sorte (técnico do time, quem cai contra o resto, p do excesso < 0,05)", "etapa_3.por_familia.tecnico_col.excesso.CR.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("conferência (descrição, não decide numa comparação escolhida depois): o 1º turno prevê o 2º, p parcial < 0,05", "etapa_7.linhas[indicador=duelos_aereos_pct].p_parcial", op="<", lim=0.05, decide=False),
        KM("conferência (descrição): 2018-2021, quem cai contra o resto, p < 0,05", "etapa_2.linhas[indicador=duelos_aereos_pct].antigo_CR", op="<", lim=0.05, sub="p", v=0.52, decide=False),
        KM("comparação declarada, quem sobe contra quem cai (descrição): firme, q < 0,05", "etapa_2.linhas[indicador=duelos_aereos_pct].q_SC", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, moderado só com a lista DELA acima da sorte; nunca forte",
           "comparacao_da_frase": "CR, escolhida depois da pergunta do dono",
           "moderado_se": "p_bruto_CR < 0,05 E etapa_3.por_familia.tecnico_col.excesso.CR.bruto.p_excesso < 0,05",
           "fraco_se": "p_bruto_CR < 0,05 E p_excesso CR bruto >= 0,05",
           "forte": "impossível: comparação escolhida depois tem teto moderado; q_CR não conta como passar na conta dos testes",
           "zagueiros": "ti_zaga_duelos_aereos_ganhos CR: p 0,0014, lista tecnico_ind CR 8 contra 5 (p 0,19) → fraco",
           "saiu_em_15_09": "o 'E sobreviver ao desconto do dinheiro' da regra da comparação escolhida depois, e o mesmo clube no ano seguinte",
           "proibido": ["'não antes' como diferença entre períodos", "usar q_CR para o selo", "'perdeu mais duelos aéreos' (a medida é porcentagem ganha)", "'continua entre elencos de valor parecido'"]},
    p=P("etapa_2.linhas[indicador=duelos_aereos_pct].p_bruto_CR", 0.0034), ceticos=True,
    rev="reconferência 14/09 (decisão 1 do dono): fraco → moderado de 2022 a 2025, com 'em 2018-2021 não se repetiu' escrito; título pela porcentagem ganha ('ganhou uma parte menor'), não 'perdeu mais'",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Da regra da comparação escolhida depois sai o 'E sobreviver ao desconto do dinheiro'; fica a lista dela (13 contra 1, p 0,0024). Saem a frase do clube no ano seguinte e 'na declarada some entre elencos de valor parecido': quem sobe contra quem cai é firme por pouco (q 0,043), só descrição",
    faixa_keep=True,
    rodape_ops=[("replace", "selo: FRACO na rodada de conserto (antes MODERADO) pela regra da comparação escolhida depois de olhar", "**selo: MODERADO de 2022 a 2025 na reconferência de 14/09 (decisão 1 do dono)**: comparação escolhida depois, com a lista dela acima da sorte (13 contra 1, p 0,002); na rodada de conserto tinha ficado FRACO"),
                ("replace", "cai x resto (escolhida depois, só descrição):", "cai x resto (escolhida depois da pergunta; é a comparação do título e decide o selo pela decisão 1 do dono):"),
                ("replace", "13 achados contra 1 do sorteio (p do excesso 0,002), que não conta para o selo", "13 achados contra 1 do sorteio (p do excesso 0,002), que é a condição da decisão 1 para chegar a moderado (o q da família montada depois não conta como passar na conta dos testes)"),
                ("append", " · contagens da frase (`r4_saida.json`): 14 de 16 rebaixados na metade de baixo e 8 entre os 5 piores do ano")],
))
