C.append(conc(
    id="J6", tema="jogo_e_padroes", etapa="etapa_2", selo="moderado", declarada=True,
    titulo="Os meias de quem sobe dão mais passes-chave",
    frase="{m_sobe} passe-chave por jogo por meia (atletas com {corte_min_ind}+ minutos), contra {m_meio} no meio da tabela e em quem cai, de {ano_ini} a {ano_fim}. É um sinal {selo}: é firme contando os {n_familia_tecnico_ind} indicadores individuais, mas não houve como conferir por outro caminho: não há técnico individual em {periodo_antigo} nem jogo a jogo individual.",
    numero="Olhando só este número, o acaso produziria a diferença em {p_chance}.",
    ressalva="Não quer dizer que contratar meia de passe-chave faz subir: o número pode vir de quem estava em campo naquele ano, e passe-chave depende de alguém finalizar.",
    universo=UNIVERSOS["tec_ind"],
    lac={
        "m_sobe": G("dec2", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].m_sobe"),
        "m_meio": G("dec2", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].m_meio"),
        "p_chance": G("chance_em_1000", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM"),
    },
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 92 indicadores individuais (q < 0,05)", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ti_meio_passes_chave_90].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: técnico individual não processado em 2018-2021 e sem jogo a jogo individual"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do técnico individual, quem sobe contra o meio, acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)", "moderado_se": "q_SM < 0,05 sem conferência testável",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte", "proibido": ["'resiste ao dinheiro'", "'não se viu o mesmo clube repetir'"]},
    p=P("etapa_2.linhas[indicador=ti_meio_passes_chave_90].p_bruto_SM", 0.00026), ceticos=True,
    rev="reconferência 14/09: passou pelo cético de números (recalculado do serieb_tecnico.csv); média em duas casas",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Saem 'resiste ao dinheiro' e 'não se viu o mesmo clube repetir'; motivo: firme (q 0,020) sem conferência testável",
    faixa_keep=True,
    rodape_ops=[("replace", "ρ de repetição 0,20", "reconferido pelo cético de 14/09 a partir de `serieb_tecnico.csv`")],
))
