C.append(conc(
    id="J7", tema="jogo_e_padroes", etapa="etapa_2", selo="fraco", declarada=True,
    titulo="Os meias de quem sobe ganham mais duelos defensivos; quem cai não se mostrou bem pior",
    frase="Quem mais destoa é quem sobe, para cima: {sobe_metade_cima} dos {n_prom} que subiram ficaram na metade de cima do ano em duelo defensivo ganho pelos meias, de {ano_ini} a {ano_fim} ({med_sobe}% contra {med_meio}% no meio da tabela). É um sinal {selo}: entre os {n_familia_tecnico_ind} números individuais testados, o número dos que separam é o que a sorte produz.",
    numero="Olhando só este número, o acaso produziria a diferença contra o meio em {p_chance}. Quem cai não se mostrou bem pior: contra o meio da tabela não se viu diferença, e contra o resto a diferença fica no limite do acaso.",
    ressalva="Não quer dizer que meia que ganha duelo defensivo faz subir. Não há como conferir em {periodo_antigo}, nem com jogo a jogo individual.",
    universo=UNIVERSOS["tec_ind"],
    lac={
        "sobe_metade_cima": N("inteiro", "etapa_2.linhas[].sobe_metade_cima", "ti_meio_duelos_defensivos_ganhos"),
        "med_sobe": N("dec1", "etapa_2.linhas[].mediana_sobe", "ti_meio_duelos_defensivos_ganhos (valor cru)"),
        "med_meio": N("dec1", "etapa_2.linhas[].mediana_meio", "ti_meio_duelos_defensivos_ganhos (valor cru)"),
        "p_chance": G("chance_em_100", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM"),
    },
    val={"sobe_metade_cima": "13", "med_sobe": "59,3", "med_meio": "57,2"},
    crit=[
        CONST("1. comparação declarada antes: quem sobe contra o meio", True, papel="declarada", txt="sim"),
        KM("p bruto < 0,05", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM", papel="p", op="<", lim=0.05),
        KM("2. firme: conta dos 92 indicadores individuais (q < 0,05)", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].q_SM", papel="q", op="<", lim=0.05),
        KM("firme com folga (q < 0,025)", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].q_SM", papel="q_folga", op="<", lim=0.025),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: técnico individual não processado em 2018-2021 e sem jogo a jogo individual"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista inteira do técnico individual acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SM.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("quem sobe contra o resto (escolhida depois; descrição): lista acima da sorte", "etapa_3.por_familia.tecnico_ind.excesso.SR.bruto.p_excesso", op="<", lim=0.05, decide=False),
        KM("quem cai contra o resto (escolhida depois; descrição): p < 0,05", "etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_CR", op="<", lim=0.05, v=0.093, txt="0,093: zona cinzenta", decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "fraco_se": "p_bruto_SM < 0,05 E q_SM >= 0,05 E a lista do técnico individual SM no nível da sorte",
           "parte_depois_de_olhar": "SR: lista 10 contra 5, p 0,085 → teto fraco; CR: zona cinzenta; CM p 0,29 → 'não se viu'",
           "saiu_em_15_09": "o desconto do dinheiro e o mesmo clube no ano seguinte; a citação da etapa 10 (a medida saiu da lista fixa de lá)"},
    p=P("etapa_2.linhas[indicador=ti_meio_duelos_defensivos_ganhos].p_bruto_SM", 0.01208), ceticos=True,
    rev="reconferência 14/09: regra do dono reaplicada à parte 'quem sobe contra o resto' (lista 0,082): segue fraco; mediana crua no molde",
    rev15="rodada sem dinheiro (15/09): segue FRACO (q 0,22; lista 0,082). Saem 'continua entre times de valor de elenco parecido' e 'não se viu o clube repetir'; a ressalva não cita mais a etapa 10, porque `ti_meio_duelos_defensivos_ganhos` saiu da lista fixa de lá",
    faixa_keep=True, rodape_ops=[("append", " · contagem da frase (`r4_saida.json`): 13 de 16 promovidos na metade de cima do ano · regra do dono de 14/09 reaplicada: quem sobe contra o resto é comparação escolhida depois e a lista dela não passa da sorte (0,082), então não sobe de fraco")],
))
