C.append(conc(
    id="M4", tema="mercado_e_contratacao", etapa="etapa_13", selo="fraco", declarada=True,
    titulo="Na zaga e na lateral, o perfil físico que a nota de encaixe procura é fraco",
    frase="Contando o clube como um caso, de {ano_ini} a {ano_fim}, algumas medidas físicas da nota separam quem subiu de quem caiu na zaga e na lateral ({bruto_zaga} de {n_zaga} e {bruto_lateral} de {n_lateral} no número cru; descontado só o rodízio, {sobra_zaga} e {sobra_lateral}), mas nenhuma é firme contando as medidas do setor, e a lista de nenhum dos dois setores tem mais achados do que a sorte. É um sinal {selo}.",
    numero="Na zaga, a lista tem {bruto_zaga} achados quando a sorte daria {nulo_zaga}; na lateral, {bruto_lateral} contra {nulo_lateral}. O ataque tem conclusão própria (M8), e o meio-campo também (M5).",
    ressalva="Não quer dizer que físico não conta nesses setores, nem que a nota escolhe jogador ruim: com {n_sobe} clubes contra {n_cai}, só diferenças grandes aparecem. A nota mira quem sobe contra quem cai, não contra o meio. O ataque, que estava junto nesta conclusão, foi separado depois de olhar os números (M8); a família e a comparação foram declaradas antes.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos atletas do setor com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.p5_clube"),
        "bruto_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.p5_clube"),
        "n_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.testes"),
        "n_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.testes"),
        "sobra_zaga": G("zero_por_extenso", "sobecai_corrigido_por_clube.zaga.passam5_rod"),
        "sobra_lateral": G("zero_por_extenso", "sobecai_corrigido_por_clube.lateral.passam5_rod"),
        "nulo_zaga": G("inteiro", "sobecai_corrigido_por_clube.zaga.excesso.SC.bruto.nulo_mediana"),
        "nulo_lateral": G("inteiro", "sobecai_corrigido_por_clube.lateral.excesso.SC.bruto.nulo_mediana"),
    },
    crit=[
        CONST("1. família (medidas da nota por setor, clube como caso) e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim"),
        KM("alguma medida com p bruto < 0,05 por clube (zaga ou lateral)", "sobecai_corrigido_por_clube", papel="p", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="p5_clube"),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube", papel="rod", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="passam5_rod"),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube", papel="q", op=">", lim=0, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="bh5_clube"),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube", papel="q_folga", op="<", lim=0.025, ag="min", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="itens.q_clube"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022, e o clube não se repete de um setor para o outro"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do setor acima da sorte (p do excesso < 0,05) na zaga ou na lateral", "sobecai_corrigido_por_clube", papel="lista", op="<", lim=0.05, ag="algum", filtro={"tipo": "dicionario", "nome": "setor", "valores": ["zaga", "lateral"]}, sub="excesso.SC.bruto.p_excesso"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum), por setor, nos dois setores juntos (os dois dão o mesmo selo)",
           "fraco_se": "algum p bruto < 0,05 por clube E nenhuma firme por clube E a lista do setor no nível da sorte (zaga e lateral)",
           "partida": "resposta d do dono (14/09, noite): M4 = zaga e lateral; o ataque virou a M8. A família e a comparação foram declaradas antes; a divisão do título foi decidida depois de olhar e fica registrada",
           "saiu_em_15_09": "o desconto do valor total (passam5_liq2) e 'fraco nos três setores' (ficou falso no ataque)",
           "proibido": ["'menos do que o acaso daria'", "selo único para os quatro setores", "'em boa parte o que o elenco caro já traz' (quantidade não medida, ausência afirmada)", "'descontados o valor do elenco e o rodízio'"]},
    p=P("sobecai_corrigido_por_clube.zaga.excesso.SC.bruto.p_excesso", 0.127), ceticos=True,
    rev="reconferência 14/09: 'o perfil é, em boa parte, o que o elenco caro já traz' virou 'descontados valor e rodízio, não se viu o perfil da nota distinguir quem sobe de quem cai', igual no documento e no spec; ponte com a FIS-10; o p5_clube gravado é a contagem crua (um nome só)",
    rev15="rodada sem dinheiro (15/09): segue FRACO, mas só zaga e lateral (resposta d do dono). Só com o rodízio: zaga 3 sobram e lista 0,127; lateral 2 sobram e lista 0,151; nenhuma firme por clube. O ataque saiu para a M8 (moderado): 'fraco nos três setores' ficava falso lá",
    faixa_keep=True,
    rodape_texto="rodada sem dinheiro de 15/09 (`prototipo_novo.json`, ainda não gravado no projeto) · medidas da nota por setor, clube como caso, quem sobe contra quem cai (16 × 16), média do clube ponderada por minuto · **zaga**: 34 medidas, 4 com p bruto < 0,05, nenhuma firme por clube (menor q 0,23), 3 continuam só com o rodízio (velocidade de pico das 5 melhores, corridas recebidas e corridas acima de alta velocidade), lista 4 contra 1 do sorteio, p do excesso 0,127 ([7, 17, 0]) · **lateral**: 35 medidas, 4 com p bruto < 0,05, nenhuma firme (menor q 0,24), 2 continuam só com o rodízio (velocidade de pico das 5 melhores e tempo até o sprint), lista 4 contra 1, p 0,151 ([7, 17, 1]) · na conta de 14/09, com o desconto do valor, não sobrava nenhuma nos três setores · a marca da etapa 13 (sobecai_corrigido_por_clube.<setor>.excesso.SC.bruto.lista) diz 'a lista não tem mais achados do que a sorte' na zaga e na lateral · onde ver na aba: etapa 13",
))
