C.append(conc(
    id="M5", tema="mercado_e_contratacao", etapa="etapa_13", selo="moderado", declarada=True,
    titulo="No meio-campo, o perfil físico que a nota procura continua de pé",
    frase="No meio-campo, entre quem subiu e quem caiu de {ano_ini} a {ano_fim}, {bruto_meio} das {n_meio} medidas da nota separam no número cru, {firmes_meio} são firmes contando as medidas do setor, e {n_sobra_meio} continuam descontado só o rodízio ({nomes_sobra_meio}). É um sinal {selo}: não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="Lista do meio-campo: {bruto_meio} achados no número cru, quando a sorte daria {nulo_meio}; descontado só o rodízio, a lista já não tem mais achados que a sorte, e a regra usa a lista crua.",
    ressalva="Não quer dizer 'contrate meia que arranca e gira rápido', nem que o físico só conta no meio-campo: a diferença entre setores não foi testada. Contra o meio da tabela, a arrancada dos meias é um sinal fraco (FIS-06). A zaga e a lateral estão na M4 e o ataque na M8. Não contradiz a FIS-04: lá são as medidas do catálogo contadas por time; aqui, as da nota no meio-campo, com média ponderada por minuto no clube.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos meias com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.p5_clube"),
        "n_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.testes"),
        "firmes_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.bh5_clube"),
        "n_sobra_meio": G("inteiro_por_extenso", "sobecai_corrigido_por_clube.meio.passam5_rod"),
        "nomes_sobra_meio": D("texto", "nomes simples do glossário de sobecai_corrigido_por_clube.meio.sobreviventes_rod, vírgulas e 'e'", ["sobecai_corrigido_por_clube.meio.sobreviventes_rod"]),
        "nulo_meio": G("inteiro", "sobecai_corrigido_por_clube.meio.excesso.SC.bruto.nulo_mediana"),
    },
    val={"nomes_sobra_meio": "arrancadas que viram sprint, distância em alta intensidade e sprints com a bola do adversário, corridas para a área, e tempo de giro de 90° e de 180°"},
    crit=[
        CONST("1. família (medidas da nota por setor, clube como caso) e comparação quem sobe contra quem cai declaradas antes", True, papel="declarada", txt="sim (a nota mira essa comparação)"),
        KM("alguma medida com p bruto < 0,05 por clube", "sobecai_corrigido_por_clube.meio.p5_clube", papel="p", op=">", lim=0),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube.meio.passam5_rod", papel="rod", op=">", lim=0),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube.meio.bh5_clube", papel="q", op=">", lim=0),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube.meio.itens", papel="q_folga", op="<", lim=0.025, ag="min", sub="q_clube"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista crua do meio-campo acima da sorte (p do excesso < 0,05)", "sobecai_corrigido_por_clube.meio.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("a mesma lista descontado só o rodízio (descrição)", "sobecai_corrigido_por_clube.meio.excesso.SC.rod.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "firme por clube (algum q_clube < 0,05) E alguma continua só com o rodízio E nenhuma conferência testável",
           "forte_se": "firme por clube E pelo menos uma conferência testável, todas passando (não há nenhuma)",
           "nota": "o excesso decide pela lista crua (regra da régua); só com o rodízio a lista dá 0,095, dito no número",
           "saiu_em_15_09": "os níveis liq e liq2 (valor e valor + rodízio) e o 'q das sobreviventes' (virou q_rod por item)",
           "proibido": ["'só se sustenta no meio-campo'", "juntar M5 e M4 numa vaga das cinco", "'entre elencos de valor e rodízio parecidos'"]},
    p=P("sobecai_corrigido_por_clube.meio.menor_p_rod", 0.00035), ceticos=True,
    rev="reconferência 14/09: caminhos com nível (excesso.SC.bruto); itens com p_liq, p_liq2 e q_liq2; declaração do teste por clube e da semente acertada com o que mediu",
    rev15="rodada sem dinheiro (15/09): segue MODERADO. Firme por clube (5 com q < 0,05, a menor 0,023) e 6 continuando só com o rodízio (menor p 0,0004), sem conferência testável. A regra decide pela lista bruta (11 contra 1, p 0,028); só com o rodízio ela dá 0,095 e isso fica escrito. Sai 'entre elencos de valor e rodízio parecidos' e 'nos outros setores não sobra nenhuma' (o ataque sobra, M8)",
    faixa_keep=True, rodape_ops=[],
))
