C.append(conc(
    id="M8", tema="mercado_e_contratacao", etapa="etapa_13", selo="moderado", declarada=True,
    titulo="No ataque, as medidas físicas da nota de encaixe separam quem subiu de quem caiu",
    frase="Contando o clube como um caso, de {ano_ini} a {ano_fim}, {bruto_ataque} das {n_ataque} medidas físicas da nota no ataque separam quem subiu de quem caiu no número cru; {firmes_ataque} são firmes contando as medidas do setor ({frase_folga_ataque}), e {sobra_ataque} continuam descontado só o rodízio. É um sinal {selo}: não houve como conferir por outro caminho, porque não há físico por rodada nem antes de {ano_ini}.",
    numero="A lista do ataque tem {bruto_ataque} achados quando a sorte daria {nulo_ataque}, e continua com mais achados do que a sorte descontado só o rodízio.",
    ressalva="Não quer dizer 'contrate atacante que corre', nem que físico no ataque faz subir. Elenco valioso tende a ter isso; o estudo não separa as duas coisas. A separação entre o ataque e a zaga e a lateral (M4) foi feita depois de olhar os números; a família e a comparação foram declaradas antes. Vai para o mesmo lado da FIS-10, que conta as medidas do catálogo por time.",
    universo="{n_sobe} clubes que subiram e {n_cai} que caíram de {ano_ini} a {ano_fim}, cada clube como um caso (média ponderada por minuto dos atacantes com {corte_min_fisico}+ minutos rastreados); o meio da tabela entra só no sorteio",
    lac={
        "bruto_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.p5_clube"),
        "n_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.testes"),
        "firmes_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.bh5_clube"),
        "frase_folga_ataque": D("texto", "menor q_clube do setor < 0,025: 'a mais firme com folga'; senão 'todas por pouco'", ["sobecai_corrigido_por_clube.ataque.itens"]),
        "sobra_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.passam5_rod"),
        "nulo_ataque": G("inteiro", "sobecai_corrigido_por_clube.ataque.excesso.SC.bruto.nulo_mediana"),
    },
    val={"frase_folga_ataque": "todas por pouco"},
    crit=[
        CONST("1. família (medidas da nota por setor, clube como caso) e comparação quem sobe contra quem cai declaradas antes; a divisão do título foi feita depois de olhar", True, papel="declarada", txt="sim"),
        KM("alguma medida com p bruto < 0,05 por clube", "sobecai_corrigido_por_clube.ataque.p5_clube", papel="p", op=">", lim=0),
        KM("5. alguma continua descontado só o rodízio (p_rod < 0,05)", "sobecai_corrigido_por_clube.ataque.passam5_rod", papel="rod", op=">", lim=0),
        KM("2. firme por clube: alguma medida com q < 0,05 contando as do setor", "sobecai_corrigido_por_clube.ataque.bh5_clube", papel="q", op=">", lim=0),
        KM("firme com folga: menor q por clube < 0,025", "sobecai_corrigido_por_clube.ataque.itens", papel="q_folga", op="<", lim=0.025, ag="min", sub="q_clube"),
        CONST("3. há conferência testável por outro caminho", False, papel="ha_conf", txt="não: sem físico por rodada nem antes de 2022"),
        CONST("há uma conferência testável só", False, papel="uma_conf", txt="não: não há nenhuma"),
        KM("4. lista do ataque acima da sorte (p do excesso < 0,05)", "sobecai_corrigido_por_clube.ataque.excesso.SC.bruto.p_excesso", papel="lista", op="<", lim=0.05),
        KM("a mesma lista descontado só o rodízio (descrição)", "sobecai_corrigido_por_clube.ataque.excesso.SC.rod.p_excesso", op="<", lim=0.05, decide=False),
    ],
    regra={"regua": "régua final de 15/09 (regime comum)",
           "moderado_se": "firme por clube (algum q_clube < 0,05) E alguma continua só com o rodízio E nenhuma conferência testável",
           "partida": "resposta d do dono (14/09, noite): o ataque sai da M4 e vira conclusão própria (declaracoes_novas.conclusao_ataque_por_clube, id M8); família e comparação declaradas antes, título partido depois de olhar",
           "ressalva": "sem desconto e sem receita (resposta b do dono); a medida da relação com o valor por item vai em sobecai_corrigido_por_clube.ataque.itens[].rho_valor (descrição, nunca teto)",
           "proibido": ["'contrate atacante que corre'", "'o ataque decide a subida'", "juntar M8 e M5 numa conclusão só (mudaria o título depois de olhar)", "'descontados valor e rodízio'"]},
    p=P("sobecai_corrigido_por_clube.ataque.menor_p_rod", 0.00072), ceticos=False, nova_em="2026-09-15 (partida da M4, resposta d do dono)",
    rev="nova na rodada sem dinheiro de 15/09: era o setor ataque dentro da M4",
    rev15="nova em 15/09 (resposta d do dono): MODERADO. Firme por clube (11 medidas com q < 0,05, a menor 0,043, todas por pouco), 13 continuam só com o rodízio (menor p 0,0007), lista 13 contra 1 (p 0,010 no bruto, 0,0089 só com o rodízio); sem conferência testável. Na M4 de 14/09 o ataque aparecia com 'nada sobra', pelo desconto do valor",
    faixa_texto="<sub>**Vale também pela faixa de pontos?** não medido (conclusão partida da M4 em 15/09).</sub>",
    rodape_texto="nova na rodada sem dinheiro de 15/09 (`prototipo_novo.json`, ainda não gravado no projeto), partida da M4 pela resposta d do dono · medidas da nota no ataque, clube como caso, quem sobe contra quem cai (16 × 16), média do clube ponderada por minuto (110 atletas de quem subiu, 140 de quem caiu) · 35 medidas, 13 com p bruto < 0,05, 11 firmes por clube (q de 0,043 para cima: todas por pouco), 13 continuam só com o rodízio (menor p 0,00072) · lista 13 contra 1 do sorteio, p do excesso 0,010 no bruto e 0,0089 só com o rodízio ([7, 17, 3], 10.000 sorteios) · as que continuam: sprints e distância em alta intensidade com a bola do adversário, tempo de giro de 90°, distância e contagem de alta intensidade, sprint (distância e contagem), corrida em alta velocidade (distância e contagem), tempo até a corrida forte depois de mudar de direção, velocidade de pico, arrancada que vira sprint e metros por minuto com a bola do adversário · a relação de cada medida com o valor do elenco vai em `itens[].rho_valor` (spn_s ρ 0,38, p 0,0005), só descrição · onde ver na aba: etapa 13",
))
