C.append(conc(
    id="ORI-01", tema="dinheiro_e_elenco", etapa="conclusoes_base", selo="fraco", declarada=False,
    titulo="Quem acabou de cair da Série A subiu mais e não caiu",
    frase="De {ano_ini_ori} a {ano_fim}, quem tinha acabado de cair da Série A subiu {sub_A} vezes em {n_A} ({pct_sub_A}%) e {cai_A_extenso}. Quem já estava na B subiu {sub_B} em {n_B} ({pct_sub_B}%) e caiu {cai_B}. É um sinal {selo}: a comparação da origem foi montada depois de olhar os números, e não há lista de onde ela saia para comparar com a sorte.",
    numero="Só existe valor de elenco de {ano_ini} a {ano_fim}; nesse período estão {n_A_valor} dos {n_A} casos, e eles tinham tipicamente o {posto_mediano_A}º elenco mais valioso do ano.",
    ressalva="Não quer dizer que cair da A ajuda a subir: esses clubes chegam com um dos elencos mais valiosos do ano (DIN-01), e o estudo não separa as duas coisas. Que ninguém caiu vale sem exceção para os {n_A} casos (e os {n_A_sens} contando {ano_ini_sens}), mas não é regra.",
    universo="{n_origem} clube-temporadas da Série B de {ano_ini_ori} a {ano_fim} ({n_A} vieram da Série A, {n_B} já estavam na B, {n_C} vieram da C), com a origem da base pública gravada; valor de elenco só nas {n_origem_valor} de {ano_ini} a {ano_fim}; {ano_parcial} fica fora de toda conta",
    lac={
        "ano_ini_ori": N("ano", "conclusoes_base.origem.anos_da_conta", "[0]"),
        "sub_A": N("inteiro", "conclusoes_base.origem.por_origem", "A.subiu"),
        "n_A": N("inteiro", "conclusoes_base.origem.por_origem", "A.n"),
        "pct_sub_A": D("inteiro", "100 × sub_A / n_A", ["sub_A", "n_A"]),
        "cai_A_extenso": D("texto", "0 -> 'não caiu nenhuma vez'; senão 'caiu N vezes'", ["conclusoes_base.origem.por_origem"]),
        "sub_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.subiu"),
        "n_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.n"),
        "pct_sub_B": D("inteiro", "100 × sub_B / n_B", ["sub_B", "n_B"]),
        "cai_B": N("inteiro", "conclusoes_base.origem.por_origem", "B.caiu"),
        "n_C": N("inteiro", "conclusoes_base.origem.por_origem", "C.n"),
        "n_origem": D("inteiro", "n_A + n_B + n_C", ["n_A", "n_B", "n_C"]),
        "n_origem_valor": N("inteiro", "conclusoes_base.origem.dinheiro", "soma de por_origem[].n (só descrição)"),
        "n_A_valor": N("inteiro", "conclusoes_base.origem.dinheiro", "por_origem.A.n (só descrição)"),
        "posto_mediano_A": N("inteiro", "conclusoes_base.origem.dinheiro", "por_origem.A.posto_mediano (só descrição)"),
        "n_A_sens": N("inteiro", "conclusoes_base.origem.sensibilidade", "A.n (anos_sensibilidade)"),
        "ano_ini_sens": N("ano", "conclusoes_base.origem.anos_sensibilidade", "[0]"),
    },
    val={"ano_ini_ori": "2019", "sub_A": "11", "n_A": "28", "pct_sub_A": "39", "cai_A_extenso": "não caiu nenhuma vez", "sub_B": "13", "n_B": "84", "pct_sub_B": "15", "cai_B": "23", "n_C": "28",
         "n_origem": "140", "n_origem_valor": "80", "n_A_valor": "16", "posto_mediano_A": "3", "n_A_sens": "32", "ano_ini_sens": "2018"},
    crit=[
        CONST("1. comparação declarada antes", False, papel="declarada", txt="não: a análise da origem foi declarada em 14/09, depois de olhar"),
        KM("A contra B, Fisher bilateral, p < 0,05 (queda ou subida)", "conclusoes_base.origem.fisher.A_x_B", papel="p", op="<", lim=0.05, ag="algum", sub=["p_queda", "p_subida"],
           v={"p_queda": 0.00081, "p_subida": 0.015}, txt="queda 0,0008; subida 0,015"),
        CONST("4. lista de onde a comparação saia, com mais achados que a sorte", False, papel="lista", txt="não há lista: é uma comparação só"),
    ],
    regra={"regua": "régua final de 15/09 (regime comum): comparação escolhida depois de olhar, sem lista → teto fraco",
           "comparacao": "A x B, Fisher bilateral, subida e queda (declaracoes_novas.origem)",
           "fraco_se": "p Fisher < 0,05 E comparação montada depois de olhar sem lista",
           "moderado_se": "impossível sem lista declarada",
           "ressalva": "sem desconto e sem receita: 'esses clubes chegam com um dos elencos mais valiosos do ano (DIN-01); o estudo não separa as duas coisas' (resposta b do dono)",
           "saiu_em_15_09": "a permutação dentro de ano × quartil de valor, a razão de verossimilhança e as subidas e quedas 'esperadas pelo valor' (eram desconto)",
           "pre_requisito": "bases.origem com sha256",
           "proibido": ["'de onde o clube vem pesa mais que qualquer número de jogo'", "'nunca cai' sem o universo", "juntar 2019-2025 e 2022-2025 sem dizer", "'é o elenco caro que vem junto' como fato",
                        "'é o que o elenco caro (ou o valor) já prevê' como fato", "'descontado o valor do elenco, não se viu a origem acrescentar nada' (o desconto saiu em 15/09)"]},
    p=P("conclusoes_base.origem.fisher.A_x_B.p_queda", 0.00081), ceticos=True,
    rev="reconferência 14/09: subidas esperadas '7 a 8' e quedas 'menos de 2 em qualquer conta (0,6 a 1,75)', com a conta da taxa do quartil sem os próprios clubes da A; raiz conclusoes_base.origem",
    rev15="rodada sem dinheiro (15/09): segue FRACO. Saem do selo e do texto a permutação dentro de ano × quartil, a razão de verossimilhança e as quedas e subidas 'esperadas pelo valor'; do título sai 'descontado o valor do elenco, não se viu a origem acrescentar nada'. Fica a ressalva sem desconto: esses clubes chegam com um dos elencos mais valiosos do ano, e o estudo não separa as duas coisas. A regra_maquina ganha a linha 'escolhida depois, sem lista → fraco'",
    faixa_keep=True,
    rodape_ops=[("replace", "subidas esperadas 7,2 a 7,5 sem penalização", "subidas esperadas 7,2 a 7,5 sem penalização · **conta fora da amostra** (`cf_num/v_ori.py`, taxa do quartil de posto sem os próprios clubes da A): subidas 8,21 esperadas, quedas 0,71; faixas de 3 postos (não declaradas, só descrição): 11,5 e 0,40 sem os A, 7,7 e 0,33 com eles · a frase de 14/09 usava as especificações declaradas mais essas duas contas: subidas 7,2 a 8,2, quedas 0,57 a 1,75 · **rodada sem dinheiro de 15/09:** essas contas de 'esperado pelo valor' e a permutação deixaram de decidir o selo e de ir para a frase; ficam aqui como registro")],
))
